(() => {
  'use strict';
  const MBB = window.MBBBiologia = window.MBBBiologia || {};
  const q = MBB.choice;

  const lessonHtml = `
    <section class="biology-opening">
      <span class="lesson-kicker">Uma situação real para investigar</span>
      <div class="hero-box biology-story">
        <strong class="card-title">Em um parque urbano, visitantes começaram a deixar restos de alimento perto de uma trilha. Alguns meses depois, a equipe registrou mais quatis nessa área, lixo espalhado, alterações no comportamento dos animais e conflitos mais frequentes entre indivíduos.</strong>
        <p>Seria incorreto concluir, apenas olhando a cena, que “os quatis aumentaram porque havia comida” e encerrar a investigação. A disponibilidade de alimento é uma hipótese plausível, mas um ecossistema envolve <strong>muitas relações simultâneas</strong>: alimento natural, abrigo, água, predadores, competidores, doenças, presença humana, clima e capacidade do ambiente de sustentar a população.</p>
        ${q('A','Faça uma hipótese','Qual pergunta é mais científica para começar a investigar a mudança observada?',[['a','Qual animal é mais bonito no parque?'],['b','Quais fatores bióticos e abióticos mudaram e como eles podem estar relacionados à população de quatis?'],['c','Como provar que existe uma única causa?']],'b','Correto. Ecologia procura relações entre organismos e ambiente e evita assumir uma causa única sem evidências.','O problema exige investigar interações e variáveis do sistema, não uma opinião ou uma causa escolhida antecipadamente.')}
        <p class="central-question"><strong>Nossa missão:</strong> entender <strong>como matéria e energia conectam os seres vivos</strong> e por que alterar uma parte de um ecossistema pode produzir efeitos em outras partes.</p>
      </div>
    </section>

    <section>
      <h3>1. Ecologia começa definindo quem interage com quem — e em qual escala</h3>
      <p>Um mesmo quati pode ser analisado como indivíduo, membro de uma população, participante de uma comunidade e componente de um ecossistema. Essas palavras não são sinônimos: cada nível responde a uma pergunta diferente.</p>
      <div class="life-map">
        <div><strong>Organismo</strong><span>um indivíduo</span></div><div><strong>População</strong><span>indivíduos da mesma espécie numa área e período</span></div><div><strong>Comunidade</strong><span>populações de espécies diferentes</span></div><div><strong>Ecossistema</strong><span>comunidade + ambiente físico em interação</span></div><div><strong>Biosfera</strong><span>conjunto dos ecossistemas da Terra</span></div>
      </div>
      <div class="two-col"><div class="example-box"><strong class="card-title">Hábitat</strong><p>É o lugar ou conjunto de condições onde uma espécie vive.</p></div><div class="example-box"><strong class="card-title">Nicho ecológico</strong><p>Envolve seu modo de vida e relações: recursos utilizados, período de atividade, alimentação, interações e tolerâncias ambientais.</p></div></div>
      ${q('B','Escala correta','Todos os quatis de uma área do parque, considerados no mesmo período, formam principalmente:',[['a','uma população'],['b','uma biosfera'],['c','um fator abiótico']],'a','Isso. São indivíduos da mesma espécie considerados em uma área e período definidos.','População exige indivíduos da mesma espécie; comunidade inclui espécies diferentes.')}
    </section>

    <section>
      <h3>2. Um ecossistema inclui seres vivos e condições físicas</h3>
      <p><strong>Fatores bióticos</strong> são os seres vivos e suas interações. <strong>Fatores abióticos</strong> incluem luz, água, temperatura, solo, salinidade, pH e outras condições físico-químicas. Eles não atuam separadamente: a disponibilidade de água, por exemplo, afeta plantas e animais e também modifica relações entre espécies.</p>
      <div class="visual-box"><strong class="card-title">Ecossistema não é apenas uma lista de espécies</strong><svg class="lesson-visual" viewBox="0 0 760 260" role="img" aria-label="Diagrama mostrando fatores abióticos como luz, água e temperatura conectados a produtores, consumidores e decompositores."><defs><marker id="bio01a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#2f7d32"/></marker></defs><rect x="25" y="55" width="180" height="140" rx="15" fill="#eef7ff" stroke="#aac9df"/><text x="115" y="90" text-anchor="middle" font-size="18" font-weight="900">Ambiente físico</text><text x="115" y="122" text-anchor="middle" font-size="14">luz • água • solo</text><text x="115" y="146" text-anchor="middle" font-size="14">temperatura • nutrientes</text><rect x="290" y="35" width="180" height="80" rx="15" fill="#edf8ee" stroke="#a9cfac"/><text x="380" y="70" text-anchor="middle" font-size="18" font-weight="900">Produtores</text><text x="380" y="94" text-anchor="middle" font-size="13">plantas e algas</text><rect x="555" y="35" width="180" height="80" rx="15" fill="#fff5e8" stroke="#e3c293"/><text x="645" y="70" text-anchor="middle" font-size="18" font-weight="900">Consumidores</text><text x="645" y="94" text-anchor="middle" font-size="13">animais e outros</text><rect x="420" y="155" width="180" height="75" rx="15" fill="#f6f0ff" stroke="#cdbce8"/><text x="510" y="190" text-anchor="middle" font-size="18" font-weight="900">Decompositores</text><text x="510" y="213" text-anchor="middle" font-size="13">fungos e bactérias</text><path d="M205 105 H286" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio01a)"/><path d="M470 75 H551" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio01a)"/><path d="M640 116 C620 145 600 160 598 168" fill="none" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio01a)"/><path d="M420 192 C300 215 205 190 170 160" fill="none" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio01a)"/></svg><p class="visual-caption">As setas representam conexões gerais. Ecossistemas reais possuem muitas relações adicionais.</p></div>
    </section>

    <section>
      <h3>3. Cadeia alimentar é um recorte; teia alimentar é mais próxima da realidade</h3>
      <p>Uma cadeia alimentar mostra uma sequência simplificada de transferência de matéria e energia. Em ecossistemas reais, um organismo geralmente participa de várias relações alimentares, formando uma <strong>teia alimentar</strong>.</p>
      <div class="concept-flow"><div><strong>Produtor</strong><span>capim</span></div><div class="flow-arrow">→</div><div><strong>Consumidor primário</strong><span>gafanhoto</span></div><div class="flow-arrow">→</div><div><strong>Consumidor secundário</strong><span>sapo</span></div></div>
      <p>As setas costumam indicar a direção da transferência de matéria e energia: do organismo que serve de alimento para aquele que o consome. Decompositores atuam sobre matéria orgânica de vários níveis e devolvem nutrientes ao ambiente.</p>
      <div class="note-box"><strong>Não existe “animal mais importante” pela posição na cadeia</strong><p>Produtores, consumidores e decompositores exercem papéis diferentes e interdependentes. A retirada de uma espécie pode ou não gerar efeitos intensos; isso depende da rede de interações e da capacidade de outras espécies exercerem funções semelhantes.</p></div>
    </section>

    <section>
      <h3>4. Matéria circula; energia flui</h3>
      <p>Átomos de carbono, nitrogênio e outros elementos podem ser reutilizados muitas vezes nos ecossistemas. A energia, porém, entra principalmente como radiação solar, é transformada pelos produtores e, a cada transferência, parte é dissipada como calor devido ao metabolismo.</p>
      <div class="visual-box"><strong class="card-title">Por que a pirâmide de energia nunca fica invertida?</strong><svg class="lesson-visual" viewBox="0 0 760 300" role="img" aria-label="Pirâmide de energia com produtores na base e consumidores em níveis superiores, mostrando diminuição da energia disponível."><polygon points="120,260 640,260 560,190 200,190" fill="#c9e7cb"/><polygon points="200,185 560,185 500,120 260,120" fill="#f4df9d"/><polygon points="260,115 500,115 450,55 310,55" fill="#f2b1a9"/><text x="380" y="235" text-anchor="middle" font-size="18" font-weight="900">Produtores • maior energia disponível</text><text x="380" y="158" text-anchor="middle" font-size="17" font-weight="900">Consumidores primários</text><text x="380" y="91" text-anchor="middle" font-size="16" font-weight="900">Consumidores superiores</text></svg><p class="visual-caption">Os tamanhos são ilustrativos; a fração transferida varia entre ecossistemas e níveis tróficos.</p></div>
      ${q('C','Energia nos níveis tróficos','Por que níveis tróficos superiores geralmente têm menos energia disponível?',[['a','Porque energia é criada apenas nos consumidores'],['b','Porque parte da energia é usada no metabolismo e dissipada como calor em cada nível'],['c','Porque a matéria deixa de existir']],'b','Correto. A transferência de energia entre níveis não é 100% eficiente.','Separe matéria de energia: a matéria é reciclada; parte da energia é dissipada em cada transformação.')}
    </section>

    <section>
      <h3>5. Populações mudam porque recursos, interações e condições mudam</h3>
      <p><strong>Densidade populacional</strong> relaciona o número de indivíduos à área ou ao volume considerado. Ela pode aumentar por nascimentos e imigração e diminuir por mortes e emigração. Recursos limitados e interações como competição, predação, parasitismo e cooperação também influenciam a dinâmica.</p>
      <div class="two-col"><div class="example-box"><strong class="card-title">Competição</strong><p>Ocorre quando organismos utilizam recursos limitados semelhantes. Pode acontecer dentro da mesma espécie ou entre espécies diferentes.</p></div><div class="example-box"><strong class="card-title">Cooperação e mutualismos</strong><p>Algumas interações produzem benefícios para os envolvidos, mas não significam ausência de competição em outros contextos.</p></div></div>
      <p>No caso dos quatis, restos de alimento podem alterar a distribuição dos indivíduos, mas a conclusão precisa ser testada com dados de abundância, dieta, saúde, comportamento e condições ambientais.</p>
    </section>

    <section>
      <h3>6. Ecossistemas mudam no tempo: sucessão ecológica</h3>
      <p>Após uma perturbação — natural ou causada por atividade humana — a composição de espécies pode mudar ao longo do tempo. Esse processo é chamado <strong>sucessão ecológica</strong>. Não é uma escada obrigatória rumo a um estado “perfeito”: trajetórias reais dependem de clima, solo, dispersão, intensidade da perturbação e novas interferências.</p>
      <div class="concept-flow"><div><strong>Perturbação</strong><span>incêndio, abandono, deslizamento...</span></div><div class="flow-arrow">→</div><div><strong>Colonização</strong><span>espécies chegam e modificam condições</span></div><div class="flow-arrow">→</div><div><strong>Mudança da comunidade</strong><span>composição varia no tempo</span></div></div>
    </section>

    <section>
      <h3>7. Biomas brasileiros mostram como clima, solo e história moldam comunidades</h3>
      <p>Amazônia, Cerrado, Caatinga, Mata Atlântica, Pantanal e Pampa apresentam combinações diferentes de clima, vegetação, disponibilidade de água, solos e história ecológica. Não é necessário decorar uma lista de espécies para compreender o princípio: <strong>condições ambientais selecionam quais estratégias de vida conseguem persistir</strong>.</p>
      <div class="three-col"><div class="example-box"><strong class="card-title">Cerrado</strong><p>Sazonalidade de chuvas e fogo influenciam fortemente a vegetação e as adaptações.</p></div><div class="example-box"><strong class="card-title">Caatinga</strong><p>Longos períodos secos favorecem estratégias de economia de água e perda de folhas.</p></div><div class="example-box"><strong class="card-title">Pantanal</strong><p>O pulso de inundação reorganiza disponibilidade de hábitats e recursos ao longo do ano.</p></div></div>
    </section>

    <section>
      <h3>8. Impacto ambiental não se resolve com uma única ação</h3>
      <p>Desmatamento, fragmentação, resíduos, espécies invasoras, caça, poluição e mudanças climáticas podem alterar ecossistemas por mecanismos diferentes. Soluções precisam atacar o mecanismo: restauração, corredores ecológicos, saneamento, redução de resíduos, manejo, fiscalização, educação ambiental, agroecologia ou sistemas agroflorestais podem ser adequados em situações diferentes.</p>
      <div class="interactive-lab" id="bio01Investigator"><div class="lab-heading"><h4>Investigador de ecossistemas</h4></div><div class="choice-row"><button type="button" data-case="food">Alimento humano para fauna</button><button type="button" data-case="forest">Fragmentação de mata</button><button type="button" data-case="stream">Resíduos em córrego</button></div><div id="bio01Result" class="lab-result"><strong>Escolha uma situação.</strong><span>A análise aparecerá aqui.</span></div></div>
    </section>

    <section class="chapter-checkpoint">
      <span class="lesson-kicker">Checkpoint</span><h3>9. Você consegue pensar como ecólogo?</h3>
      ${q('1','Ecossistema','Qual definição é mais completa?',[['a','Conjunto apenas de animais'],['b','Seres vivos e fatores abióticos em interação numa área'],['c','Qualquer lugar sem seres vivos']],'b','Correto. Ecossistema integra componentes bióticos e abióticos.','Inclua organismos e ambiente físico.')}
      ${q('2','Nicho','Nicho ecológico descreve principalmente:',[['a','somente o endereço da espécie'],['b','o modo de vida, recursos e interações da espécie'],['c','apenas seu tamanho corporal']],'b','Correto. Hábitat é mais próximo do “onde”; nicho envolve “como vive e interage”.','Não reduza nicho ao local onde o organismo é encontrado.')}
      ${q('3','Teia alimentar','Por que uma teia é mais realista que uma cadeia isolada?',[['a','Porque organismos costumam participar de várias relações alimentares'],['b','Porque elimina decompositores'],['c','Porque toda espécie come todas as outras']],'a','Isso. Redes alimentares possuem múltiplos caminhos.','Ecossistemas não funcionam como uma fila única de alimentação.')}
      ${q('4','Energia','Qual afirmação é correta?',[['a','Matéria e energia reciclam do mesmo modo'],['b','A matéria circula; a energia flui e parte é dissipada'],['c','Energia aumenta espontaneamente em cada nível']],'b','Correto. Essa distinção será fundamental no metabolismo energético.','Separe ciclos de matéria do fluxo de energia.')}
      ${q('5','População','O que pode aumentar o número de indivíduos de uma população local?',[['a','nascimentos e imigração'],['b','mortes e emigração'],['c','apenas aumento da temperatura']],'a','Correto. Populações variam por entradas e saídas de indivíduos.','Pense em nascimentos, mortes, imigração e emigração.')}
      ${q('6','Sucessão','Sucessão ecológica significa:',[['a','uma sequência rígida que sempre termina igual'],['b','mudanças na composição da comunidade ao longo do tempo após colonização ou perturbação'],['c','a transformação de uma espécie em outra durante a vida']],'b','Correto. A trajetória depende das condições e da história do local.','Sucessão descreve comunidades, não metamorfose individual.')}
      ${q('7','Biomas','Por que biomas brasileiros possuem comunidades diferentes?',[['a','Porque clima, solo, água, fogo e história ecológica diferem'],['b','Porque cada bioma usa leis biológicas diferentes'],['c','Apenas porque recebem nomes diferentes']],'a','Correto. Condições e história ambiental moldam as comunidades.','Os nomes descrevem diferenças reais de condições e biota.')}
      ${q('8','Investigação','Um parque registra mais quatis perto de lixeiras. Qual conclusão é mais responsável?',[['a','O lixo provou ser a única causa'],['b','Existe uma associação que justifica investigar alimento, comportamento e outras variáveis'],['c','Quatis surgiram espontaneamente das lixeiras']],'b','Perfeito. Observação orienta hipóteses, mas causalidade exige evidências adicionais.','Evite transformar correlação observada em causa única sem teste.')}
      <div class="challenge-box"><strong>Desafio MbB — redesenhe o problema</strong><p>Uma prefeitura pretende eliminar uma espécie considerada “incômoda” num parque. Em até oito linhas, explique <strong>quais dados ecológicos você pediria antes da decisão</strong> e por que retirar uma espécie sem conhecer sua rede de interações pode produzir efeitos inesperados.</p><details><summary>Critério para conferir</summary><p>Uma boa resposta menciona tamanho e tendência populacional, dieta, predadores/presas, competição, papel na dispersão ou decomposição, fatores abióticos, causas do conflito com humanos e alternativas de manejo. Também reconhece que efeitos indiretos dependem da teia ecológica.</p></details></div>
    </section>
    <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT101:</strong> relações alimentares, fluxo de matéria e energia, níveis tróficos, sucessão ecológica, biomas, equilíbrio de ecossistemas e análise de ações humanas e soluções de sustentabilidade.</p></details>`;

  const cases={food:['Alimento humano para fauna','A oferta artificial pode alterar densidade, distribuição, dieta e comportamento. É preciso medir essas mudanças e reduzir a fonte de conflito, não apenas culpar os animais.'],forest:['Fragmentação de mata','A divisão de uma área contínua pode reduzir conectividade, alterar bordas, dificultar deslocamentos e isolar populações. Corredores e restauração podem ser avaliados conforme o contexto.'],stream:['Resíduos em córrego','Resíduos podem alterar qualidade da água, oferta de alimento, oxigênio e organismos presentes. A solução depende de identificar a fonte e impedir a entrada contínua de poluentes.']};
  function init(root){const box=root.querySelector('#bio01Investigator');const result=root.querySelector('#bio01Result');box?.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>{const [t,x]=cases[b.dataset.case];result.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Ecologia e energia',technical:'Ecossistemas • relações, níveis tróficos, sucessão e biomas',title:'Por que mexer em uma espécie pode alterar todo o ecossistema?',objective:'<strong>Objetivo:</strong> compreender níveis de organização, fatores bióticos e abióticos, cadeias e teias alimentares, fluxo de energia, dinâmica populacional, sucessão, biomas e impactos ambientais.',html:lessonHtml,init});}
  MBB.enableChapter('01 Ecossistemas',show);
})();
