(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Fechamento da 1ª série</span><div class="hero-box biology-story"><strong class="card-title">Agora Biologia precisa funcionar como um sistema: ambiente, energia, células, organismos, evolução e hereditariedade têm de conversar.</strong><p>Os exercícios começam separando conceitos que costumam ser confundidos e avançam para situações em que você precisa <strong>interpretar evidências, construir mecanismos e reconhecer limites das conclusões</strong>.</p><p><strong>Como usar:</strong> responda antes de voltar aos capítulos. Ao errar, descubra o critério científico que faltou. Nos desafios abertos, escreva sua resposta antes de abrir a orientação.</p><p class="central-question"><strong>Missão final:</strong> passar de <strong>observação → mecanismo → evidência → explicação → decisão</strong>.</p></div></section>

  <section><h3>Nível 1 — Ecologia e energia</h3><p>Reconstrua as relações básicas que sustentam os capítulos 01 e 02.</p>
  ${q('1','Nível de organização','Indivíduos da mesma espécie vivendo na mesma área e período formam:',[['a','população'],['b','comunidade'],['c','biosfera']],'a','Correto. População exige mesma espécie, área e período.','Comunidade reúne populações de espécies diferentes.')}
  ${q('2','Ecossistema','Um ecossistema inclui:',[['a','somente organismos'],['b','organismos e fatores abióticos em interação'],['c','somente solo e água']],'b','Correto. A interação entre componentes vivos e físicos é central.','Não separe ambiente físico da comunidade.')}
  ${q('3','Nicho','Nicho ecológico descreve principalmente:',[['a','o papel, recursos e relações da espécie'],['b','apenas o endereço'],['c','somente a cor do organismo']],'a','Correto. Nicho envolve como a espécie vive e interage.','Hábitat é mais próximo do “onde”.')}
  ${q('4','Teia','Uma teia alimentar é mais realista que uma cadeia isolada porque:',[['a','organismos participam de várias relações alimentares'],['b','não possui produtores'],['c','todos comem todos']],'a','Correto. Ecossistemas possuem múltiplos caminhos de transferência.','A cadeia é um recorte simplificado.')}
  ${q('5','Energia','Ao subir níveis tróficos, a energia disponível tende a:',[['a','diminuir'],['b','aumentar sempre'],['c','ser criada pelos consumidores']],'a','Correto. Parte é usada no metabolismo e dissipada como calor.','Energia não é transferida com 100% de eficiência.')}
  ${q('6','Fotossíntese','O carbono incorporado à glicose vem principalmente de:',[['a','CO₂'],['b','luz'],['c','O₂']],'a','Correto. Luz fornece energia; CO₂ fornece carbono.','Separe matéria de energia.')}
  ${q('7','Respiração','Plantas realizam respiração celular:',[['a','dia e noite'],['b','somente à noite'],['c','nunca']],'a','Correto. Fotossíntese depende de luz; respiração continua.','Os processos podem ocorrer simultaneamente.')}
  ${q('8','Fermentação','Qual afirmação é correta?',[['a','pode sustentar produção limitada de ATP sem respiração aeróbica completa'],['b','produz sempre mais ATP que respiração aeróbica'],['c','só existe em animais']],'a','Correto. Microrganismos também usam fermentação.','Fermentação rende menos ATP que a respiração aeróbica completa.')}
  </section>

  <section><h3>Nível 2 — Ambiente, clima, poluição e ciclos</h3><p>Agora o objetivo é construir cadeias causais em vez de slogans.</p>
  ${q('9','Tempo e clima','Uma onda de frio de dois dias:',[['a','descreve tempo de curto prazo'],['b','refuta sozinha aquecimento global'],['c','define o clima do planeta']],'a','Correto. Clima exige padrões de longo prazo.','Um evento local curto não substitui séries climáticas.')}
  ${q('10','Efeito estufa','O efeito estufa natural:',[['a','é importante para manter a Terra habitável'],['b','foi criado apenas pela indústria'],['c','deve ser completamente eliminado']],'a','Correto. A questão climática é sua intensificação.','Separe fenômeno natural de intensificação antrópica.')}
  ${q('11','Risco','Danos por enchentes dependem de:',[['a','perigo, exposição e vulnerabilidade'],['b','somente da chuva'],['c','somente da população']],'a','Correto. Risco combina fenômeno físico e vulnerabilidade.','Cidades diferentes podem sofrer impactos distintos com chuva semelhante.')}
  ${q('12','Mitigação','Qual é exemplo de mitigação climática?',[['a','reduzir emissões de gases de efeito estufa'],['b','criar rota de evacuação'],['c','instalar sirene']],'a','Correto. Mitigação atua nas causas; os outros exemplos são adaptação/gestão de risco.','Pergunte se a ação reduz a causa ou reduz vulnerabilidade.')}
  ${q('13','Poluição','Risco de um poluente depende de:',[['a','agente + dose/via/tempo de exposição'],['b','apenas do nome'],['c','apenas da aparência']],'a','Correto. Exposição é parte essencial da análise.','Perigo e risco não são sinônimos.')}
  ${q('14','Saneamento','Saneamento reduz risco principalmente porque:',[['a','interrompe rotas de contaminação e exposição'],['b','elimina todos os microrganismos'],['c','substitui toda prevenção individual']],'a','Correto. Atua coletivamente antes do contato.','A prevenção ambiental não elimina todos os riscos.')}
  ${q('15','Nitrogênio','Microrganismos são importantes no ciclo do N porque:',[['a','transformam diferentes formas nitrogenadas'],['b','criam átomos de N'],['c','todo microrganismo fixa N₂']],'a','Correto. Diferentes grupos realizam etapas diferentes.','Eles transformam matéria; não criam o elemento.')}
  ${q('16','Eutrofização','Qual cadeia é mais adequada?',[['a','nutrientes ↑ → biomassa ↑ → decomposição ↑ → O₂ pode ↓'],['b','fertilizante → O₂ vira N₂'],['c','água verde → veneno obrigatório']],'a','Correto. Eutrofização envolve uma cascata ecológica.','Aparência não revela sozinha toxicidade ou mecanismo.')}
  </section>

  <section><h3>Nível 3 — Origem da vida e evolução</h3><p>Aqui, rigor significa não transformar hipótese em certeza nem evolução em intenção.</p>
  ${q('17','Hipótese','Uma hipótese científica deve ser:',[['a','testável'],['b','impossível de confrontar com evidências'],['c','uma certeza final']],'a','Correto. Testabilidade é parte do método científico.','Provisório não significa arbitrário.')}
  ${q('18','Teoria','Teoria científica é:',[['a','estrutura explicativa sustentada por evidências'],['b','sinônimo de palpite'],['c','ideia que não pode mais ser testada']],'a','Correto. Teorias integram muitas evidências.','O uso científico de “teoria” é diferente do cotidiano.')}
  ${q('19','Pasteur','Os frascos de pescoço de cisne mostraram que:',[['a','crescimento microbiano dependia de contaminação nas condições testadas'],['b','a primeira vida nunca poderia surgir'],['c','aminoácidos eram células']],'a','Correto. A conclusão deve permanecer dentro do experimento.','Pasteur não simulou a Terra prebiótica.')}
  ${q('20','Miller-Urey','O experimento demonstrou:',[['a','síntese abiótica de moléculas orgânicas em certas condições'],['b','criação de uma célula viva'],['c','a composição exata da atmosfera primitiva']],'a','Correto. Foi um teste de química prebiótica.','Não transforme moléculas orgânicas em vida pronta.')}
  ${q('21','Evolução','Quem evolui geneticamente ao longo das gerações?',[['a','populações'],['b','um indivíduo porque precisa'],['c','somente fósseis']],'a','Correto. Frequências de variantes mudam em populações.','Indivíduos desenvolvem-se; populações evoluem.')}
  ${q('22','Seleção natural','Qual condição é necessária?',[['a','variação herdável + sucesso reprodutivo diferencial'],['b','intenção de adaptar-se'],['c','mutação dirigida pela necessidade']],'a','Correto. Seleção não prevê nem deseja resultados.','O ambiente seleciona efeitos de variantes; não comanda mutações específicas.')}
  ${q('23','Filogenia','Árvore filogenética representa:',[['a','hipótese de relações por ancestralidade comum'],['b','escala de superioridade'],['c','fila com humanos no topo']],'a','Correto. A proximidade é lida pela recência do ancestral comum.','Não confunda parentesco com progresso.')}
  ${q('24','Endossimbiose','Qual evidência apoia origem bacteriana de mitocôndrias?',[['a','DNA próprio e divisão semelhante à fissão'],['b','ausência de membrana'],['c','serem bactérias independentes atuais']],'a','Correto. Diversas características convergem para essa origem.','Organelas atuais são fortemente integradas à célula.')}
  </section>

  <section><h3>Nível 4 — Células e fisiologia</h3><p>Use estrutura para explicar função.</p>
  ${q('25','Célula','Qual estrutura é universal?',[['a','membrana plasmática'],['b','núcleo'],['c','cloroplasto']],'a','Correto. Procariontes também possuem membrana.','Núcleo e cloroplasto não são universais.')}
  ${q('26','Procarionte','Bactéria possui:',[['a','DNA sem núcleo membranoso'],['b','mitocôndrias'],['c','núcleo típico eucariótico']],'a','Correto. O DNA fica na região do nucleoide.','Procariontes não têm núcleo membranoso.')}
  ${q('27','Difusão','Difusão simples ocorre:',[['a','a favor de gradiente sem gasto direto de ATP'],['b','sempre contra gradiente'],['c','somente com bombas']],'a','Correto. O gradiente dirige o movimento líquido.','Bombas estão ligadas ao transporte ativo.')}
  ${q('28','Osmose','Célula animal em meio hipertônico tende a:',[['a','perder água'],['b','ganhar parede celular'],['c','produzir cloroplasto']],'a','Correto. A água tende a sair da célula.','Analise a diferença osmótica entre meio e citoplasma.')}
  ${q('29','Bactérias','Qual afirmação é correta?',[['a','todas causam doenças'],['b','participam de ciclos, microbiotas, alimentos e também podem ser patogênicas'],['c','são vírus']],'b','Correto. Bactérias são metabolicamente e ecologicamente diversas.','Patogenicidade é apenas uma parte do grupo.')}
  ${q('30','Fungos','Fungos são:',[['a','eucariontes heterótrofos por absorção'],['b','plantas sem clorofila'],['c','procariontes']],'a','Correto. Formam linhagem distinta das plantas.','Não classifique por aparência superficial.')}
  ${q('31','Troca gasosa','Brânquias, traqueias e pulmões resolvem principalmente:',[['a','trocas gasosas em contextos diferentes'],['b','fotossíntese'],['c','hereditariedade']],'a','Correto. São soluções distintas para obter/eliminar gases.','Compare função comum e estruturas diferentes.')}
  ${q('32','Integração','Durante exercício, respiração e circulação se relacionam porque:',[['a','trocas gasosas fornecem O₂ e circulação o distribui aos tecidos'],['b','o coração produz O₂'],['c','pulmões digerem glicose']],'a','Correto. Sistemas trabalham integrados.','Separe produção de ATP, troca gasosa e transporte.')}
  </section>

  <section><h3>Nível 5 — Genética e hereditariedade</h3><p>Use probabilidade sem transformar genes em destino.</p>
  ${q('33','Alelo','Alelo é:',[['a','uma versão de um gene'],['b','um órgão'],['c','um organismo']],'a','Correto. Alelos são variantes de um locus.','Gene e alelo não são sinônimos perfeitos.')}
  ${q('34','Segregação','Um indivíduo Aa forma gametas:',[['a','A ou a'],['b','Aa'],['c','AA e aa']],'a','Correto. Os alelos segregam.','Gametas recebem uma cópia do locus no modelo diploide.')}
  ${q('35','Probabilidade','Em Aa × Aa, P(aa) é:',[['a','1/4'],['b','1/2'],['c','3/4']],'a','Correto. 1/2 × 1/2 = 1/4.','Cada genitor precisa fornecer a.')}
  ${q('36','Dominância','Dominante significa:',[['a','fenótipo expresso no heterozigoto no modelo considerado'],['b','mais comum'],['c','mais adaptativo']],'a','Correto. Dominância não mede frequência nem valor adaptativo.','É uma relação fenotípica entre alelos.')}
  ${q('37','2ª Lei','Assortimento independente possui limite porque:',[['a','genes ligados podem não segregar independentemente'],['b','meiose não existe'],['c','todo gene está em cromossomo diferente']],'a','Correto. Posição cromossômica importa.','A independência é uma condição, não regra absoluta.')}
  ${q('38','ABO','Genótipo do fenótipo AB é:',[['a','IᴬIᴮ'],['b','ii'],['c','Iᴬi']],'a','Correto. Iᴬ e Iᴮ são codominantes.','AB exige os dois alelos.')}
  ${q('39','Transfusão','Por que compatibilidade clínica exige mais que ABO/Rh escolar?',[['a','há outros antígenos e testes de compatibilidade'],['b','grupos sanguíneos são fictícios'],['c','o tipo muda depois da refeição']],'a','Correto. Protocolos clínicos usam testes específicos.','Modelos escolares são introdutórios.')}
  ${q('40','Fenótipo complexo','Altura humana é:',[['a','poligênica e influenciada pelo ambiente'],['b','um único alelo dominante universal'],['c','sem influência genética']],'a','Correto. Muitas características humanas são multifatoriais.','Mendel não explica sozinho toda variação humana.')}
  </section>

  <section><h3>Nível 6 — Desafios integradores</h3><p>Agora não há alternativa: construa a explicação.</p>
  <div class="challenge-box"><strong>41. Parque urbano</strong><p>Uma população de quatis cresce perto de lixeiras. Proponha uma investigação que diferencie correlação de causalidade e indique medidas de manejo sem simplesmente retirar os animais.</p><details><summary>Raciocínio esperado</summary><p>Medir abundância, dieta, disponibilidade de alimento natural/artificial, saúde, reprodução, deslocamento e comparação com áreas sem lixo; controlar a fonte de alimento e monitorar resposta.</p></details></div>
  <div class="challenge-box"><strong>42. Estufa</strong><p>Explique por que CO₂ pode cair durante o dia e subir à noite, conectando fotossíntese, respiração e saldo de processos.</p><details><summary>Raciocínio esperado</summary><p>Plantas respiram continuamente; com luz, fotossíntese pode consumir CO₂ mais rápido que a respiração o libera. No escuro, fotossíntese cessa e permanece a liberação respiratória.</p></details></div>
  <div class="challenge-box"><strong>43. Lagoa eutrofizada</strong><p>Construa a cadeia causal de excesso de nutrientes até possível mortalidade de peixes e proponha duas intervenções na fonte.</p><details><summary>Raciocínio esperado</summary><p>Nutrientes → produção de biomassa → morte/decomposição → consumo de O₂ → hipóxia. Intervenções: saneamento, manejo de fertilizantes, faixas vegetadas, redução do escoamento.</p></details></div>
  <div class="challenge-box"><strong>44. Resistência</strong><p>Explique resistência bacteriana sem usar “as bactérias quiseram se adaptar”.</p><details><summary>Raciocínio esperado</summary><p>Variação herdável + antibiótico como pressão seletiva + sobrevivência/reprodução diferencial + aumento da frequência de resistência.</p></details></div>
  <div class="challenge-box"><strong>45. Corpo integrado</strong><p>Durante corrida, conecte respiração, circulação, metabolismo celular e homeostase.</p><details><summary>Raciocínio esperado</summary><p>Ventilação/troca aumentam oferta de O₂; circulação distribui O₂ e combustíveis; células produzem ATP e CO₂/calor; sistemas regulatórios ajustam água, sais, temperatura e resíduos.</p></details></div>
  <div class="challenge-box"><strong>46. Herança sem determinismo</strong><p>Explique por que dois irmãos podem diferir mesmo com os mesmos pais, usando meiose, fecundação, recombinação e ambiente.</p><details><summary>Raciocínio esperado</summary><p>Gametas carregam combinações distintas; segregação/recombinação e fecundação probabilística geram genótipos diferentes; muitos fenótipos ainda dependem de ambiente e desenvolvimento.</p></details></div>
  </section>

  <section><h3>Mapa final de revisão</h3><div class="table-wrap"><table><thead><tr><th>Se você errou principalmente...</th><th>Revise</th><th>Pergunta para reconstruir</th></tr></thead><tbody><tr><td>teias, energia, populações</td><td>01</td><td>Quem interage e para onde matéria/energia vão?</td></tr><tr><td>fotossíntese, respiração, ATP</td><td>02</td><td>Qual matéria entra/sai e como a energia é transformada?</td></tr><tr><td>clima, risco, energia</td><td>03</td><td>Qual escala de tempo e qual mecanismo estão sendo analisados?</td></tr><tr><td>poluição, saneamento, saúde</td><td>04</td><td>Qual é a fonte, a via de exposição e o controle?</td></tr><tr><td>ciclos e eutrofização</td><td>05</td><td>Qual elemento está sendo transferido e por qual processo?</td></tr><tr><td>origem da vida</td><td>06</td><td>O que foi realmente testado e o que continua hipótese?</td></tr><tr><td>seleção e filogenia</td><td>07</td><td>Qual mecanismo muda populações e qual ancestral é compartilhado?</td></tr><tr><td>células, bactérias, fungos</td><td>08</td><td>Como a estrutura permite troca, metabolismo e informação?</td></tr><tr><td>fisiologia</td><td>09</td><td>Que problema comum diferentes organismos precisam resolver?</td></tr><tr><td>Mendel, ABO/Rh</td><td>10</td><td>Quais alelos segregam e qual probabilidade está sendo calculada?</td></tr></tbody></table></div><div class="ok-box"><strong>Fechamento da 1ª série</strong><p>Se você consegue justificar respostas usando mecanismos, evidências, probabilidades e limites, Biologia deixou de ser uma lista de nomes e passou a funcionar como <strong>explicação de sistemas vivos</strong>.</p></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p>Revisão cumulativa das habilidades trabalhadas na 1ª série: ecologia, metabolismo, clima, poluição e saúde, ciclos, origem da vida, evolução, células, fisiologia e genética.</p></details>`;
  function show(){MBB.showLesson({unit:'Prática',technical:'Revisão cumulativa • mecanismos, evidências, integração e aplicação',title:'Você consegue usar a Biologia para explicar sistemas vivos?',objective:'<strong>Objetivo:</strong> consolidar os capítulos 01 a 10 por meio de 40 questões objetivas e 6 desafios integradores, identificando o que já foi compreendido e o que precisa ser revisado.',html:lessonHtml});}
  MBB.enableChapter('99 Exercícios e desafios',show);
})();
