(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Uma estufa de tomates possui sensores de luz, temperatura e CO₂. Durante o dia, com iluminação intensa, a concentração de CO₂ do ar interno tende a cair. À noite, sem iluminação, o sensor registra aumento de CO₂ mesmo com as plantas aparentemente “paradas”.</strong><p>Um aluno conclui: “de dia a planta faz fotossíntese; à noite ela troca e começa a respirar”. Essa frase parece razoável, mas esconde um erro importante: <strong>plantas respiram celularmente dia e noite</strong>. A fotossíntese depende de luz; a respiração celular não é um “modo noturno”.</p>${q('A','Faça uma hipótese','Qual explicação inicial combina melhor com os dados da estufa?',[['a','À noite as plantas deixam de ter metabolismo'],['b','De dia, fotossíntese e respiração ocorrem; com luz suficiente, o consumo de CO₂ pela fotossíntese pode superar a liberação pela respiração'],['c','Plantas produzem CO₂ apenas quando estão doentes']],'b','Correto. Os dois processos podem ocorrer simultaneamente; o saldo observado depende das taxas relativas.','Não trate fotossíntese e respiração como turnos exclusivos.')}
  <p class="central-question"><strong>Nossa missão:</strong> acompanhar <strong>matéria e energia</strong> do Sol até as moléculas orgânicas e entender como células extraem energia utilizável para manter a vida.</p></div></section>

  <section><h3>1. Vida exige energia para manter organização, transporte, síntese e movimento</h3><p>Células realizam trabalho constantemente: transportam substâncias, sintetizam moléculas, mantêm gradientes, reparam estruturas e, em muitos organismos, produzem movimento. Para isso, precisam transformar energia de uma forma em outra.</p><p>O <strong>ATP</strong> funciona como uma das principais moléculas intermediárias de transferência de energia nas células. Ele não é um “estoque infinito”: é produzido e consumido continuamente.</p><div class="concept-flow"><div><strong>Fonte de energia</strong><span>luz ou moléculas orgânicas</span></div><div class="flow-arrow">→</div><div><strong>Transformações celulares</strong><span>produção de ATP</span></div><div class="flow-arrow">→</div><div><strong>Trabalho celular</strong><span>síntese • transporte • movimento</span></div></div></section>

  <section><h3>2. Fotossíntese transforma energia luminosa em energia química</h3><p>Em plantas, algas e alguns microrganismos, a fotossíntese utiliza energia luminosa para produzir matéria orgânica a partir de substâncias inorgânicas. Numa representação global simplificada:</p><div class="formula-box"><span class="formula-name">Representação global da fotossíntese</span><div class="big-formula">6 CO₂ + 6 H₂O + luz → C₆H₁₂O₆ + 6 O₂</div><p>Essa equação resume muitas etapas. Ela não significa que uma molécula de glicose “surge de uma vez” em uma única reação.</p></div><p>O carbono do CO₂ passa a integrar moléculas orgânicas. A energia luminosa é convertida em energia química associada às ligações dessas moléculas.</p><div class="note-box"><strong>De onde vem o oxigênio liberado?</strong><p>O O₂ liberado na fotossíntese provém da água nas reações fotoquímicas. A equação global, sozinha, não mostra o caminho de cada átomo.</p></div></section>

  <section><h3>3. Respiração celular libera energia utilizável a partir de moléculas orgânicas</h3><p>Na respiração celular aeróbica, moléculas orgânicas são oxidadas e o oxigênio participa como aceptor final de elétrons em etapas que permitem grande produção de ATP. Uma representação global simplificada é:</p><div class="formula-box"><span class="formula-name">Representação global da respiração aeróbica</span><div class="big-formula">C₆H₁₂O₆ + 6 O₂ → 6 CO₂ + 6 H₂O + energia</div><p>A energia não aparece toda como ATP: parte é transferida para ATP e parte é dissipada como calor.</p></div><p>Animais, plantas, fungos e muitos microrganismos realizam respiração celular. Em eucariontes, várias etapas estão associadas às mitocôndrias; a glicólise ocorre no citosol.</p>${q('B','Plantas respiram?','Uma folha iluminada pode realizar fotossíntese e respiração celular ao mesmo tempo?',[['a','Sim'],['b','Não, são processos incompatíveis'],['c','Só se a planta não tiver clorofila']],'a','Correto. Os processos são diferentes e podem ocorrer simultaneamente.','A fotossíntese depende de luz; a respiração celular continua ocorrendo.')}</section>

  <section><h3>4. Fotossíntese e respiração estão conectadas, mas não são simplesmente “reações inversas”</h3><p>As equações globais parecem espelhadas, porém os mecanismos celulares, enzimas e etapas intermediárias são distintos. O que podemos comparar com segurança é o balanço geral de matéria e energia.</p><div class="table-wrap"><table><thead><tr><th>Aspecto</th><th>Fotossíntese</th><th>Respiração aeróbica</th></tr></thead><tbody><tr><td>Papel energético</td><td>Armazena energia química em matéria orgânica</td><td>Transfere parte da energia da matéria orgânica para ATP</td></tr><tr><td>Carbono</td><td>CO₂ é incorporado em moléculas orgânicas</td><td>carbono orgânico pode retornar como CO₂</td></tr><tr><td>O₂</td><td>pode ser liberado</td><td>é consumido na via aeróbica</td></tr><tr><td>Onde ocorre em eucariontes</td><td>cloroplastos</td><td>glicólise no citosol e etapas nas mitocôndrias</td></tr></tbody></table></div></section>

  <section><h3>5. O saldo de gases depende das taxas dos processos</h3><p>Em uma planta iluminada, se a taxa de fotossíntese supera a taxa de respiração, o saldo pode ser de consumo de CO₂ e liberação de O₂. No escuro, a fotossíntese para, mas a respiração continua; o saldo passa a refletir apenas os processos que permanecem ativos.</p><div class="visual-box"><strong class="card-title">Saldo não é o mesmo que processo inexistente</strong><svg class="lesson-visual" viewBox="0 0 760 280" role="img" aria-label="Diagrama comparando planta iluminada e planta no escuro, com fotossíntese e respiração ocorrendo durante o dia e apenas respiração no escuro."><rect x="35" y="45" width="315" height="190" rx="18" fill="#f1fae9" stroke="#acd08c"/><text x="192" y="82" text-anchor="middle" font-size="20" font-weight="900">Com luz</text><text x="192" y="120" text-anchor="middle" font-size="16">fotossíntese + respiração</text><text x="192" y="155" text-anchor="middle" font-size="14">saldo possível:</text><text x="192" y="181" text-anchor="middle" font-size="17" font-weight="900" fill="#2f7d32">CO₂ ↓ • O₂ ↑</text><rect x="410" y="45" width="315" height="190" rx="18" fill="#f5f5f8" stroke="#c7c7d2"/><text x="567" y="82" text-anchor="middle" font-size="20" font-weight="900">No escuro</text><text x="567" y="120" text-anchor="middle" font-size="16">respiração continua</text><text x="567" y="155" text-anchor="middle" font-size="14">saldo esperado:</text><text x="567" y="181" text-anchor="middle" font-size="17" font-weight="900">CO₂ ↑ • O₂ ↓</text></svg></div></section>

  <section><h3>6. Matéria circula entre organismos; energia precisa entrar continuamente</h3><p>O carbono fixado por produtores pode passar a herbívoros, predadores, decompositores e retornar ao ambiente. A energia solar capturada não “dá a volta”: após sucessivas transformações, grande parte termina dissipada como calor. Por isso ecossistemas dependem de entrada contínua de energia.</p><div class="ok-box"><strong>Conexão com o Capítulo 01</strong><p>Agora podemos explicar por que pirâmides de energia diminuem nos níveis tróficos: cada organismo usa energia em seu próprio metabolismo antes que parte da matéria seja transferida adiante.</p></div></section>

  <section><h3>7. Nem toda obtenção de energia celular usa oxigênio da mesma forma</h3><p>Algumas células e microrganismos podem obter ATP por vias sem uso de O₂ como aceptor final. Na <strong>fermentação</strong>, a produção de ATP é muito menor que na respiração aeróbica completa, mas permite regenerar moléculas necessárias para manter a glicólise.</p><div class="two-col"><div class="example-box"><strong class="card-title">Fermentação lática</strong><p>Pode ocorrer em células musculares sob certas condições e em microrganismos usados na produção de alimentos fermentados.</p></div><div class="example-box"><strong class="card-title">Fermentação alcoólica</strong><p>Leveduras podem produzir etanol e CO₂, processo explorado em panificação e em biocombustíveis.</p></div></div><div class="note-box"><strong>Cuidado com a linguagem</strong><p>Dizer que “o músculo fica sem oxigênio e vira fermentação” é simplificação excessiva. Metabolismo muscular envolve oferta de O₂, intensidade, duração e múltiplas vias energéticas.</p></div></section>

  <section><h3>8. Biomassa e biocombustíveis conectam metabolismo e tecnologia</h3><p>Biomassa é matéria orgânica de origem recente que pode ser usada como fonte de energia ou matéria-prima. Etanol de cana-de-açúcar, biogás e biodiesel são exemplos de rotas que aproveitam matéria biológica.</p><p>Chamarmos uma fonte de “renovável” não significa impacto zero. É preciso analisar uso do solo, água, fertilizantes, transporte, emissões, eficiência e competição com outros usos da terra.</p><div class="three-col"><div class="example-box"><strong class="card-title">Biomassa</strong><p>armazena energia química originalmente capturada em processos biológicos</p></div><div class="example-box"><strong class="card-title">Conversão</strong><p>combustão, fermentação, digestão anaeróbia ou outras tecnologias</p></div><div class="example-box"><strong class="card-title">Decisão</strong><p>considerar balanço ambiental e social, não apenas a palavra “bio”</p></div></div></section>

  <section><h3>9. Investigador metabólico</h3><div class="interactive-lab" id="bio02Lab"><div class="lab-heading"><h4>Qual processo explica melhor o dado?</h4></div><div class="choice-row"><button type="button" data-case="dark">Planta no escuro libera CO₂</button><button type="button" data-case="bread">Massa de pão forma bolhas</button><button type="button" data-case="forest">Floresta acumula biomassa</button></div><div class="lab-result" id="bio02Result"><strong>Escolha uma situação.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>10. Você consegue acompanhar matéria e energia?</h3>
  ${q('1','ATP','Qual é uma função geral do ATP?',[['a','servir como intermediário de transferência de energia celular'],['b','ser o único nutriente usado por humanos'],['c','substituir todas as enzimas']],'a','Correto. ATP conecta processos que liberam energia a processos que exigem energia.','ATP não substitui nutrientes nem enzimas.')}
  ${q('2','Fotossíntese','O carbono da glicose produzida por uma planta vem principalmente de:',[['a','CO₂'],['b','luz'],['c','O₂ atmosférico']],'a','Correto. O CO₂ fornece o carbono incorporado à matéria orgânica.','Luz fornece energia, não átomos de carbono.')}
  ${q('3','Respiração','Qual organismo pode realizar respiração celular?',[['a','apenas animais'],['b','animais, plantas, fungos e muitos microrganismos'],['c','apenas seres sem cloroplastos']],'b','Correto. Respiração celular não é exclusividade de animais.','Plantas também precisam produzir ATP para o trabalho celular.')}
  ${q('4','Equações globais','Por que fotossíntese e respiração não devem ser tratadas como uma única reação reversível simples?',[['a','porque envolvem vias, enzimas e compartimentos distintos'],['b','porque usam elementos químicos diferentes'],['c','porque nenhuma delas transforma energia']],'a','Correto. A semelhança das equações globais não significa mecanismo idêntico ao contrário.','Compare mecanismos, não apenas os termos das equações.')}
  ${q('5','Saldo no escuro','O que acontece com a fotossíntese de uma planta no escuro?',[['a','continua igual'],['b','cessa por falta de luz, enquanto a respiração pode continuar'],['c','vira respiração automaticamente']],'b','Correto. São processos diferentes.','A respiração não é uma “fotossíntese invertida”.')}
  ${q('6','Energia no ecossistema','Por que ecossistemas precisam de entrada contínua de energia?',[['a','porque energia é parcialmente dissipada como calor nas transformações'],['b','porque átomos desaparecem'],['c','porque decompositores destroem energia']],'a','Isso. Matéria pode circular; energia útil não é reciclada integralmente.','A dissipação energética é inevitável nas transformações.')}
  ${q('7','Fermentação','Qual afirmação é correta?',[['a','fermentação pode manter produção limitada de ATP sem respiração aeróbica completa'],['b','fermentação produz mais ATP que respiração aeróbica'],['c','fermentação só existe em animais']],'a','Correto. Ela permite manter a glicólise em determinadas condições.','Fermentação ocorre também em microrganismos e rende menos ATP.')}
  ${q('8','Biocombustível','Por que “renovável” não significa impacto zero?',[['a','porque produção exige recursos e pode gerar impactos no uso do solo, água e emissões'],['b','porque todo biocombustível é fóssil'],['c','porque energia renovável não usa matéria']],'a','Correto. Avaliação ambiental precisa considerar o ciclo produtivo completo.','Evite transformar uma categoria em selo automático de sustentabilidade.')}
  <div class="challenge-box"><strong>Desafio MbB — explique o sensor</strong><p>Explique em até oito linhas por que o CO₂ de uma estufa pode diminuir durante um dia ensolarado e aumentar à noite, deixando claro que plantas respiram o tempo todo e que o valor medido é um <strong>saldo</strong> entre processos.</p><details><summary>Critério para conferir</summary><p>A resposta deve distinguir fotossíntese e respiração, mencionar dependência da luz, consumo/liberação de CO₂ e explicar que medir o saldo não significa que um dos processos esteja necessariamente ausente.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT101:</strong> fotossíntese, respiração celular, situações cotidianas relacionadas ao metabolismo, comparação entre processos e relação entre energia, biomassa, biocombustíveis e sustentabilidade.</p></details>`;
  const cases={dark:['Respiração celular','No escuro, a fotossíntese cessa, mas a respiração celular continua e pode liberar CO₂.'],bread:['Fermentação alcoólica','Leveduras metabolizam açúcares; o CO₂ produzido forma bolhas que ajudam a massa a crescer.'],forest:['Fotossíntese + balanço de carbono','Quando a produção de matéria orgânica supera perdas por respiração, consumo e decomposição, parte do carbono pode permanecer acumulada na biomassa.']};
  function init(root){const r=root.querySelector('#bio02Result');root.querySelectorAll('#bio02Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Ecologia e energia',technical:'Metabolismo energético • fotossíntese, respiração, ATP e biomassa',title:'De onde vem a energia que mantém um ecossistema funcionando?',objective:'<strong>Objetivo:</strong> compreender fotossíntese, respiração celular e fermentação como transformações de matéria e energia e relacioná-las ao fluxo energético nos ecossistemas e ao uso de biomassa.',html:lessonHtml,init});}
  MBB.enableChapter('02 Metabolismo energético',show);
})();
