(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Um peixe retira oxigênio dissolvido da água com brânquias. Um inseto usa um sistema de traqueias. Um ser humano usa pulmões e sangue para distribuir gases. Se todos precisam obter matéria e energia, por que seus corpos usam soluções tão diferentes?</strong><p>A evolução não desenha um “projeto ideal” único. Cada linhagem herda estruturas de ancestrais e as modifica ao longo do tempo. Fisiologia comparada investiga <strong>como organismos diferentes resolvem problemas semelhantes: obter nutrientes, trocar gases, transportar substâncias e reproduzir-se</strong>.</p>${q('A','Compare soluções','O fato de peixe e humano usarem estruturas respiratórias diferentes significa que um deles é biologicamente “mais evoluído”?',[['a','sim, pulmão é sempre superior'],['b','não; cada sistema funciona em contexto evolutivo e ambiental próprio'],['c','sim, organismos aquáticos são menos evoluídos']],'b','Correto. Evolução não forma uma escala universal de superioridade.','Compare função e ambiente, não valor biológico.')}
  <p class="central-question"><strong>Nossa missão:</strong> comparar <strong>digestão, circulação, respiração e reprodução</strong> como soluções evolutivas para necessidades comuns dos organismos.</p></div></section>

  <section><h3>1. Ser multicelular cria um problema de distância</h3><p>Uma célula pequena pode trocar muitas substâncias diretamente com o ambiente. Em organismos multicelulares grandes, várias células ficam longe da superfície externa. Sistemas de transporte e superfícies especializadas reduzem esse problema.</p><div class="concept-flow"><div><strong>Ambiente</strong><span>nutrientes • O₂ • água</span></div><div class="flow-arrow">→</div><div><strong>Superfícies de troca</strong><span>intestino • brânquia • pulmão</span></div><div class="flow-arrow">→</div><div><strong>Transporte interno</strong><span>fluidos e circulação</span></div></div><p>A eficiência de uma superfície de troca costuma aumentar quando há grande área, pequena distância de difusão e manutenção de gradientes.</p></section>

  <section><h3>2. Digestão transforma alimentos em moléculas absorvíveis</h3><p>Digestão envolve processos mecânicos e químicos que reduzem alimentos a moléculas capazes de atravessar superfícies de absorção. Enzimas catalisam reações específicas; não “derretem qualquer alimento”.</p><div class="table-wrap"><table><thead><tr><th>Estratégia</th><th>Exemplo geral</th><th>Ideia</th></tr></thead><tbody><tr><td>Intracelular</td><td>alguns protistas e células especializadas</td><td>partículas são internalizadas e digeridas em compartimentos</td></tr><tr><td>Extracelular em cavidade</td><td>cnidários</td><td>digestão ocorre em cavidade com uma abertura principal</td></tr><tr><td>Tubo digestório completo</td><td>muitos animais</td><td>fluxo unidirecional permite especialização de regiões</td></tr></tbody></table></div><div class="ok-box"><strong>No ser humano</strong><p>Boca, estômago, intestino e órgãos associados atuam de forma integrada. A maior parte da absorção de nutrientes ocorre no intestino delgado, cuja superfície é ampliada por pregas, vilosidades e microvilosidades.</p></div></section>

  <section><h3>3. Circulação distribui materiais e conecta órgãos</h3><p>Animais usam diferentes sistemas circulatórios. Em sistemas <strong>abertos</strong>, o fluido circulatório deixa vasos e banha tecidos em cavidades; em sistemas <strong>fechados</strong>, o sangue permanece em vasos.</p><div class="comparison-grid"><div class="example-box"><strong class="card-title">Circulação aberta</strong><p>encontrada em artrópodes e muitos moluscos; hemolinfa circula por vasos e espaços corporais</p></div><div class="example-box"><strong class="card-title">Circulação fechada</strong><p>encontrada em anelídeos e vertebrados; sangue circula em rede de vasos</p></div></div><p>Entre vertebrados há circuitos diferentes. Peixes possuem circulação simples; aves e mamíferos possuem circulação dupla com separação completa entre sangue oxigenado e pouco oxigenado no coração.</p>${q('B','Circulação','Por que “fechada” não significa automaticamente “melhor” em qualquer contexto?',[['a','porque diferentes sistemas estão associados a histórias evolutivas e demandas metabólicas distintas'],['b','porque sistema fechado não transporta substâncias'],['c','porque todo animal pode trocar de sistema']],'a','Correto. Comparação evolutiva deve considerar função, tamanho, metabolismo e história da linhagem.','Evite transformar diferenças fisiológicas em ranking universal.')}</section>

  <section><h3>4. Trocas gasosas dependem de difusão e superfície adequada</h3><p>O₂ e CO₂ atravessam superfícies respiratórias por difusão, guiada por gradientes de pressão parcial/concentração. Essas superfícies precisam permanecer funcionais no ambiente do organismo.</p><div class="four-col"><div class="example-box"><strong class="card-title">Superfície corporal</strong><p>animais pequenos podem trocar gases diretamente pela pele</p></div><div class="example-box"><strong class="card-title">Brânquias</strong><p>grande área de troca em ambiente aquático</p></div><div class="example-box"><strong class="card-title">Traqueias</strong><p>em insetos, tubos levam ar próximo aos tecidos</p></div><div class="example-box"><strong class="card-title">Pulmões</strong><p>superfície interna protegida contra perda excessiva de água</p></div></div><div class="note-box"><strong>Respirar não é apenas “puxar ar”</strong><p>Ventilação movimenta o meio respiratório. Troca gasosa é difusão através de superfícies. Respiração celular é um processo metabólico dentro das células. Os três conceitos se relacionam, mas não são sinônimos.</p></div></section>

  <section><h3>5. O sistema respiratório humano funciona junto com a circulação</h3><p>Durante a inspiração, mudanças de volume torácico alteram pressões e o ar entra nos pulmões. Nos alvéolos, gases difundem-se entre ar e sangue. Hemoglobina transporta grande parte do O₂; CO₂ é transportado de diferentes formas no sangue.</p><div class="visual-box"><strong class="card-title">Da atmosfera até a célula</strong><svg class="lesson-visual" viewBox="0 0 760 280" role="img" aria-label="Fluxo do oxigênio da atmosfera aos pulmões, sangue e células, com CO2 no sentido contrário."><defs><marker id="bio09a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#2f7d32"/></marker></defs><rect x="35" y="75" width="145" height="110" rx="14" fill="#eef7ff" stroke="#aec9db"/><text x="107" y="120" text-anchor="middle" font-weight="900">Atmosfera</text><rect x="220" y="75" width="145" height="110" rx="14" fill="#f7eceb" stroke="#ddaaa6"/><text x="292" y="120" text-anchor="middle" font-weight="900">Alvéolos</text><rect x="405" y="75" width="145" height="110" rx="14" fill="#fff3f1" stroke="#d99f99"/><text x="477" y="120" text-anchor="middle" font-weight="900">Sangue</text><rect x="590" y="75" width="135" height="110" rx="14" fill="#edf8ee" stroke="#a8cbaa"/><text x="657" y="120" text-anchor="middle" font-weight="900">Células</text><path d="M180 115 H216" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio09a)"/><path d="M365 115 H401" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio09a)"/><path d="M550 115 H586" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio09a)"/><text x="380" y="220" text-anchor="middle" font-size="14">O₂ → tecidos • CO₂ retorna em sentido oposto</text></svg></div></section>

  <section><h3>6. Excreção mantém composição do meio interno</h3><p>Metabolismo produz resíduos e altera concentrações de água e sais. Sistemas excretores ajudam a manter <strong>homeostase</strong>. Nos vertebrados, rins filtram o sangue e ajustam reabsorção e secreção de substâncias, produzindo urina.</p><p>Animais excretam resíduos nitrogenados em formas diferentes. Amônia exige muita água para eliminação; ureia e ácido úrico reduzem toxicidade ou perda de água em graus diferentes, mas têm custos metabólicos distintos.</p></section>

  <section><h3>7. Reprodução pode envolver clonagem genética parcial ou recombinação</h3><p>Na reprodução <strong>assexuada</strong>, um único organismo pode originar descendentes sem fusão de gametas. Na reprodução <strong>sexuada</strong>, meiose e fecundação combinam material genético de dois gametas, aumentando combinações genéticas.</p><div class="two-col"><div class="example-box"><strong class="card-title">Assexuada</strong><p>pode ser rápida e eficiente; descendentes tendem a ser geneticamente muito semelhantes, exceto por mutações</p></div><div class="example-box"><strong class="card-title">Sexuada</strong><p>gera novas combinações de alelos e amplia variabilidade entre descendentes</p></div></div><div class="note-box"><strong>Não existe estratégia universalmente superior</strong><p>Muitos organismos alternam estratégias ou combinam diferentes modos conforme ambiente e história evolutiva.</p></div></section>

  <section><h3>8. Sistemas são integrados, não capítulos independentes do corpo</h3><p>Após uma refeição, digestão disponibiliza moléculas; circulação distribui nutrientes; respiração fornece O₂ para metabolismo aeróbico; excreção remove resíduos e ajusta água/sais. Alterar um sistema repercute em outros.</p><div class="concept-flow"><div><strong>Digestão</strong><span>nutrientes</span></div><div class="flow-arrow">→</div><div><strong>Circulação</strong><span>distribuição</span></div><div class="flow-arrow">↔</div><div><strong>Respiração/excreção</strong><span>trocas e equilíbrio</span></div></div></section>

  <section><h3>9. Investigador comparativo</h3><div class="interactive-lab" id="bio09Lab"><div class="lab-heading"><h4>Qual solução fisiológica aparece?</h4></div><div class="choice-row"><button type="button" data-case="fish">Peixe</button><button type="button" data-case="insect">Inseto</button><button type="button" data-case="human">Humano em exercício</button></div><div class="lab-result" id="bio09Result"><strong>Escolha um caso.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>10. Você consegue comparar sem criar ranking?</h3>
  ${q('1','Multicelularidade','Por que organismos grandes precisam de sistemas internos de transporte?',[['a','porque muitas células ficam longe das superfícies de troca'],['b','porque difusão deixa de existir'],['c','porque apenas animais possuem células']],'a','Correto. Distâncias maiores tornam transporte interno decisivo.','Difusão continua existindo, mas não resolve sozinha grandes distâncias.')}
  ${q('2','Digestão','A principal função da digestão é:',[['a','transformar alimentos em moléculas absorvíveis'],['b','produzir oxigênio'],['c','converter todo alimento diretamente em ATP no intestino']],'a','Correto. Absorção vem depois da quebra e transformação dos nutrientes.','ATP é produzido pelas células por metabolismo, não pelo tubo digestório diretamente.')}
  ${q('3','Circulação','Em sistema fechado:',[['a','o sangue permanece em vasos'],['b','não existe coração'],['c','não há transporte de gases']],'a','Correto. Essa é a característica estrutural central.','Sistemas fechados podem ter diferentes números de câmaras e circuitos.')}
  ${q('4','Brânquias','Por que são adequadas à vida aquática?',[['a','oferecem grande superfície para troca com água'],['b','produzem ar atmosférico'],['c','funcionam apenas fora d’água']],'a','Correto. Estrutura e ambiente estão relacionados.','Brânquias exploram O₂ dissolvido na água.')}
  ${q('5','Respiração','Qual sequência está correta?',[['a','ventilação → troca gasosa → transporte → respiração celular'],['b','respiração celular → formação do pulmão'],['c','digestão → fotossíntese']],'a','Correto. São etapas relacionadas mas distintas.','Não use “respiração” como nome para todos os processos.')}
  ${q('6','Homeostase','Rins contribuem para:',[['a','regular água, sais e remover resíduos metabólicos'],['b','produzir alimentos'],['c','realizar fotossíntese']],'a','Correto. Excreção participa da manutenção do meio interno.','Rins não são apenas “filtros de sujeira”; regulam composição.')}
  ${q('7','Reprodução sexuada','Uma consequência comum é:',[['a','aumento de combinações genéticas nos descendentes'],['b','descendentes sempre idênticos'],['c','ausência de meiose']],'a','Correto. Recombinação e segregação geram novas combinações.','Gametas são produzidos por meiose em muitos ciclos sexuados.')}
  ${q('8','Comparação','Por que não devemos chamar um sistema fisiológico de “mais evoluído” apenas por ser mais complexo?',[['a','porque evolução produz adaptações contextuais, não uma escala única de progresso'],['b','porque complexidade nunca muda'],['c','porque todos os organismos têm os mesmos órgãos']],'a','Correto. Função e ambiente são critérios mais úteis que ranking.','Complexidade não é medida universal de valor evolutivo.')}
  <div class="challenge-box"><strong>Desafio MbB — uma corrida em quatro sistemas</strong><p>Durante exercício físico, explique como <strong>digestão/estoques de nutrientes, respiração, circulação e excreção/homeostase</strong> se relacionam para sustentar células musculares. Não trate os sistemas como independentes.</p><details><summary>Critério para conferir</summary><p>A resposta deve relacionar combustível metabólico, entrada e transporte de O₂, remoção de CO₂, circulação e ajustes de água, sais e resíduos.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT202:</strong> fisiologia comparada de digestão, circulação, respiração, excreção e reprodução, relacionando estrutura, função, ambiente e evolução.</p></details>`;
  const cases={fish:['Brânquias + circulação','Água passa por superfícies branquiais, gases difundem-se e o sistema circulatório distribui O₂ aos tecidos.'],insect:['Traqueias','Ar percorre tubos e chega próximo às células; hemolinfa geralmente não é o principal transporte de O₂.'],human:['Integração sistêmica','Ventilação e débito cardíaco aumentam para sustentar trocas e transporte; metabolismo também aumenta produção de calor e CO₂.']};
  function init(root){const r=root.querySelector('#bio09Result');root.querySelectorAll('#bio09Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Organismos e hereditariedade',technical:'Fisiologia comparada • digestão, circulação, respiração, excreção e reprodução',title:'Como corpos diferentes resolvem os mesmos problemas da vida?',objective:'<strong>Objetivo:</strong> comparar soluções fisiológicas para obtenção de nutrientes, trocas gasosas, transporte, excreção e reprodução, relacionando estrutura, ambiente e evolução.',html:lessonHtml,init});}
  MBB.enableChapter('09 Fisiologia comparada',show);
})();
