(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Em uma discussão, aparecem três frases: “a vida surgiu por acaso e isso já está provado”, “Pasteur provou que vida nunca pode surgir de matéria não viva” e “como ninguém viu o primeiro ser vivo aparecer, qualquer explicação vale do mesmo jeito”.</strong><p>As três afirmações confundem níveis diferentes de conhecimento. A Ciência pode investigar <strong>processos naturais, testar hipóteses e comparar evidências</strong>, mas não possui uma gravação direta do primeiro sistema vivo. Também não deve transformar experimentos históricos em conclusões que eles não testaram.</p>${q('A','Comece pelo método','Qual atitude é mais científica diante de uma questão sobre a origem da vida?',[['a','separar o que foi observado, o que é hipótese e o que ainda permanece incerto'],['b','tratar a hipótese preferida como certeza'],['c','descartar qualquer hipótese sobre eventos antigos']],'a','Correto. Ciência reconstrói eventos passados combinando evidências, mecanismos testáveis e previsões.','Ausência de observação direta não impede investigação, mas exige clareza sobre grau de evidência.')}
  <p class="central-question"><strong>Nossa missão:</strong> entender <strong>como a Ciência investiga um evento que não podemos observar diretamente</strong> e distinguir biogênese, hipóteses sobre origem da vida e limites dos experimentos.</p></div></section>

  <section><h3>1. Fato, hipótese, teoria e crença não são degraus da mesma escada</h3><p>Na linguagem cotidiana, “teoria” pode significar palpite. Em Ciência, uma <strong>teoria científica</strong> é uma estrutura explicativa abrangente sustentada por evidências e capaz de gerar previsões testáveis. Uma <strong>hipótese</strong> é uma explicação específica que pode ser investigada.</p><div class="table-wrap"><table><thead><tr><th>Termo</th><th>Uso adequado</th></tr></thead><tbody><tr><td>Observação/fato</td><td>registro ou resultado obtido sob condições definidas</td></tr><tr><td>Hipótese</td><td>explicação provisória e testável</td></tr><tr><td>Teoria científica</td><td>estrutura explicativa ampla sustentada por múltiplas evidências</td></tr><tr><td>Crença</td><td>convicção que pode envolver valores, tradição ou questões não necessariamente testáveis pelo método científico</td></tr></tbody></table></div><div class="note-box"><strong>Ciência não é tribunal de questões metafísicas</strong><p>O método científico trabalha com explicações naturais que possam ser confrontadas com evidências. Questões religiosas ou metafísicas podem ter outros âmbitos de discussão; o conteúdo escolar precisa evitar fingir que métodos diferentes respondem exatamente às mesmas perguntas.</p></div></section>

  <section><h3>2. A antiga ideia de geração espontânea foi testada em condições concretas</h3><p>Durante séculos, era comum pensar que certos organismos surgiam espontaneamente de matéria em decomposição. Experimentos progressivamente mais controlados mostraram que, nas condições testadas, organismos observados vinham de outros organismos ou de estruturas reprodutivas já existentes.</p><div class="analysis-steps"><div><span>1</span><strong>Redi</strong><p>carne protegida de moscas não desenvolvia larvas do mesmo modo.</p></div><div><span>2</span><strong>Spallanzani</strong><p>caldos aquecidos e vedados permaneceram sem crescimento em seus testes.</p></div><div><span>3</span><strong>Críticas</strong><p>questionaram ar, vedação e condições experimentais.</p></div><div><span>4</span><strong>Pasteur</strong><p>frascos de pescoço de cisne permitiam entrada de ar e retinham partículas.</p></div><div><span>5</span><strong>Conclusão</strong><p>crescimento microbiano dependia de contaminação nas condições estudadas.</p></div></div><div class="ok-box"><strong>O que Pasteur mostrou — e o que não mostrou</strong><p>Seus experimentos refutaram a geração espontânea rotineira de microrganismos em caldos nas condições testadas. Eles <strong>não recriaram nem testaram diretamente a origem da primeira vida na Terra primitiva</strong>.</p></div>${q('B','Limite experimental','Por que é incorreto dizer que Pasteur provou que vida nunca poderia surgir de matéria não viva em nenhuma condição possível?',[['a','porque seu experimento testou condições específicas de contaminação e crescimento microbiano'],['b','porque ele não usou microscópio'],['c','porque microrganismos não são seres vivos']],'a','Correto. Extrapolar além das condições testadas produziria uma conclusão maior que a evidência.','Um bom experimento responde à pergunta que realmente foi testada.')}</section>

  <section><h3>3. Biogênese e origem da vida respondem a perguntas diferentes</h3><p><strong>Biogênese</strong> descreve a observação de que, nas condições atuais estudadas, seres vivos surgem de outros seres vivos. A investigação da <strong>origem da vida</strong> pergunta como sistemas capazes de metabolismo, compartimentalização e hereditariedade podem ter surgido na Terra primitiva a partir de processos não biológicos.</p><div class="comparison-grid"><div class="example-box"><strong class="card-title">Pergunta de Pasteur</strong><p>Microrganismos aparecem espontaneamente em caldo esterilizado nas condições do experimento?</p></div><div class="example-box"><strong class="card-title">Pergunta da origem da vida</strong><p>Que processos químicos e físicos, ao longo de muito tempo e em ambientes primitivos, poderiam gerar sistemas cada vez mais complexos?</p></div></div></section>

  <section><h3>4. Evolução química é uma família de hipóteses, não uma receita completa já comprovada</h3><p>Oparin e Haldane propuseram, historicamente, que moléculas simples poderiam originar moléculas orgânicas mais complexas sob condições da Terra primitiva. Ideias modernas investigam várias etapas: síntese de moléculas orgânicas, concentração, formação de polímeros, compartimentos, catálise e sistemas de hereditariedade.</p><div class="concept-flow"><div><strong>Moléculas simples</strong><span>fontes ambientais</span></div><div class="flow-arrow">→</div><div><strong>Complexidade química</strong><span>moléculas + compartimentos</span></div><div class="flow-arrow">→</div><div><strong>Sistemas evolutivos</strong><span>replicação + variação + seleção</span></div></div><div class="note-box"><strong>A etapa difícil é a ponte completa</strong><p>Produzir moléculas orgânicas é diferente de produzir uma célula viva. A pesquisa atual investiga caminhos parciais e condições possíveis; não existe uma única sequência histórica demonstrada passo a passo.</p></div></section>

  <section><h3>5. Miller e Urey testaram uma etapa química — não “criaram vida”</h3><p>Em 1953, Stanley Miller, orientado por Harold Urey, simulou uma mistura gasosa e fontes de energia para investigar se moléculas orgânicas poderiam ser formadas abióticamente. O experimento produziu aminoácidos e outras moléculas orgânicas.</p><p>Hoje sabemos que a composição exata da atmosfera primitiva é mais complexa e debatida do que a mistura usada no experimento. Mesmo assim, o resultado foi importante por demonstrar que <strong>síntese abiótica de moléculas orgânicas é quimicamente possível em certas condições</strong>.</p><div class="visual-box"><strong class="card-title">O que o experimento realmente testou</strong><svg class="lesson-visual" viewBox="0 0 760 280" role="img" aria-label="Esquema do experimento de Miller-Urey com água aquecida, gases, descarga elétrica e coleta de moléculas orgânicas."><defs><marker id="bio06a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#2f7d32"/></marker></defs><rect x="30" y="80" width="150" height="120" rx="15" fill="#eaf5ff" stroke="#a9c8df"/><text x="105" y="115" text-anchor="middle" font-weight="900">Água aquecida</text><text x="105" y="145" text-anchor="middle" font-size="13">vapor</text><rect x="300" y="50" width="160" height="150" rx="15" fill="#fff8e8" stroke="#d9c082"/><text x="380" y="90" text-anchor="middle" font-weight="900">Mistura de gases</text><text x="380" y="120" text-anchor="middle" font-size="13">+ descarga elétrica</text><text x="380" y="150" text-anchor="middle" font-size="13">fonte de energia</text><rect x="580" y="80" width="150" height="120" rx="15" fill="#edf8ee" stroke="#a8cfaa"/><text x="655" y="115" text-anchor="middle" font-weight="900">Coleta</text><text x="655" y="145" text-anchor="middle" font-size="13">moléculas orgânicas</text><path d="M180 140 H296" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio06a)"/><path d="M460 140 H576" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio06a)"/></svg><p class="visual-caption">Representação conceitual; o aparato real possuía circulação fechada e condensação.</p></div></section>

  <section><h3>6. Panspermia desloca a origem espacial, mas não resolve sozinha a origem última</h3><p>A hipótese da <strong>panspermia</strong> considera a possibilidade de moléculas orgânicas complexas ou formas de vida terem chegado à Terra vindas de outro local. Há evidências de moléculas orgânicas em meteoritos e no espaço, mas isso não demonstra que a vida terrestre veio pronta de fora.</p><p>Mesmo se transferência de vida entre mundos fosse demonstrada, ainda restaria a pergunta: <strong>como essa vida surgiu originalmente?</strong></p></section>

  <section><h3>7. Um bom modelo de origem precisa enfrentar vários problemas ao mesmo tempo</h3><div class="four-col"><div class="example-box"><strong class="card-title">Informação</strong><p>como surgiu hereditariedade capaz de copiar informação com variação?</p></div><div class="example-box"><strong class="card-title">Metabolismo</strong><p>como redes químicas passaram a aproveitar fontes de energia?</p></div><div class="example-box"><strong class="card-title">Compartimento</strong><p>como reações ficaram concentradas e separadas do ambiente?</p></div><div class="example-box"><strong class="card-title">Evolução</strong><p>quando sistemas começaram a sofrer seleção diferencial?</p></div></div><p>Hipóteses como “mundo de RNA”, metabolismo primeiro e protocélulas lipídicas exploram partes diferentes desse quebra-cabeça e podem se combinar em cenários mais complexos.</p></section>

  <section><h3>8. Ciência histórica usa vestígios, química e comparação — não apenas testemunho direto</h3><p>Também não observamos diretamente a formação de montanhas antigas ou todos os eventos evolutivos do passado. Reconstruímos processos usando vestígios, mecanismos testáveis, datação, comparação e experimentos que verificam partes do modelo.</p><div class="source-check"><strong>Pergunte ao encontrar uma afirmação sobre origem da vida</strong><p>Ela descreve um experimento? Uma hipótese? Um cenário plausível? Uma evidência indireta? Ou apresenta uma possibilidade como fato consumado?</p></div></section>

  <section><h3>9. Investigador de afirmações</h3><div class="interactive-lab" id="bio06Lab"><div class="lab-heading"><h4>O que a evidência realmente permite concluir?</h4></div><div class="choice-row"><button type="button" data-case="pasteur">Pasteur</button><button type="button" data-case="miller">Miller-Urey</button><button type="button" data-case="meteorite">Orgânicos em meteorito</button></div><div class="lab-result" id="bio06Result"><strong>Escolha um caso.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>10. Você consegue separar evidência de extrapolação?</h3>
  ${q('1','Hipótese','Uma hipótese científica deve ser:',[['a','testável e confrontável com evidências'],['b','uma certeza definitiva'],['c','uma opinião impossível de avaliar']],'a','Correto. Hipóteses precisam produzir consequências investigáveis.','O caráter provisório não significa ausência de rigor.')}
  ${q('2','Teoria','Uma teoria científica é:',[['a','um palpite sem evidências'],['b','uma estrutura explicativa ampla sustentada por evidências'],['c','uma hipótese que deixou de poder ser testada']],'b','Correto. Teoria não é sinônimo de palpite no uso científico.','Ela organiza evidências e produz previsões.')}
  ${q('3','Redi/Pasteur','Esses experimentos apoiaram principalmente:',[['a','biogênese nas condições testadas'],['b','panspermia'],['c','a formação da primeira célula']],'a','Correto. Eles investigaram geração espontânea em sistemas experimentais.','Não extrapole para a origem primordial da vida.')}
  ${q('4','Pasteur','O pescoço de cisne foi importante porque:',[['a','permitia entrada de ar enquanto retinha partículas contaminantes'],['b','impedia qualquer contato com ar'],['c','criava aminoácidos']],'a','Correto. O desenho respondia à crítica de que o ar teria sido excluído.','O ponto foi separar ar de contaminação por partículas/microrganismos.')}
  ${q('5','Miller-Urey','O experimento mostrou que:',[['a','moléculas orgânicas podem ser formadas abióticamente em certas condições'],['b','uma célula viva foi criada'],['c','a atmosfera primitiva tinha exatamente aquela composição']],'a','Correto. Foi um teste de química prebiótica, não criação de vida.','O experimento não resolveu todas as etapas da origem.')}
  ${q('6','Panspermia','Qual limitação permanece?',[['a','ela pode deslocar o local da origem sem explicar necessariamente como a vida surgiu'],['b','ela prova abiogênese'],['c','ela demonstra que meteoritos são vivos']],'a','Correto. Transferência e origem são perguntas diferentes.','Encontrar orgânicos no espaço não equivale a encontrar vida.')}
  ${q('7','Ciência histórica','Eventos antigos podem ser estudados cientificamente porque:',[['a','vestígios e mecanismos atuais permitem testar previsões de modelos históricos'],['b','somente eventos filmados podem ser ciência'],['c','o passado não deixa evidências']],'a','Correto. Geologia e evolução também usam inferência histórica testável.','Observação direta do evento inteiro não é requisito absoluto.')}
  ${q('8','Limites','Qual frase é mais responsável?',[['a','já conhecemos cada etapa exata da origem da vida'],['b','existem hipóteses e resultados experimentais importantes, mas a sequência histórica completa ainda é objeto de pesquisa'],['c','nada pode ser investigado']],'b','Correto. Incerteza bem delimitada faz parte da ciência.','Evite tanto certeza excessiva quanto ceticismo absoluto.')}
  <div class="challenge-box"><strong>Desafio MbB — corrija duas frases</strong><p>Reescreva de modo cientificamente rigoroso: <strong>1)</strong> “Pasteur provou que vida nunca surge de matéria não viva”; <strong>2)</strong> “Miller criou vida em laboratório”.</p><details><summary>Critério para conferir</summary><p>A primeira deve limitar Pasteur à geração espontânea microbiana nas condições testadas. A segunda deve dizer que Miller-Urey produziu moléculas orgânicas abióticas em um modelo experimental, não seres vivos.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT201:</strong> natureza da Ciência, biogênese/abiogênese, experimentos históricos, hipóteses sobre origem da vida, Oparin-Haldane, Miller-Urey e avaliação crítica de evidências.</p></details>`;
  const cases={pasteur:['Conclusão limitada','O crescimento microbiano dependia de contaminação nas condições testadas; não é um experimento sobre a Terra pré-biótica.'],miller:['Química prebiótica','Moléculas orgânicas foram formadas sem vida em certas condições experimentais; nenhuma célula foi produzida.'],meteorite:['Matéria orgânica extraterrestre','Mostra que química orgânica ocorre fora da Terra; não demonstra, por si, que a vida terrestre chegou em meteoritos.']};
  function init(root){const r=root.querySelector('#bio06Result');root.querySelectorAll('#bio06Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Origem e evolução',technical:'Origem da vida • método científico, biogênese e química prebiótica',title:'Como investigar a origem da vida sem transformar hipótese em certeza?',objective:'<strong>Objetivo:</strong> distinguir evidência, hipótese e teoria, compreender experimentos sobre geração espontânea e avaliar com rigor hipóteses e experimentos relacionados à origem da vida.',html:lessonHtml,init});}
  MBB.enableChapter('06 Origem da vida',show);
})();
