(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Dois irmãos compartilham muitos genes, mas não são idênticos. Um tem sangue tipo A e o outro tipo O. Na família, alguém pergunta: “Se características são herdadas, por que irmãos podem ser tão diferentes?”</strong><p>Hereditariedade não copia um “pacote pronto” de pai e mãe. Na reprodução sexuada, alelos são segregados e recombinados; cada descendente recebe uma combinação particular. Além disso, muitas características dependem de <strong>vários genes e do ambiente</strong>, não de uma única regra mendeliana.</p>${q('A','Ponto de partida','Qual afirmação é mais adequada?',[['a','irmãos recebem exatamente os mesmos alelos'],['b','irmãos podem receber combinações diferentes de alelos devido à segregação e recombinação'],['c','toda diferença entre irmãos é causada apenas pelo ambiente']],'b','Correto. A meiose e a fecundação geram combinações distintas de alelos.','Hereditariedade envolve probabilidades e combinações, não cópia idêntica.')}
  <p class="central-question"><strong>Nossa missão:</strong> usar os modelos de Mendel para entender <strong>gene, alelo, segregação, probabilidade, ABO e Rh</strong>, reconhecendo ao mesmo tempo os limites desses modelos.</p></div></section>

  <section><h3>1. Gene, alelo, genótipo e fenótipo respondem a perguntas diferentes</h3><div class="table-wrap"><table><thead><tr><th>Termo</th><th>Ideia</th></tr></thead><tbody><tr><td>Gene</td><td>região de DNA associada a um produto funcional ou característica biológica</td></tr><tr><td>Alelo</td><td>uma versão de um gene</td></tr><tr><td>Genótipo</td><td>combinação de alelos considerada para um ou mais loci</td></tr><tr><td>Fenótipo</td><td>característica observável resultante de genótipo, ambiente e desenvolvimento</td></tr></tbody></table></div><div class="note-box"><strong>DNA não é destino absoluto</strong><p>Muitas características dependem de múltiplos genes, regulação, ambiente e acaso do desenvolvimento. O modelo de um gene com dois alelos é poderoso para certos problemas, mas não descreve toda a hereditariedade humana.</p></div></section>

  <section><h3>2. Mendel construiu um modelo usando cruzamentos controlados</h3><p>Gregor Mendel estudou ervilhas com características contrastantes, realizou cruzamentos planejados e contou grandes números de descendentes. Seu mérito não foi apenas “descobrir dominantes e recessivos”, mas transformar hereditariedade em um problema quantitativo.</p><p>Em um modelo simples com dois alelos, um indivíduo diploide possui dois alelos para um locus — um herdado de cada genitor. Durante a formação de gametas, esses alelos se separam.</p><div class="gene-pair"><span>A</span><span>a</span></div><div class="concept-flow"><div><strong>Indivíduo Aa</strong><span>dois alelos</span></div><div class="flow-arrow">→</div><div><strong>Meiose</strong><span>segregação</span></div><div class="flow-arrow">→</div><div><strong>Gametas</strong><span>A ou a</span></div></div></section>

  <section><h3>3. A 1ª Lei de Mendel é um modelo de segregação</h3><p>Para um locus simples, os dois alelos de um indivíduo diploide se separam na formação dos gametas. Um heterozigoto <strong>Aa</strong> produz, em média, metade dos gametas com A e metade com a, supondo ausência de distorções de segregação.</p><div class="formula-box"><span class="formula-name">Cruzamento simples</span><div class="big-formula">Aa × Aa → 1 AA : 2 Aa : 1 aa</div><p>Se A for completamente dominante sobre a, a proporção fenotípica esperada é 3 : 1. Isso é uma <strong>probabilidade esperada</strong>, não garantia de quatro filhos em sequência.</p></div>${q('B','Probabilidade','Um casal heterozigoto Aa × Aa tem quatro filhos. É obrigatório que exatamente três apresentem fenótipo dominante e um recessivo?',[['a','sim, Mendel obriga essa sequência'],['b','não; 3:1 é proporção esperada em muitos descendentes, e cada fecundação é um evento probabilístico'],['c','sim, mas apenas se os filhos nascerem na ordem certa']],'b','Correto. Probabilidades descrevem frequências esperadas, não roteiros familiares.','Não transforme uma proporção populacional em sequência determinística.')}</section>

  <section><h3>4. Dominante não significa melhor, mais forte ou mais comum</h3><p>Dominância descreve a relação entre alelos no fenótipo do heterozigoto. Um alelo dominante pode ser raro; um recessivo pode ser comum. Dominância também não indica vantagem evolutiva.</p><div class="comparison-grid"><div class="example-box"><strong class="card-title">Dominância completa</strong><p>Aa apresenta o mesmo fenótipo considerado de AA.</p></div><div class="example-box"><strong class="card-title">Codominância</strong><p>os dois alelos contribuem de forma detectável ao fenótipo, como Iᴬ e Iᴮ no sistema ABO.</p></div></div></section>

  <section><h3>5. Probabilidade ajuda a prever cruzamentos sem decorar quadrados</h3><p>Se um evento tem probabilidade 1/2 e outro independente também 1/2, a probabilidade de ambos ocorrerem é 1/2 × 1/2 = 1/4. Esse raciocínio permite resolver muitos cruzamentos sem desenhar todas as combinações.</p><div class="formula-box"><span class="formula-name">Exemplo Aa × Aa</span><div class="big-formula">P(aa) = 1/2 × 1/2 = 1/4</div><p>Cada genitor precisa fornecer o alelo a.</p></div></section>

  <section><h3>6. A 2ª Lei descreve assortimento independente — com limites</h3><p>Para genes em cromossomos diferentes, ou suficientemente distantes no mesmo cromossomo, a segregação de um par de alelos pode ser aproximadamente independente da de outro par. Esse é o modelo clássico da 2ª Lei.</p><p>Genes próximos no mesmo cromossomo podem ser <strong>ligados</strong> e não seguir as proporções de independência simples. Recombinação pode separá-los com frequência relacionada à distância entre loci.</p><div class="note-box"><strong>Regra escolar com condição explícita</strong><p>“Genes segregam independentemente” não é uma lei sem exceções. O modelo funciona quando os loci se comportam como independentes.</p></div></section>

  <section><h3>7. Sistema ABO mostra alelos múltiplos e codominância</h3><p>O sistema ABO envolve três alelos principais: <strong>Iᴬ, Iᴮ e i</strong>. Iᴬ e Iᴮ são codominantes entre si e ambos dominam sobre i no modelo escolar.</p><div class="table-wrap"><table><thead><tr><th>Fenótipo</th><th>Genótipos possíveis</th><th>Antígenos principais nas hemácias</th></tr></thead><tbody><tr><td>A</td><td>IᴬIᴬ ou Iᴬi</td><td>A</td></tr><tr><td>B</td><td>IᴮIᴮ ou Iᴮi</td><td>B</td></tr><tr><td>AB</td><td>IᴬIᴮ</td><td>A e B</td></tr><tr><td>O</td><td>ii</td><td>nem A nem B</td></tr></tbody></table></div>${q('C','ABO','Uma pessoa de fenótipo A pode ter qual genótipo?',[['a','somente IᴬIᴬ'],['b','IᴬIᴬ ou Iᴬi'],['c','IᴮIᴮ']],'b','Correto. Fenótipo dominante não revela sozinho se há alelo i.','O mesmo fenótipo pode corresponder a mais de um genótipo.')}</section>

  <section><h3>8. Compatibilidade transfusional é mais complexa que um quadro escolar</h3><p>No ensino introdutório, costuma-se comparar antígenos ABO/Rh das hemácias e anticorpos do receptor. Isso ajuda a entender por que certas combinações podem causar aglutinação e hemólise.</p><div class="warning-strip"><strong>Não use tabelas escolares para decisões clínicas.</strong> Transfusões reais exigem tipagem, pesquisa de anticorpos, testes de compatibilidade e protocolos do serviço de saúde. Existem muitos outros sistemas de grupos sanguíneos além de ABO e Rh.</div><p>O sistema Rh é frequentemente simplificado pelo antígeno D: presença costuma ser descrita como Rh positivo e ausência como Rh negativo. A genética real do sistema Rh envolve mais loci e variantes do que o modelo escolar.</p></section>

  <section><h3>9. Eritroblastose fetal mostra por que imunologia e genética se encontram</h3><p>Em certas gestações, uma pessoa RhD negativa pode produzir anticorpos contra hemácias RhD positivas após sensibilização. Em exposição posterior, esses anticorpos podem atravessar a placenta e afetar hemácias fetais.</p><p>A medicina dispõe de prevenção com imunoglobulina anti-D em situações indicadas. O objetivo escolar aqui é entender o mecanismo geral de <strong>antígeno, sensibilização e resposta imune</strong>, não orientar conduta clínica.</p><div class="note-box"><strong>Sempre contexto clínico</strong><p>Gestação e transfusão envolvem avaliação individual, exames e protocolos profissionais. Não tente deduzir risco pessoal apenas por uma tabela de genética.</p></div></section>

  <section><h3>10. Características humanas geralmente ultrapassam o modelo mendeliano simples</h3><p>Altura, massa corporal, cor da pele, pressão arterial e muitos outros fenótipos são influenciados por muitos genes e fatores ambientais. Até características com forte componente genético podem apresentar penetrância incompleta, expressividade variável e interação com ambiente.</p><div class="three-col"><div class="example-box"><strong class="card-title">Monogênica simples</strong><p>um locus explica grande parte do padrão observado</p></div><div class="example-box"><strong class="card-title">Poligênica</strong><p>muitos loci contribuem para variação contínua</p></div><div class="example-box"><strong class="card-title">Multifatorial</strong><p>genes + ambiente + desenvolvimento interagem</p></div></div><div class="ok-box"><strong>Mendel é base, não limite</strong><p>O valor dos modelos mendelianos está em ensinar segregação e probabilidade. A genética moderna amplia esses princípios para sistemas mais complexos.</p></div></section>

  <section><h3>11. Investigador genético</h3><div class="interactive-lab" id="bio10Lab"><div class="lab-heading"><h4>Qual princípio resolve o caso?</h4></div><div class="choice-row"><button type="button" data-case="aa">Aa × Aa</button><button type="button" data-case="abo">Iᴬi × Iᴮi</button><button type="button" data-case="linked">Genes próximos</button></div><div class="lab-result" id="bio10Result"><strong>Escolha um caso.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>12. Você consegue usar Mendel sem transformar genética em destino?</h3>
  ${q('1','Alelo','Alelo é:',[['a','uma versão de um gene'],['b','um cromossomo inteiro'],['c','um órgão']],'a','Correto. Alelos são variantes de um locus gênico.','Não confunda gene, alelo e cromossomo.')}
  ${q('2','Segregação','Um indivíduo Aa produz gametas:',[['a','A ou a'],['b','somente Aa'],['c','AA e aa']],'a','Correto. Os alelos se segregam durante a formação dos gametas.','Gametas recebem uma cópia do locus no modelo diploide simples.')}
  ${q('3','Aa × Aa','Qual a probabilidade teórica de aa em cada gestação?',[['a','1/4'],['b','1/2'],['c','3/4']],'a','Correto. Cada genitor fornece a com probabilidade 1/2.','Multiplique 1/2 por 1/2.')}
  ${q('4','Dominância','Dominante significa:',[['a','sempre mais comum e melhor'],['b','que determina o fenótipo do heterozigoto no modelo considerado'],['c','que será escolhido pela seleção natural']],'b','Correto. Dominância é relação fenotípica entre alelos.','Não confunda dominância com frequência ou vantagem adaptativa.')}
  ${q('5','2ª Lei','Assortimento independente é esperado principalmente quando:',[['a','loci comportam-se como independentes'],['b','genes estão sempre colados no mesmo cromossomo'],['c','não existe meiose']],'a','Correto. Ligação gênica pode modificar as proporções.','A condição de independência precisa ser verificada.')}
  ${q('6','ABO','Pessoa AB possui genótipo:',[['a','IᴬIᴮ'],['b','ii'],['c','Iᴬi']],'a','Correto. Iᴬ e Iᴮ são codominantes.','AB exige os dois alelos codominantes.')}
  ${q('7','Transfusão','Por que uma tabela ABO escolar não basta para transfusão real?',[['a','porque existem outros antígenos e são necessários testes de compatibilidade'],['b','porque grupos sanguíneos não existem'],['c','porque o sangue muda de tipo toda semana']],'a','Correto. Serviços de saúde realizam testes específicos e seguem protocolos.','ABO/Rh é apenas parte da imunogenética transfusional.')}
  ${q('8','Fenótipo complexo','Altura humana é melhor descrita como:',[['a','característica influenciada por muitos genes e ambiente'],['b','um único alelo dominante universal'],['c','sem componente genético']],'a','Correto. É um exemplo clássico de característica complexa.','Modelos monogênicos não explicam toda variação humana.')}
  <div class="challenge-box"><strong>Desafio MbB — irmãos e probabilidade</strong><p>Explique por que dois irmãos dos mesmos pais podem ter grupos ABO diferentes e muitas outras diferenças fenotípicas. Use <strong>segregação, recombinação, probabilidade e ambiente</strong>.</p><details><summary>Critério para conferir</summary><p>A resposta deve mostrar que cada gameta contém combinações diferentes, fecundação é probabilística e muitos fenótipos dependem de múltiplos genes e ambiente.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT205:</strong> Leis de Mendel, segregação, probabilidade, alelos múltiplos, sistemas ABO/Rh e interpretação crítica de padrões de hereditariedade.</p></details>`;
  const cases={aa:['Segregação + probabilidade','Cada genitor Aa fornece a com probabilidade 1/2; P(aa)=1/4 em cada fecundação, sem memória das gestações anteriores.'],abo:['Alelos múltiplos','Gametas podem levar Iᴬ ou i de um genitor e Iᴮ ou i do outro, permitindo fenótipos A, B, AB ou O em probabilidades específicas.'],linked:['Ligação gênica','Genes próximos no mesmo cromossomo podem não assortir independentemente; recombinação entre eles pode ocorrer com frequência menor que 50%.']};
  function init(root){const r=root.querySelector('#bio10Result');root.querySelectorAll('#bio10Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Organismos e hereditariedade',technical:'Genética • Mendel, probabilidade, ABO, Rh e limites do modelo simples',title:'Por que irmãos podem ser parecidos sem serem iguais?',objective:'<strong>Objetivo:</strong> compreender segregação e probabilidade mendeliana, alelos múltiplos e sistemas sanguíneos, reconhecendo ligação gênica, características complexas e limites de modelos escolares.',html:lessonHtml,init});}
  MBB.enableChapter('10 Genética e sangue',show);
})();
