(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Uma escola fica perto de uma avenida movimentada. Nos horários de pico, há fumaça visível em alguns dias, ruído intenso e lixo acumulado após chuvas fortes. Alunos perguntam: “Se o problema está no ambiente, como ele chega ao nosso corpo?”</strong><p>A resposta exige acompanhar <strong>vias de exposição</strong>: ar inalado, água e alimentos, contato com substâncias, som e condições do espaço urbano. Poluição não é apenas “sujeira”: é a introdução ou presença de agentes físicos, químicos ou biológicos em níveis capazes de alterar o ambiente e aumentar riscos à saúde e aos ecossistemas.</p>${q('A','Primeira análise','Qual pergunta é mais adequada antes de concluir que um poluente causou um problema de saúde?',[['a','Qual é o agente, a concentração, a via e o tempo de exposição?'],['b','O nome do agente parece assustador?'],['c','A postagem sobre o assunto teve muitas curtidas?']],'a','Correto. Risco depende do agente e das condições reais de exposição.','Uma palavra ou imagem forte não substitui dose, via, tempo e evidência.')}
  <p class="central-question"><strong>Nossa missão:</strong> compreender como <strong>ar, água, ruído, resíduos e saneamento</strong> podem afetar sistemas do corpo e como prevenção depende de controlar fontes e reduzir exposição.</p></div></section>

  <section><h3>1. Poluente, exposição e risco são conceitos diferentes</h3><p>Um <strong>poluente</strong> é um agente que pode degradar o ambiente ou produzir efeitos indesejados. <strong>Exposição</strong> descreve o contato efetivo com esse agente. <strong>Risco</strong> depende da combinação entre perigo e condições de exposição.</p><div class="concept-flow"><div><strong>Fonte</strong><span>trânsito • esgoto • indústria • resíduos</span></div><div class="flow-arrow">→</div><div><strong>Exposição</strong><span>inalação • ingestão • contato • som</span></div><div class="flow-arrow">→</div><div><strong>Efeito possível</strong><span>depende de dose, tempo e vulnerabilidade</span></div></div><div class="note-box"><strong>“Químico” não significa automaticamente “tóxico”</strong><p>Toda matéria é formada por substâncias químicas. Toxicidade e risco dependem da identidade do agente, dose, via, duração da exposição e características do organismo.</p></div></section>

  <section><h3>2. Saneamento interrompe rotas de transmissão e contaminação</h3><p>Abastecimento de água segura, coleta e tratamento de esgoto, manejo de resíduos e drenagem urbana reduzem exposição a microrganismos patogênicos, matéria orgânica em excesso, vetores e contaminantes.</p><div class="two-col"><div class="example-box"><strong class="card-title">Sem saneamento adequado</strong><p>Esgoto pode alcançar rios, poços ou áreas alagadas; resíduos podem obstruir drenagem e favorecer vetores.</p></div><div class="example-box"><strong class="card-title">Com barreiras de proteção</strong><p>Tratamento, redes adequadas, coleta, drenagem e monitoramento reduzem vias de exposição antes que o problema chegue ao indivíduo.</p></div></div><p>Prevenção coletiva costuma ser mais eficiente que depender apenas de comportamentos individuais depois que o ambiente já foi contaminado.</p></section>

  <section><h3>3. Poluição do ar começa no pulmão, mas seus efeitos não ficam restritos a ele</h3><p>Partículas finas e gases podem irritar vias respiratórias e desencadear respostas inflamatórias. Partículas muito pequenas podem alcançar regiões profundas dos pulmões. A exposição crônica a determinados poluentes está associada também a maior risco cardiovascular.</p><div class="visual-box"><strong class="card-title">Do ar ambiente à troca gasosa</strong><svg class="lesson-visual" viewBox="0 0 760 280" role="img" aria-label="Fluxo simplificado mostrando ar com partículas entrando pelas vias respiratórias, alcançando alvéolos e relacionando pulmões à circulação sanguínea."><defs><marker id="bio04a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#2f7d32"/></marker></defs><rect x="30" y="75" width="170" height="115" rx="15" fill="#f4f4f4" stroke="#bbb"/><text x="115" y="110" text-anchor="middle" font-size="18" font-weight="900">Ar ambiente</text><text x="115" y="140" text-anchor="middle" font-size="13">gases + partículas</text><rect x="295" y="55" width="170" height="155" rx="15" fill="#eef8ff" stroke="#a9c9df"/><text x="380" y="95" text-anchor="middle" font-size="18" font-weight="900">Vias e pulmões</text><text x="380" y="126" text-anchor="middle" font-size="13">irritação • inflamação</text><text x="380" y="151" text-anchor="middle" font-size="13">troca gasosa</text><rect x="560" y="75" width="170" height="115" rx="15" fill="#fff0ef" stroke="#dfaaa5"/><text x="645" y="110" text-anchor="middle" font-size="18" font-weight="900">Circulação</text><text x="645" y="140" text-anchor="middle" font-size="13">efeitos sistêmicos possíveis</text><path d="M200 132 H292" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio04a)"/><path d="M465 132 H557" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio04a)"/></svg><p class="visual-caption">Esquema geral. Diferentes poluentes possuem mecanismos e riscos distintos.</p></div><div class="note-box"><strong>Correlação populacional não diagnostica uma pessoa</strong><p>Estudos epidemiológicos identificam padrões de risco em populações. Sintomas individuais exigem avaliação clínica; o conteúdo aqui explica mecanismos e prevenção ambiental, não faz diagnóstico.</p></div></section>

  <section><h3>4. Sistema respiratório e cardiovascular trabalham integrados</h3><p>Nos alvéolos, O₂ difunde-se para o sangue e CO₂ faz o caminho oposto. O coração impulsiona o sangue, distribuindo gases, nutrientes e outras substâncias. Por isso alterações importantes na qualidade do ar podem repercutir sobre dois sistemas integrados.</p><div class="concept-flow"><div><strong>Ventilação</strong><span>ar chega aos alvéolos</span></div><div class="flow-arrow">→</div><div><strong>Troca gasosa</strong><span>O₂ ↔ CO₂</span></div><div class="flow-arrow">→</div><div><strong>Circulação</strong><span>transporte pelo organismo</span></div></div></section>

  <section><h3>5. Ruído intenso é um agente físico e pode danificar estruturas auditivas</h3><p>Som é uma onda mecânica. A orelha externa conduz o som, estruturas da orelha média transmitem vibrações e células sensoriais da cóclea convertem estímulos mecânicos em sinais nervosos.</p><p>Exposição a níveis sonoros elevados, especialmente por períodos prolongados, pode lesar células sensoriais. O risco depende da intensidade e do tempo de exposição; portanto não existe um único número que descreva qualquer situação.</p><div class="warning-strip"><strong>Prevenção responsável:</strong> reduzir a fonte, aumentar distância quando possível, limitar o tempo de exposição e usar proteção adequada em contextos ocupacionais ou de risco. Limites legais e recomendações dependem do contexto e devem ser consultados em normas atualizadas.</div>${q('B','Som e saúde','Por que intensidade e duração devem ser consideradas juntas?',[['a','Porque exposição curta e longa ao mesmo nível podem representar riscos diferentes'],['b','Porque o ouvido mede apenas tempo'],['c','Porque ruído só afeta quem já tem perda auditiva']],'a','Correto. Dose sonora depende de intensidade e duração, entre outros fatores.','Risco não depende de uma única variável isolada.')}</section>

  <section><h3>6. Visão depende de luz, foco e células sensoriais — não de “forçar os olhos” como um músculo</h3><p>A córnea e o cristalino participam do foco da luz sobre a retina. Fotorreceptores transformam energia luminosa em sinais que seguem pelo nervo óptico e são processados pelo sistema nervoso.</p><p>Ambientes com iluminação inadequada podem causar desconforto e fadiga visual, mas afirmações sobre “poluição visual” precisam ser específicas: excesso de estímulos, contraste, sinalização e organização urbana podem afetar atenção e conforto; isso não deve ser transformado automaticamente em alegações de dano ocular permanente.</p><div class="source-check"><strong>Boa prática de informação em saúde</strong><p>Evite vídeos que transformam qualquer desconforto em doença. Procure fontes institucionais e diferencie mecanismo biológico comprovado, associação observada e opinião.</p></div></section>

  <section><h3>7. Poluição da água pode afetar humanos e ecossistemas ao mesmo tempo</h3><p>Esgoto sem tratamento, excesso de nutrientes, metais, solventes, óleo, resíduos e microrganismos podem alterar qualidade da água por mecanismos diferentes. A mesma água pode servir como via de exposição humana e como ambiente para organismos aquáticos.</p><div class="three-col"><div class="example-box"><strong class="card-title">Biológica</strong><p>microrganismos patogênicos e matéria orgânica</p></div><div class="example-box"><strong class="card-title">Química</strong><p>nutrientes, metais, pesticidas e outros contaminantes</p></div><div class="example-box"><strong class="card-title">Física</strong><p>temperatura, turbidez, sedimentos e resíduos</p></div></div><p>No próximo capítulo veremos em detalhe como excesso de nutrientes pode desencadear eutrofização e queda de oxigênio dissolvido.</p></section>

  <section><h3>8. Biomateriais mostram que materiais podem interagir com sistemas vivos de formas planejadas</h3><p><strong>Biomaterial</strong> é um material desenvolvido ou selecionado para interagir com sistemas biológicos em aplicações médicas ou biotecnológicas. Pode ser metálico, cerâmico, polimérico, natural ou composto.</p><p>Biocompatibilidade não significa “inércia absoluta”. O desempenho depende da aplicação, superfície, propriedades mecânicas, degradação, resposta do organismo e tempo de uso.</p><div class="two-col"><div class="example-box"><strong class="card-title">Prótese/implante</strong><p>precisa combinar resistência, compatibilidade e função mecânica</p></div><div class="example-box"><strong class="card-title">Curativo ou scaffold</strong><p>pode ser projetado para contato temporário e interação controlada com tecidos</p></div></div></section>

  <section><h3>9. Investigador ambiente-corpo</h3><div class="interactive-lab" id="bio04Lab"><div class="lab-heading"><h4>Qual é a melhor intervenção?</h4></div><div class="choice-row"><button type="button" data-case="air">Fumaça do trânsito</button><button type="button" data-case="sewage">Esgoto no córrego</button><button type="button" data-case="noise">Ruído da oficina</button></div><div class="lab-result" id="bio04Result"><strong>Escolha um caso.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>10. Você consegue ligar ambiente, exposição e prevenção?</h3>
  ${q('1','Poluição','Qual definição é mais adequada?',[['a','qualquer coisa que pareça feia'],['b','presença ou introdução de agentes que alteram o ambiente e podem produzir efeitos indesejados'],['c','apenas fumaça industrial']],'b','Correto. Poluição pode envolver agentes físicos, químicos e biológicos.','Não limite poluição a aparência ou a uma única fonte.')}
  ${q('2','Risco','O risco de um agente depende de:',[['a','perigo + condições de exposição'],['b','apenas do nome da substância'],['c','apenas do cheiro']],'a','Correto. Dose, via e tempo importam.','Perigo e exposição não são sinônimos.')}
  ${q('3','Saneamento','Por que saneamento é uma medida coletiva de saúde?',[['a','porque interrompe vias de contaminação antes da exposição individual'],['b','porque substitui toda higiene pessoal'],['c','porque elimina todos os microrganismos do planeta']],'a','Correto. Saneamento atua em fontes e rotas ambientais.','Ele reduz riscos coletivos, mas não elimina toda forma de exposição.')}
  ${q('4','Ar','Partículas finas podem afetar:',[['a','apenas a aparência do céu'],['b','sistema respiratório e, em exposições relevantes, também risco cardiovascular'],['c','somente o sistema digestório']],'b','Correto. Pulmões e circulação estão funcionalmente integrados.','Não restrinja o efeito possível apenas ao local de entrada.')}
  ${q('5','Audição','Qual combinação aumenta risco de dano auditivo?',[['a','maior intensidade e maior duração de exposição'],['b','som baixo por poucos segundos obrigatoriamente'],['c','apenas o tipo de música']],'a','Correto. Intensidade e tempo precisam ser analisados juntos.','O gênero musical não é o princípio biológico central.')}
  ${q('6','Visão','Qual afirmação é responsável?',[['a','desconforto visual prova lesão permanente'],['b','iluminação e excesso de estímulos podem causar desconforto, mas dano ocular exige evidência específica'],['c','todo anúncio luminoso causa cegueira']],'b','Correto. Separe desconforto, desempenho e dano clínico.','Não transforme uma associação ampla em diagnóstico.')}
  ${q('7','Água','Poluição da água pode ser:',[['a','somente química'],['b','biológica, química ou física'],['c','somente visual']],'b','Correto. Diferentes agentes alteram a água por mecanismos distintos.','Considere microrganismos, nutrientes, metais, sedimentos e temperatura.')}
  ${q('8','Biomaterial','Biocompatibilidade significa:',[['a','que o material é sempre totalmente inerte'],['b','que seu desempenho biológico é adequado para uma aplicação e contexto definidos'],['c','que qualquer material natural é seguro']],'b','Correto. A aplicação e a resposta biológica importam.','Naturalidade ou inércia absoluta não definem sozinhas biocompatibilidade.')}
  <div class="challenge-box"><strong>Desafio MbB — prevenção antes do sintoma</strong><p>Uma escola registra ruído alto, poeira do trânsito e água acumulada com resíduos no entorno. Proponha ações em três níveis: <strong>controle da fonte, redução da exposição e monitoramento</strong>. Explique por que agir na fonte costuma ser mais efetivo que esperar sintomas.</p><details><summary>Critério para conferir</summary><p>A resposta deve distinguir fontes e vias de exposição e propor medidas coletivas antes de depender exclusivamente de equipamentos individuais ou atendimento após o dano.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT306:</strong> poluição, saneamento, impactos sobre visão, audição, sistemas respiratório e cardiovascular, prevenção e aplicações de biomateriais.</p></details>`;
  const cases={air:['Prioridade: controlar a fonte','Transporte coletivo, inspeção, redução de emissões e planejamento urbano atacam a fonte; monitoramento da qualidade do ar ajuda a avaliar resultados.'],sewage:['Prioridade: interromper a descarga','Coleta e tratamento de esgoto reduzem a contaminação na origem; avisos individuais não substituem saneamento.'],noise:['Prioridade: reduzir emissão e exposição','Barreiras, manutenção, isolamento e organização de horários podem reduzir o ruído antes de recorrer apenas à proteção individual.']};
  function init(root){const r=root.querySelector('#bio04Result');root.querySelectorAll('#bio04Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Ambiente e sociedade',technical:'Poluição e saúde • exposição, saneamento e sistemas do corpo',title:'Como a poluição do ambiente chega ao nosso corpo?',objective:'<strong>Objetivo:</strong> relacionar agentes ambientais, vias de exposição e efeitos biológicos, compreendendo saneamento, poluição do ar, água e ruído, sistemas respiratório/cardiovascular, visão, audição e biomateriais.',html:lessonHtml,init});}
  MBB.enableChapter('04 Poluição e saúde',show);
})();
