(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Depois de chuvas fortes, uma lagoa próxima a áreas agrícolas fica esverdeada. Dias depois, aparecem peixes mortos. Um comentário diz: “O fertilizante envenenou os peixes diretamente”. Outro afirma: “As algas consumiram todo o oxigênio”.</strong><p>As duas explicações podem simplificar demais. Excesso de nutrientes pode favorecer crescimento intenso de algas e outros produtores; depois, morte e decomposição dessa biomassa podem aumentar o consumo de oxigênio dissolvido por microrganismos. O resultado pode ser <strong>hipóxia</strong>, especialmente em determinadas condições.</p>${q('A','Construa a cadeia causal','Qual sequência descreve melhor um caso típico de eutrofização?',[['a','nutrientes ↑ → crescimento de produtores ↑ → matéria orgânica/decomposição ↑ → O₂ dissolvido pode ↓'],['b','fertilizante → oxigênio vira nitrogênio → peixes somem'],['c','água verde → prova automática de veneno']],'a','Correto. A queda de oxigênio pode ser consequência indireta de uma cadeia ecológica e microbiana.','Procure uma sequência de mecanismos, não uma causa instantânea escolhida pela aparência.')}
  <p class="central-question"><strong>Nossa missão:</strong> acompanhar <strong>água, carbono, oxigênio e nitrogênio</strong> entre atmosfera, organismos, solo e água e entender como atividades humanas alteram esses ciclos.</p></div></section>

  <section><h3>1. Ciclos biogeoquímicos conectam partes vivas e não vivas do planeta</h3><p>Átomos não pertencem permanentemente a um organismo. Carbono que hoje compõe uma folha pode, mais tarde, estar no solo, na atmosfera ou em outro ser vivo. Os ciclos biogeoquímicos descrevem transferências entre <strong>biosfera, atmosfera, hidrosfera e geosfera</strong>.</p><div class="concept-flow"><div><strong>Reservatório</strong><span>atmosfera • solo • oceanos</span></div><div class="flow-arrow">↔</div><div><strong>Processos</strong><span>fotossíntese • respiração • decomposição</span></div><div class="flow-arrow">↔</div><div><strong>Organismos</strong><span>incorporam e devolvem matéria</span></div></div><div class="ok-box"><strong>Matéria circula</strong><p>Os elementos são continuamente transferidos e transformados. O ciclo não significa que cada átomo segue uma rota única nem que todas as transferências ocorrem na mesma velocidade.</p></div></section>

  <section><h3>2. O ciclo da água é movido por energia e gravidade</h3><p>Evaporação e transpiração transferem água para a atmosfera; condensação forma gotículas; precipitação devolve água à superfície; infiltração, escoamento e armazenamento redistribuem-na.</p><p>Vegetação influencia infiltração, evapotranspiração e escoamento. Impermeabilização urbana pode aumentar escoamento superficial e reduzir infiltração local, alterando risco de alagamentos.</p><div class="visual-box"><strong class="card-title">Água em movimento</strong><svg class="lesson-visual" viewBox="0 0 760 300" role="img" aria-label="Ciclo simplificado da água com evaporação, condensação, precipitação, infiltração e escoamento."><defs><marker id="bio05w" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#2f7d32"/></marker></defs><rect x="30" y="210" width="700" height="55" rx="15" fill="#b8d9ee"/><text x="380" y="244" text-anchor="middle" font-weight="900">oceanos, rios, solo e aquíferos</text><ellipse cx="380" cy="72" rx="145" ry="42" fill="#eef3f8" stroke="#b4c4d4"/><text x="380" y="78" text-anchor="middle" font-weight="900">atmosfera / nuvens</text><path d="M180 210 C170 155 210 125 265 100" fill="none" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio05w)"/><text x="135" y="145" font-size="13">evaporação</text><path d="M485 105 C540 130 575 165 575 207" fill="none" stroke="#2f7d32" stroke-width="4" marker-end="url(#bio05w)"/><text x="565" y="145" font-size="13">precipitação</text><path d="M330 266 V292" stroke="#2f7d32" stroke-width="4"/><text x="340" y="290" font-size="13">infiltração</text></svg></div></section>

  <section><h3>3. Carbono conecta fotossíntese, respiração, decomposição e clima</h3><p>Fotossíntese remove CO₂ do ambiente e incorpora carbono à matéria orgânica. Respiração e decomposição devolvem parte desse carbono. Oceanos trocam CO₂ com a atmosfera e armazenam grandes quantidades de carbono. Combustão de biomassa e combustíveis fósseis também libera CO₂.</p><div class="two-col"><div class="example-box"><strong class="card-title">Ciclo rápido</strong><p>fotossíntese, alimentação, respiração e decomposição movimentam carbono em escalas relativamente curtas</p></div><div class="example-box"><strong class="card-title">Reservatórios lentos</strong><p>sedimentos, rochas e combustíveis fósseis podem armazenar carbono por escalas geológicas</p></div></div><p>A queima de combustíveis fósseis transfere rapidamente carbono de reservatórios geológicos para a atmosfera, conectando este capítulo ao estudo do clima.</p></section>

  <section><h3>4. O ciclo do oxigênio está fortemente ligado ao carbono</h3><p>Fotossíntese oxigênica libera O₂; respiração aeróbica e diversas oxidações consomem O₂. Em ambientes aquáticos, a concentração de oxigênio dissolvido depende também de temperatura, mistura da água, fotossíntese e respiração/decomposição.</p><div class="note-box"><strong>Oxigênio dissolvido não é “bolha de ar presa”</strong><p>Moléculas de O₂ podem estar dissolvidas na água. Sua disponibilidade para organismos aquáticos depende das condições do ambiente e do metabolismo da comunidade.</p></div></section>

  <section><h3>5. Nitrogênio atmosférico é abundante, mas a maioria dos seres vivos não o usa diretamente</h3><p>A atmosfera contém muito N₂, porém plantas e animais não conseguem simplesmente incorporá-lo diretamente à maioria das biomoléculas. Microrganismos desempenham papéis decisivos ao transformar compostos nitrogenados.</p><div class="table-wrap"><table><thead><tr><th>Processo</th><th>Ideia central</th><th>Agentes importantes</th></tr></thead><tbody><tr><td>Fixação</td><td>N₂ é convertido em formas biologicamente utilizáveis</td><td>certos microrganismos; também processos industriais e descargas elétricas</td></tr><tr><td>Nitrificação</td><td>amônio é transformado em nitrito/nitrato</td><td>microrganismos do solo e água</td></tr><tr><td>Assimilação</td><td>plantas incorporam nitrogênio inorgânico em moléculas orgânicas</td><td>produtores</td></tr><tr><td>Amonificação</td><td>nitrogênio orgânico retorna a formas amoniacais</td><td>decompositores</td></tr><tr><td>Desnitrificação</td><td>formas nitrogenadas retornam a N₂</td><td>certos microrganismos em condições específicas</td></tr></tbody></table></div><div class="ok-box"><strong>Microrganismos são engenheiros do ciclo</strong><p>Sem transformações microbianas, a disponibilidade de nitrogênio biologicamente utilizável seria muito diferente.</p></div></section>

  <section><h3>6. Fertilizante aumenta disponibilidade de nutrientes — e o excesso pode escapar do sistema produtivo</h3><p>Fertilizantes fornecem nutrientes essenciais às plantas. O problema não é a palavra “fertilizante”, mas <strong>quantidade, momento, forma de aplicação, solo, chuva e capacidade de absorção</strong>. Nutrientes não utilizados podem ser lixiviados ou carregados para corpos d’água.</p><div class="comparison-grid"><div class="example-box"><strong class="card-title">Fertilizante mineral</strong><p>pode fornecer nutrientes em formas rapidamente disponíveis; exige manejo preciso</p></div><div class="example-box"><strong class="card-title">Adubação orgânica</strong><p>também fornece nutrientes e matéria orgânica; excesso igualmente pode contaminar água</p></div></div><div class="note-box"><strong>“Orgânico” não significa “sem risco de eutrofização”</strong><p>Qualquer fonte que aumente excessivamente a carga de nitrogênio ou fósforo pode contribuir para o problema.</p></div></section>

  <section><h3>7. Eutrofização é uma cascata de efeitos, não apenas “água com algas”</h3><div class="analysis-steps"><div><span>1</span><strong>Nutrientes</strong><p>N e/ou P aumentam.</p></div><div><span>2</span><strong>Produção</strong><p>algas/cianobactérias podem proliferar.</p></div><div><span>3</span><strong>Biomassa</strong><p>mais matéria orgânica entra na decomposição.</p></div><div><span>4</span><strong>Respiração</strong><p>decompositores consomem O₂.</p></div><div><span>5</span><strong>Hipóxia</strong><p>organismos sensíveis podem morrer ou migrar.</p></div></div><p>A intensidade depende de luz, temperatura, circulação da água, nutrientes limitantes, espécies presentes e outras condições.</p>${q('B','Mecanismo','Por que peixes podem morrer após uma grande floração de algas?',[['a','porque toda alga é venenosa'],['b','porque decomposição e respiração podem reduzir O₂ dissolvido, entre outros mecanismos possíveis'],['c','porque algas transformam água em sal']],'b','Correto. Hipóxia é um mecanismo importante; algumas florações também podem envolver toxinas, mas não todas.','Não generalize toda floração como tóxica nem ignore o papel do oxigênio.')}</section>

  <section><h3>8. “Maré vermelha” e eutrofização não são sinônimos perfeitos</h3><p>O termo popular <strong>maré vermelha</strong> é usado para certas florações de microalgas, mas a água nem sempre fica vermelha e nem toda floração é tóxica. Florações podem ocorrer por diferentes combinações de nutrientes, temperatura, circulação e características das espécies.</p><p>Eutrofização descreve enriquecimento excessivo por nutrientes e suas consequências ecológicas. Os fenômenos podem estar relacionados, mas não são equivalentes em todos os casos.</p><div class="source-check"><strong>Evite diagnóstico pela cor da água</strong><p>Identificação de uma floração exige análise ambiental e, quando necessário, identificação dos organismos e toxinas. Aparência isolada não basta.</p></div></section>

  <section><h3>9. Mitigar exige agir na origem dos nutrientes</h3><div class="three-col"><div class="example-box"><strong class="card-title">Saneamento</strong><p>reduzir lançamento de esgoto e nutrientes em corpos d’água</p></div><div class="example-box"><strong class="card-title">Manejo agrícola</strong><p>dose, época, cobertura do solo, rotação e faixas vegetadas</p></div><div class="example-box"><strong class="card-title">Restauração</strong><p>matas ciliares e áreas úmidas podem reduzir escoamento e reter nutrientes</p></div></div><p>Adubação verde e rotação com leguminosas podem contribuir para manejo do nitrogênio, mas também precisam ser integradas a um sistema produtivo planejado.</p></section>

  <section><h3>10. Investigador dos ciclos</h3><div class="interactive-lab" id="bio05Lab"><div class="lab-heading"><h4>Qual ciclo foi alterado?</h4></div><div class="choice-row"><button type="button" data-case="forest">Desmatamento</button><button type="button" data-case="farm">Excesso de fertilizante</button><button type="button" data-case="city">Solo impermeabilizado</button></div><div class="lab-result" id="bio05Result"><strong>Escolha um caso.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>11. Você consegue acompanhar átomos entre ambiente e vida?</h3>
  ${q('1','Ciclos','O que circula nos ciclos biogeoquímicos?',[['a','matéria/elementos entre reservatórios e organismos'],['b','energia sem nenhuma dissipação'],['c','somente água']],'a','Correto. Carbono, nitrogênio, água e outros componentes são transferidos entre compartimentos.','Energia flui; matéria circula.')}
  ${q('2','Água','Impermeabilização urbana tende a:',[['a','aumentar infiltração sempre'],['b','aumentar escoamento superficial e reduzir infiltração local'],['c','parar a precipitação']],'b','Correto. A superfície muda a rota da água após a chuva.','O efeito ocorre no movimento da água sobre e dentro do solo.')}
  ${q('3','Carbono','Qual processo remove CO₂ da atmosfera e incorpora carbono em matéria orgânica?',[['a','fotossíntese'],['b','respiração'],['c','combustão']],'a','Correto. Produtores fixam carbono durante fotossíntese.','Respiração e combustão tendem a liberar CO₂.')}
  ${q('4','Nitrogênio','Por que bactérias são fundamentais no ciclo do N?',[['a','porque realizam transformações entre diferentes formas nitrogenadas'],['b','porque criam átomos de nitrogênio'],['c','porque toda bactéria faz fotossíntese']],'a','Correto. Várias etapas dependem de metabolismos microbianos.','Elas transformam compostos; não criam o elemento.')}
  ${q('5','Fertilizantes','Qual afirmação é adequada?',[['a','fertilizante orgânico nunca contribui para eutrofização'],['b','qualquer fonte de nutrientes em excesso pode contribuir'],['c','somente fertilizantes minerais contêm nitrogênio']],'b','Correto. Quantidade e destino dos nutrientes são centrais.','“Orgânico” não significa impacto zero.')}
  ${q('6','Eutrofização','Qual etapa contribui diretamente para queda de O₂?',[['a','respiração/decomposição intensa da biomassa'],['b','fixação de luz pela retina'],['c','evaporação do nitrogênio']],'a','Correto. Decompositores usam oxigênio ao metabolizar matéria orgânica.','A queda de O₂ é ligada ao metabolismo da comunidade.')}
  ${q('7','Floração','Toda floração de algas é tóxica?',[['a','sim'],['b','não; espécies e condições determinam produção de toxinas e impactos'],['c','sim, se a água mudar de cor']],'b','Correto. Aparência não determina toxicidade.','Há florações não tóxicas e florações que nem ficam vermelhas.')}
  ${q('8','Mitigação','Qual intervenção ataca a causa do enriquecimento por nutrientes?',[['a','reduzir esgoto e perdas de fertilizantes'],['b','pintar a água'],['c','retirar apenas peixes mortos']],'a','Correto. Controle da fonte reduz entrada de nutrientes.','Tratar só o efeito não interrompe a causa.')}
  <div class="challenge-box"><strong>Desafio MbB — do campo à lagoa</strong><p>Explique em oito etapas ou menos como um nutriente aplicado numa plantação pode terminar relacionado à morte de peixes em uma lagoa. Inclua transporte, crescimento de produtores, decomposição e oxigênio.</p><details><summary>Critério para conferir</summary><p>A cadeia deve relacionar chuva/escoamento ou lixiviação → nutriente → aumento da produção primária → biomassa → decomposição/respiração → redução de O₂ → estresse/mortalidade, sem afirmar que esse é o único mecanismo possível.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT105:</strong> ciclos da água, carbono, oxigênio e nitrogênio; fertilizantes; interferências humanas; eutrofização, florações e ações de mitigação.</p></details>`;
  const cases={forest:['Carbono + água','Remover vegetação altera estoques de carbono, evapotranspiração, infiltração e escoamento, além de afetar a biodiversidade.'],farm:['Nitrogênio/fósforo','Nutrientes que excedem a absorção podem alcançar águas e favorecer eutrofização.'],city:['Água','Impermeabilização redireciona a água para escoamento superficial, podendo aumentar picos de vazão e transporte de poluentes.']};
  function init(root){const r=root.querySelector('#bio05Result');root.querySelectorAll('#bio05Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Ambiente e sociedade',technical:'Ciclos biogeoquímicos • água, carbono, oxigênio, nitrogênio e eutrofização',title:'Por que fertilizante demais pode tirar oxigênio da água?',objective:'<strong>Objetivo:</strong> compreender ciclos biogeoquímicos, o papel de microrganismos, fertilizantes e alterações humanas, explicando eutrofização e avaliando medidas de mitigação.',html:lessonHtml,init});}
  MBB.enableChapter('05 Ciclos biogeoquímicos',show);
})();
