(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Depois de uma sequência de dias muito quentes, uma postagem afirma: “Se hoje fez frio em outra cidade, o aquecimento global foi desmentido”. Em outra rede, alguém escreve que “o efeito estufa é o problema que precisamos eliminar”.</strong><p>As duas frases misturam conceitos diferentes. Um dia frio não descreve o clima do planeta e <strong>o efeito estufa natural é essencial para manter temperaturas compatíveis com a vida como conhecemos</strong>. O problema está na intensificação do balanço radiativo por mudanças na composição atmosférica e em seus efeitos sobre o sistema climático.</p>${q('A','Primeira distinção','Qual frase é mais adequada?',[['a','Tempo e clima são a mesma coisa'],['b','Tempo descreve condições de curto prazo; clima envolve padrões e estatísticas de longo prazo'],['c','Um evento isolado prova ou refuta sozinho uma tendência global']],'b','Correto. Clima é analisado por padrões de longo prazo, não por uma única tarde quente ou fria.','Evite usar um evento pontual como sinônimo de clima.')}
  <p class="central-question"><strong>Nossa missão:</strong> distinguir <strong>efeito estufa, aquecimento global, mudanças climáticas e eventos extremos</strong> e avaliar como escolhas energéticas e ações humanas entram nesse sistema.</p></div></section>

  <section><h3>1. O efeito estufa natural ajuda a manter a Terra habitável</h3><p>A superfície terrestre absorve parte da energia solar e emite radiação infravermelha. Gases como vapor d’água, CO₂, CH₄ e N₂O absorvem e reemitem parte dessa radiação, reduzindo a perda de energia para o espaço. Esse processo natural contribui para manter a temperatura média da superfície muito acima do que seria sem esses gases.</p><div class="visual-box"><strong class="card-title">Um balanço de energia, não uma “coberta sólida”</strong><svg class="lesson-visual" viewBox="0 0 760 300" role="img" aria-label="Esquema do efeito estufa mostrando radiação solar entrando, superfície emitindo infravermelho e parte da radiação sendo absorvida e reemitida por gases atmosféricos."><defs><marker id="bio03a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#2f7d32"/></marker></defs><circle cx="100" cy="75" r="40" fill="#ffd35f"/><text x="100" y="82" text-anchor="middle" font-weight="900">Sol</text><rect x="80" y="230" width="600" height="45" rx="12" fill="#b8d8a5"/><text x="380" y="258" text-anchor="middle" font-weight="900">superfície</text><path d="M140 95 L300 215" stroke="#e0a600" stroke-width="7" marker-end="url(#bio03a)"/><path d="M390 225 C390 170 390 135 390 80" stroke="#b42318" stroke-width="6" fill="none"/><path d="M390 130 C470 120 500 165 480 210" stroke="#b42318" stroke-width="6" fill="none" marker-end="url(#bio03a)"/><text x="535" y="105" font-size="15" font-weight="900">gases de efeito estufa</text><text x="535" y="130" font-size="13">absorvem e reemitem</text><text x="535" y="151" font-size="13">radiação infravermelha</text></svg><p class="visual-caption">Esquema qualitativo: o sistema climático envolve nuvens, oceanos, gelo, circulação atmosférica e muitos feedbacks adicionais.</p></div><div class="note-box"><strong>Eliminar o efeito estufa não é objetivo climático</strong><p>Sem o efeito estufa natural, a Terra seria muito mais fria. A questão ambiental é a <strong>intensificação</strong> do efeito por mudanças na composição atmosférica associadas principalmente à queima de combustíveis fósseis, desmatamento e outras atividades humanas.</p></div></section>

  <section><h3>2. Aquecimento global descreve uma tendência; mudanças climáticas incluem efeitos mais amplos</h3><p><strong>Aquecimento global</strong> refere-se ao aumento de longo prazo da temperatura média do sistema climático. <strong>Mudanças climáticas</strong> incluem alterações persistentes em temperatura, precipitação, gelo, nível do mar, frequência ou intensidade de certos extremos e padrões regionais.</p><p>Esses fenômenos são avaliados com séries de dados, modelos físicos, medições independentes e comparação entre causas naturais e antrópicas. Não dependem de um termômetro isolado.</p><div class="source-check"><strong>Letramento climático</strong><p>Ao encontrar uma afirmação climática, pergunte: qual período foi analisado? Qual região? Qual variável? A fonte distingue tendência de evento isolado? Há dados e metodologia?</p></div></section>

  <section><h3>3. Eventos extremos exigem linguagem cuidadosa</h3><p>Ondas de calor, chuvas intensas, secas e incêndios podem ocorrer por múltiplos fatores. A ciência de <strong>atribuição climática</strong> não costuma perguntar simplesmente “a mudança climática causou este evento?”, mas investiga se ela alterou a <strong>probabilidade ou intensidade</strong> de determinados tipos de evento.</p>${q('B','Evento extremo','Após uma enchente, qual afirmação é mais responsável?',[['a','Todo evento extremo tem uma única causa'],['b','É preciso analisar meteorologia, uso do solo, drenagem, vulnerabilidade e como o clima alterou probabilidades ou intensidades'],['c','Se já houve enchentes no passado, mudanças climáticas não podem influenciar as atuais']],'b','Correto. Risco resulta da combinação entre perigo, exposição e vulnerabilidade, além dos fatores físicos do evento.','Eventos extremos podem ter múltiplas causas e condicionantes.')}</section>

  <section><h3>4. Risco de desastre não depende apenas do fenômeno natural</h3><p>Duas cidades podem receber chuva semelhante e sofrer impactos muito diferentes. Ocupação de áreas de risco, impermeabilização do solo, drenagem, vegetação, sistemas de alerta e condições socioeconômicas alteram a vulnerabilidade.</p><div class="concept-flow"><div><strong>Perigo</strong><span>chuva intensa, calor, seca...</span></div><div class="flow-arrow">+</div><div><strong>Exposição e vulnerabilidade</strong><span>pessoas, infraestrutura, desigualdade</span></div><div class="flow-arrow">→</div><div><strong>Risco</strong><span>impactos potenciais</span></div></div><p>Educação para redução de riscos inclui prevenção, planejamento territorial, comunicação confiável, rotas de evacuação e resposta organizada.</p></section>

  <section><h3>5. Matriz energética é o conjunto das fontes usadas por uma sociedade</h3><p>Uma matriz energética pode combinar petróleo, gás natural, carvão, hidrelétrica, biomassa, eólica, solar, nuclear e outras fontes. “Renovável” e “não renovável” descrevem disponibilidade e reposição do recurso em escalas humanas, mas <strong>não determinam sozinhas o impacto ambiental total</strong>.</p><div class="table-wrap"><table><thead><tr><th>Fonte</th><th>Ponto de análise</th><th>Impactos que precisam ser avaliados</th></tr></thead><tbody><tr><td>Solar/eólica</td><td>baixas emissões operacionais de gases de efeito estufa</td><td>materiais, área, mineração, descarte e integração à rede</td></tr><tr><td>Hidrelétrica</td><td>fonte renovável com armazenamento em alguns sistemas</td><td>alagamento, ecossistemas, deslocamentos e emissões em reservatórios</td></tr><tr><td>Biomassa</td><td>carbono de ciclo biológico recente</td><td>uso do solo, emissões, fertilizantes, transporte e biodiversidade</td></tr><tr><td>Fósseis</td><td>alta densidade energética e infraestrutura consolidada</td><td>CO₂, poluentes atmosféricos, extração e dependência de recurso finito</td></tr></tbody></table></div></section>

  <section><h3>6. Emissões de CO₂ ligam decisões energéticas ao ciclo do carbono</h3><p>Combustíveis fósseis armazenam carbono que permaneceu fora do ciclo rápido por milhões de anos. Ao queimá-los, transferimos esse carbono para a atmosfera em escala muito rápida. Desmatamento também pode liberar carbono e reduzir estoques biológicos.</p><div class="ok-box"><strong>Conexão com Ecologia</strong><p>O clima não é um tema separado dos ecossistemas. Temperatura, chuva, fogo, disponibilidade de água e distribuição de espécies estão conectados. Alterar o clima altera condições abióticas que moldam comunidades.</p></div></section>

  <section><h3>7. Mitigação e adaptação respondem a problemas diferentes</h3><div class="two-col"><div class="example-box"><strong class="card-title">Mitigação</strong><p>Busca reduzir causas do aquecimento, por exemplo diminuindo emissões, evitando desmatamento e aumentando eficiência energética.</p></div><div class="example-box"><strong class="card-title">Adaptação</strong><p>Busca reduzir danos e vulnerabilidades já existentes ou esperadas: infraestrutura, planejamento urbano, sistemas de alerta, manejo de água e saúde pública.</p></div></div><p>Uma política climática robusta geralmente precisa das duas: reduzir a magnitude futura do problema e preparar sistemas humanos e naturais para impactos que já não podem ser totalmente evitados.</p></section>

  <section><h3>8. Desinformação climática costuma explorar confusões simples</h3><div class="comparison-grid"><div class="example-box"><strong class="card-title">“Hoje esfriou, logo não há aquecimento global”</strong><p>Confunde tempo local de curto prazo com tendência climática de longo prazo.</p></div><div class="example-box"><strong class="card-title">“Sempre houve mudança climática”</strong><p>É verdade que o clima mudou naturalmente no passado, mas isso não elimina a necessidade de identificar as causas da mudança atual e sua velocidade.</p></div><div class="example-box"><strong class="card-title">“Fonte renovável não causa impacto”</strong><p>Renovabilidade não substitui análise de ciclo de vida, território e biodiversidade.</p></div><div class="example-box"><strong class="card-title">“Um gráfico basta”</strong><p>Escala, período, fonte, unidade e método precisam ser conhecidos antes da interpretação.</p></div></div></section>

  <section><h3>9. Investigador climático</h3><div class="interactive-lab" id="bio03Lab"><div class="lab-heading"><h4>Qual conceito está sendo confundido?</h4></div><div class="choice-row"><button type="button" data-case="cold">Dia frio</button><button type="button" data-case="flood">Enchente</button><button type="button" data-case="solar">Usina solar</button></div><div class="lab-result" id="bio03Result"><strong>Escolha um caso.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>10. Você consegue analisar clima sem slogans?</h3>
  ${q('1','Efeito estufa','Qual afirmação é correta?',[['a','É um fenômeno natural importante para a temperatura da Terra'],['b','Foi criado exclusivamente pela indústria'],['c','deve ser totalmente eliminado']],'a','Correto. O problema é sua intensificação, não a existência do fenômeno natural.','Separe efeito estufa natural de intensificação antrópica.')}
  ${q('2','Tempo x clima','Uma frente fria de três dias:',[['a','descreve sozinha o clima global'],['b','é um evento de tempo; não refuta uma tendência climática de décadas'],['c','prova que o planeta está esfriando']],'b','Correto. Escalas temporais e espaciais importam.','Um episódio curto não substitui séries climáticas.')}
  ${q('3','Aquecimento global','O termo descreve principalmente:',[['a','tendência de aumento da temperatura média do sistema climático'],['b','todo lugar ficando mais quente todos os dias'],['c','apenas ilhas de calor urbanas']],'a','Correto. Tendência global não significa monotonia local diária.','Não confunda média global com cada local e momento.')}
  ${q('4','Extremos','Atribuição climática busca frequentemente:',[['a','calcular se a mudança climática alterou probabilidade ou intensidade de eventos'],['b','provar uma causa única para todo desastre'],['c','ignorar vulnerabilidade social']],'a','Correto. A linguagem probabilística é mais adequada.','Eventos reais resultam de múltiplos fatores.')}
  ${q('5','Risco','Duas cidades recebem chuva semelhante, mas uma sofre mais. Isso pode ocorrer porque:',[['a','risco também depende de exposição, vulnerabilidade e infraestrutura'],['b','chuva deixa de obedecer à física'],['c','somente a população determina o clima']],'a','Correto. Perigo físico e vulnerabilidade social interagem.','Risco não é sinônimo de intensidade do fenômeno natural.')}
  ${q('6','Matriz energética','Uma fonte renovável é automaticamente sem impactos?',[['a','sim'],['b','não; impactos de materiais, território, resíduos e ecossistemas ainda precisam ser avaliados'],['c','sim, desde que produza eletricidade']],'b','Correto. Sustentabilidade exige análise mais ampla.','Renovabilidade é uma característica, não uma garantia de impacto zero.')}
  ${q('7','Mitigação','Qual exemplo é principalmente mitigação?',[['a','reduzir emissões de gases de efeito estufa'],['b','construir rota de evacuação para enchentes'],['c','instalar sirene de emergência']],'a','Correto. Mitigação atua nas causas; adaptação reduz vulnerabilidades aos impactos.','Rotas e sirenes são exemplos de adaptação e gestão de risco.')}
  ${q('8','Letramento científico','Antes de compartilhar um gráfico climático, o que deve ser conferido?',[['a','fonte, período, região, variável, unidade e método'],['b','apenas se as cores são convincentes'],['c','apenas o número de curtidas']],'a','Correto. Contexto e método fazem parte da evidência.','Popularidade visual não substitui qualidade de dados.')}
  <div class="challenge-box"><strong>Desafio MbB — responda a uma postagem</strong><p>Uma postagem diz: “Ontem fez 8 °C, portanto o aquecimento global acabou”. Responda em até seis frases diferenciando tempo, clima e tendência global, sem ridicularizar quem publicou.</p><details><summary>Critério para conferir</summary><p>A resposta deve explicar que um evento local de curto prazo é compatível com uma tendência global de longo prazo e que a avaliação climática usa séries de dados e múltiplas linhas de evidência.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT102, EM13CNT106, EM13CNT301 e EM13CNT303:</strong> efeito estufa, aquecimento global, eventos extremos, redução de riscos, matrizes energéticas, impactos socioambientais e letramento climático.</p></details>`;
  const cases={cold:['Tempo x clima','Um dia frio descreve tempo local. Para avaliar clima, precisamos de padrões de longo prazo e escala adequada.'],flood:['Perigo + exposição + vulnerabilidade','A chuva importa, mas ocupação do solo, drenagem, relevo e vulnerabilidade determinam grande parte do dano.'],solar:['Renovável ≠ impacto zero','Solar pode reduzir emissões operacionais, mas materiais, área, mineração, reciclagem e rede elétrica ainda precisam ser avaliados.']};
  function init(root){const r=root.querySelector('#bio03Result');root.querySelectorAll('#bio03Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Ambiente e sociedade',technical:'Clima e energia • efeito estufa, riscos, matrizes e letramento científico',title:'O efeito estufa é vilão ou condição para a vida?',objective:'<strong>Objetivo:</strong> distinguir efeito estufa, aquecimento global, mudanças climáticas e eventos extremos e analisar riscos, matrizes energéticas, mitigação, adaptação e desinformação.',html:lessonHtml,init});}
  MBB.enableChapter('03 Clima e energia',show);
})();
