(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Uma amostra de iogurte, uma folha de alface e células da mucosa da boca parecem completamente diferentes. Mesmo assim, todas envolvem células. O que uma célula precisa ter para continuar funcionando — e por que bactérias, fungos, plantas e animais resolvem esse problema de formas diferentes?</strong><p>A célula não é apenas uma “bolsa cheia de organelas”. Ela precisa <strong>separar interior e exterior, controlar trocas, realizar metabolismo, armazenar informação e produzir componentes</strong>. A diversidade celular nasce de diferentes soluções para essas necessidades fundamentais.</p>${q('A','Ponto de partida','Qual estrutura está presente em todas as células conhecidas?',[['a','membrana plasmática'],['b','núcleo'],['c','cloroplasto']],'a','Correto. Todas as células possuem membrana plasmática; núcleo e cloroplasto não são universais.','Procure uma característica compartilhada por procariontes e eucariontes.')}
  <p class="central-question"><strong>Nossa missão:</strong> compreender a célula como <strong>sistema vivo que troca matéria, transforma energia e mantém informação</strong>, comparando procariontes, eucariontes, bactérias e fungos.</p></div></section>

  <section><h3>1. A teoria celular conectou observações feitas em organismos muito diferentes</h3><p>Com o desenvolvimento da microscopia, cientistas perceberam que tecidos vegetais e animais eram formados por unidades recorrentes. A teoria celular foi construída e ampliada ao longo do tempo.</p><div class="three-col"><div class="example-box"><strong class="card-title">Unidade estrutural</strong><p>seres vivos são formados por uma ou mais células</p></div><div class="example-box"><strong class="card-title">Unidade funcional</strong><p>processos essenciais da vida ocorrem em células</p></div><div class="example-box"><strong class="card-title">Continuidade</strong><p>novas células surgem pela divisão de células preexistentes</p></div></div><div class="note-box"><strong>Vírus colocam uma fronteira interessante</strong><p>Vírus não possuem organização celular nem metabolismo autônomo. Dependem de células hospedeiras para replicar-se. Por isso, classificá-los simplesmente como “células muito pequenas” é incorreto.</p></div></section>

  <section><h3>2. As linhagens celulares compartilham um plano básico de organização</h3><p>Membrana plasmática, citoplasma, material genético e ribossomos formam o <strong>plano celular básico</strong> encontrado nas linhagens de seres vivos. Há, porém, células altamente especializadas que perdem componentes durante a diferenciação. Hemácias maduras de mamíferos, por exemplo, perdem núcleo e ribossomos, embora tenham se originado de células precursoras que possuíam essas estruturas.</p><div class="organism-grid"><div><strong>Membrana</strong><p>delimita a célula e regula trocas</p></div><div><strong>Citoplasma</strong><p>meio onde ocorrem muitas reações</p></div><div><strong>DNA</strong><p>armazena informação hereditária no plano celular fundamental</p></div><div><strong>Ribossomos</strong><p>participam da síntese de proteínas nas células que os mantêm</p></div></div><div class="note-box"><strong>Modelo geral com exceções de diferenciação</strong><p>Quando livros dizem que “toda célula tem DNA e ribossomos”, estão descrevendo o plano básico da organização celular. Células terminalmente especializadas podem constituir exceções sem invalidar a teoria celular.</p></div></section>

  <section><h3>3. Procarionte e eucarionte descrevem organização celular</h3><div class="table-wrap"><table><thead><tr><th>Característica</th><th>Procarionte</th><th>Eucarionte</th></tr></thead><tbody><tr><td>Núcleo delimitado por membrana</td><td>não</td><td>sim</td></tr><tr><td>Organelas membranosas</td><td>não há o sistema típico das eucariontes</td><td>presentes em diferentes combinações</td></tr><tr><td>Material genético</td><td>região do nucleoide; podem existir plasmídeos</td><td>principalmente no núcleo; também em mitocôndrias/cloroplastos</td></tr><tr><td>Exemplos</td><td>bactérias e arqueias</td><td>animais, plantas, fungos e protistas</td></tr></tbody></table></div><div class="ok-box"><strong>“Mais simples” não significa “mal adaptada”</strong><p>Bactérias possuem organização menos compartimentalizada que células eucarióticas, mas exibem enorme diversidade metabólica e evolutiva.</p></div></section>

  <section><h3>4. A membrana é seletivamente permeável</h3><p>A bicamada lipídica e proteínas de membrana controlam trocas entre célula e ambiente. Algumas substâncias atravessam por difusão; outras dependem de proteínas transportadoras ou de gasto de energia.</p><div class="visual-box"><strong class="card-title">Três modos gerais de atravessar a membrana</strong><svg class="lesson-visual" viewBox="0 0 760 290" role="img" aria-label="Esquema comparando difusão simples, difusão facilitada e transporte ativo através de membrana."><rect x="50" y="125" width="660" height="42" rx="18" fill="#dfeadf" stroke="#90ad92"/><text x="380" y="152" text-anchor="middle" font-weight="900">membrana plasmática</text><text x="140" y="60" text-anchor="middle" font-weight="900">Difusão simples</text><text x="380" y="60" text-anchor="middle" font-weight="900">Difusão facilitada</text><text x="620" y="60" text-anchor="middle" font-weight="900">Transporte ativo</text><path d="M140 90 V205" stroke="#2f7d32" stroke-width="5" marker-end="url(#bio08arr)"/><rect x="355" y="120" width="50" height="52" rx="12" fill="#7299c2"/><path d="M380 90 V205" stroke="#2f7d32" stroke-width="5" marker-end="url(#bio08arr)"/><rect x="595" y="115" width="50" height="62" rx="12" fill="#9b7fc1"/><path d="M620 205 V90" stroke="#b42318" stroke-width="5" marker-end="url(#bio08arr2)"/><text x="620" y="235" text-anchor="middle" font-size="13">usa energia</text><defs><marker id="bio08arr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#2f7d32"/></marker><marker id="bio08arr2" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#b42318"/></marker></defs></svg><p class="visual-caption">Difusão ocorre a favor de gradiente; transporte ativo pode mover substâncias contra gradientes usando energia.</p></div></section>

  <section><h3>5. Osmose é movimento de água associado a diferenças de concentração</h3><p>Em uma membrana permeável à água, a água tende a deslocar-se conforme o potencial hídrico/gradiente osmótico criado pelas concentrações de solutos. Em células animais, excesso de entrada ou saída de água pode alterar o volume celular; células vegetais possuem parede celular, que modifica a resposta mecânica.</p>${q('B','Osmose','Uma célula animal é colocada em meio muito hipertônico. Qual tendência é esperada?',[['a','perder água e diminuir de volume'],['b','ganhar água indefinidamente'],['c','produzir parede celular']],'a','Correto. A água tende a sair da célula em direção ao meio mais concentrado em solutos efetivos.','Analise o gradiente de água, não uma “atração consciente” do sal.')}</section>

  <section><h3>6. Organelas distribuem funções em células eucarióticas</h3><div class="table-wrap"><table><thead><tr><th>Estrutura</th><th>Função geral</th></tr></thead><tbody><tr><td>Núcleo</td><td>abriga grande parte do DNA e regula expressão gênica</td></tr><tr><td>Mitocôndria</td><td>etapas importantes da respiração aeróbica</td></tr><tr><td>Cloroplasto</td><td>fotossíntese em plantas e algas</td></tr><tr><td>Retículo endoplasmático</td><td>síntese/processamento de proteínas e lipídios</td></tr><tr><td>Complexo de Golgi</td><td>modificação e distribuição de moléculas</td></tr><tr><td>Lisossomos</td><td>digestão intracelular em muitos eucariontes</td></tr></tbody></table></div><p>Organelas não “trabalham isoladas”. Produtos de uma via tornam-se substratos de outra, e membranas organizam fluxos internos.</p></section>

  <section><h3>7. Bactérias não são sinônimo de doença</h3><p>Bactérias participam de decomposição, ciclos do nitrogênio, microbiotas, fermentações, produção de alimentos, biotecnologia e também podem causar doenças. O efeito depende da espécie, linhagem, local e contexto.</p><div class="three-col"><div class="example-box"><strong class="card-title">Ambiente</strong><p>decomposição e ciclos biogeoquímicos</p></div><div class="example-box"><strong class="card-title">Tecnologia</strong><p>fermentação, enzimas e engenharia genética</p></div><div class="example-box"><strong class="card-title">Saúde</strong><p>microbiotas úteis e espécies patogênicas</p></div></div><div class="note-box"><strong>Antibiótico não trata vírus</strong><p>Antibióticos atuam sobre alvos bacterianos específicos. Uso inadequado aumenta pressão seletiva e favorece disseminação de resistência. Decisões de tratamento são médicas e não devem ser feitas a partir deste material.</p></div></section>

  <section><h3>8. Fungos são heterótrofos por absorção e têm enorme importância ecológica</h3><p>Fungos não são plantas. Possuem células eucarióticas, parede celular com quitina em muitos grupos e obtêm nutrientes por absorção após digestão extracelular.</p><div class="two-col"><div class="example-box"><strong class="card-title">Decompositores</strong><p>reciclam matéria orgânica e nutrientes nos ecossistemas</p></div><div class="example-box"><strong class="card-title">Simbioses e tecnologia</strong><p>micorrizas, líquens, alimentos, fermentações e medicamentos</p></div></div><p>Alguns fungos causam doenças ou deterioram alimentos, mas reduzi-los a “mofo prejudicial” elimina boa parte de sua diversidade e importância.</p></section>

  <section><h3>9. Microscopia exige distinguir imagem, escala e interpretação</h3><p>Uma micrografia pode mostrar estruturas reais, mas cor pode ser artificial, contraste pode ser aumentado e preparação da amostra pode modificar o material. A escala indicada na imagem é essencial para não comparar tamanhos visualmente de forma enganosa.</p><div class="source-check"><strong>Pergunte ao observar uma imagem microscópica</strong><p>Qual técnica foi usada? A cor é natural? Há barra de escala? A amostra está viva, fixada ou corada? O que é observação e o que é interpretação?</p></div></section>

  <section><h3>10. Investigador celular</h3><div class="interactive-lab" id="bio08Lab"><div class="lab-heading"><h4>Qual mecanismo explica o caso?</h4></div><div class="choice-row"><button type="button" data-case="salt">Célula em meio salino</button><button type="button" data-case="antibiotic">Antibiótico contra gripe</button><button type="button" data-case="yeast">Levedura no pão</button></div><div class="lab-result" id="bio08Result"><strong>Escolha um caso.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>11. Você consegue pensar a célula como sistema?</h3>
  ${q('1','Teoria celular','Qual ideia pertence à teoria celular?',[['a','novas células surgem de células preexistentes'],['b','todo ser vivo possui cloroplastos'],['c','vírus são células pequenas']],'a','Correto. Continuidade celular é um princípio central.','Cloroplastos não são universais e vírus não possuem organização celular.')}
  ${q('2','Plano celular','Qual conjunto representa melhor o plano básico compartilhado pelas linhagens celulares, reconhecendo que células muito especializadas podem perder componentes durante a diferenciação?',[['a','membrana, material genético e ribossomos'],['b','núcleo e mitocôndrias em todas as células'],['c','parede celular em todas as células']],'a','Correto. É o plano celular fundamental; hemácias maduras de mamíferos são um exemplo de célula especializada que perde núcleo e ribossomos durante a diferenciação.','Núcleo, mitocôndrias e parede celular não são estruturas universais.')}
  ${q('3','Procarionte','Bactérias possuem:',[['a','núcleo membranoso'],['b','DNA em região não delimitada por núcleo'],['c','cloroplastos obrigatoriamente']],'b','Correto. O nucleoide não é envolvido por membrana nuclear.','Procariontes não possuem núcleo típico eucariótico.')}
  ${q('4','Difusão','Difusão simples ocorre:',[['a','a favor de gradiente sem gasto direto de ATP'],['b','sempre contra gradiente'],['c','apenas em células mortas']],'a','Correto. O movimento líquido acompanha o gradiente.','Transporte contra gradiente requer mecanismos ativos.')}
  ${q('5','Transporte ativo','O que o diferencia?',[['a','pode mover substâncias contra gradiente usando energia'],['b','sempre transporta água'],['c','não usa proteínas']],'a','Correto. Bombas e transportadores ativos mantêm gradientes celulares.','Água e difusão não definem transporte ativo.')}
  ${q('6','Bactérias','Qual afirmação é correta?',[['a','todas causam doenças'],['b','possuem papéis ecológicos, tecnológicos e de saúde muito diversos'],['c','são vírus']],'b','Correto. Patogenicidade é apenas uma parte da diversidade bacteriana.','Evite generalizar um grupo inteiro a partir de espécies patogênicas.')}
  ${q('7','Fungos','Fungos são:',[['a','plantas sem clorofila'],['b','eucariontes heterótrofos por absorção'],['c','bactérias grandes']],'b','Correto. Formam um grupo evolutivo distinto das plantas.','A ausência de clorofila não os transforma em plantas.')}
  ${q('8','Antibiótico','Por que antibiótico não trata gripe viral?',[['a','porque vírus não possuem os alvos bacterianos sobre os quais antibióticos atuam'],['b','porque todo antibiótico é fraco'],['c','porque vírus são fungos']],'a','Correto. O alvo biológico é diferente.','Antibióticos foram desenvolvidos contra estruturas/processos bacterianos específicos.')}
  <div class="challenge-box"><strong>Desafio MbB — uma célula em três níveis</strong><p>Escolha uma célula bacteriana ou eucariótica e explique como ela <strong>1)</strong> controla trocas, <strong>2)</strong> obtém energia e <strong>3)</strong> mantém informação genética. Mostre como essas funções se conectam.</p><details><summary>Critério para conferir</summary><p>A resposta deve relacionar membrana, metabolismo/ATP, DNA e síntese de proteínas, evitando uma lista de estruturas desconectadas.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT202:</strong> organização procariótica/eucariótica, membrana e transportes, bactérias, fungos, aplicações e relações entre estrutura celular e funcionamento.</p></details>`;
  const cases={salt:['Osmose','Em meio mais concentrado em solutos efetivos, a célula tende a perder água; a resposta depende também de parede celular e permeabilidades.'],antibiotic:['Alvo errado','Gripe é viral; antibiótico não age sobre vírus e seu uso inadequado favorece resistência bacteriana.'],yeast:['Fungo + fermentação','Leveduras são fungos unicelulares que podem fermentar açúcares, produzindo CO₂ usado na panificação.']};
  function init(root){const r=root.querySelector('#bio08Result');root.querySelectorAll('#bio08Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Células e diversidade',technical:'Células • membrana, transportes, procariontes, bactérias e fungos',title:'O que uma célula precisa para continuar viva?',objective:'<strong>Objetivo:</strong> compreender princípios da teoria celular, comparar procariontes e eucariontes, interpretar transportes de membrana e reconhecer a diversidade e importância de bactérias e fungos.',html:lessonHtml,init});}
  MBB.enableChapter('08 Células, bactérias e fungos',show);
})();