(() => {
  'use strict';
  const MBB=window.MBBBiologia=window.MBBBiologia||{};const q=MBB.choice;
  const lessonHtml=`
  <section class="biology-opening"><span class="lesson-kicker">Uma situação real para investigar</span><div class="hero-box biology-story"><strong class="card-title">Em um hospital, uma bactéria que antes era controlada por um antibiótico passa a aparecer com mais frequência entre as amostras resistentes. Alguém diz: “As bactérias aprenderam a resistir porque precisavam sobreviver”.</strong><p>A frase atribui intenção ao processo. Populações bacterianas podem conter variações herdáveis antes da exposição; o antibiótico altera quais variantes deixam mais descendentes. Ao longo das gerações, a frequência das variantes resistentes pode aumentar.</p>${q('A','Seleção natural','Qual explicação é mais adequada?',[['a','cada bactéria decide desenvolver resistência'],['b','variantes resistentes sobrevivem/reproduzem-se relativamente mais e sua frequência pode aumentar na população'],['c','o antibiótico cria exatamente a mutação necessária em todos os indivíduos']],'b','Correto. Seleção atua sobre variação herdável existente ou surgida ao acaso em relação à necessidade.','Evolução não exige intenção nem uma mutação dirigida pela necessidade.')}
  <p class="central-question"><strong>Nossa missão:</strong> compreender como <strong>variação, hereditariedade, seleção, ancestralidade e tempo</strong> explicam mudanças nas populações e a diversidade da vida.</p></div></section>

  <section><h3>1. Indivíduos nascem e morrem; populações evoluem</h3><p>Evolução biológica é mudança nas características herdáveis de populações ao longo das gerações. Um indivíduo pode crescer, aprender ou aclimatar-se, mas isso não significa que ele “evoluiu” geneticamente durante a própria vida.</p><div class="concept-flow"><div><strong>Variação</strong><span>indivíduos diferem</span></div><div class="flow-arrow">+</div><div><strong>Hereditariedade</strong><span>parte das diferenças é transmissível</span></div><div class="flow-arrow">→</div><div><strong>Sucesso reprodutivo diferencial</strong><span>frequências mudam</span></div></div></section>

  <section><h3>2. Lamarck ajudou a tornar a transformação das espécies uma questão científica</h3><p>Jean-Baptiste Lamarck defendeu que espécies não eram fixas e propôs mecanismos como uso e desuso e herança de caracteres adquiridos. Seu mecanismo de herança não explica, em geral, a evolução como entendemos hoje, mas historicamente foi importante por tratar transformação das espécies de modo sistemático.</p><div class="note-box"><strong>Evite a caricatura</strong><p>Lamarck não deve aparecer apenas como “o cientista errado da girafa”. A História da Ciência é mais útil quando perguntamos qual problema estava sendo enfrentado e por que novos dados exigiram mecanismos melhores.</p></div></section>

  <section><h3>3. Darwin e Wallace propuseram seleção natural</h3><p>Charles Darwin e Alfred Russel Wallace chegaram independentemente à ideia de seleção natural. Se indivíduos variam, parte dessa variação é herdável e há diferenças no sucesso reprodutivo, certas características podem tornar-se mais frequentes.</p><p><strong>Adaptação</strong> não é uma escolha consciente nem uma perfeição absoluta. É uma característica herdável que, em determinado contexto, contribui para maior sucesso reprodutivo relativo.</p>${q('B','Adaptação','Uma característica adaptativa é:',[['a','uma característica perfeita para qualquer ambiente'],['b','uma característica herdável associada a vantagem reprodutiva em determinado contexto'],['c','algo que o indivíduo desenvolve porque deseja']],'b','Correto. Vantagem é contextual e relativa.','Ambientes mudam; não existe adaptação universal perfeita.')}</section>

  <section><h3>4. Seleção natural não é o único mecanismo evolutivo</h3><p>Mutação cria novas variantes; recombinação reorganiza variantes; migração pode transferir alelos entre populações; deriva genética altera frequências por efeitos amostrais, especialmente em populações pequenas. Seleção natural é um mecanismo importante, mas não explica toda mudança evolutiva.</p><div class="four-col"><div class="example-box"><strong class="card-title">Mutação</strong><p>fonte de novas variantes</p></div><div class="example-box"><strong class="card-title">Fluxo gênico</strong><p>movimento de alelos entre populações</p></div><div class="example-box"><strong class="card-title">Deriva</strong><p>mudanças aleatórias de frequência</p></div><div class="example-box"><strong class="card-title">Seleção</strong><p>diferenças não aleatórias de sucesso reprodutivo</p></div></div></section>

  <section><h3>5. Evidências evolutivas vêm de fontes independentes</h3><div class="table-wrap"><table><thead><tr><th>Evidência</th><th>O que permite investigar</th></tr></thead><tbody><tr><td>Fósseis</td><td>formas antigas, mudanças e extinções em contexto temporal</td></tr><tr><td>Biogeografia</td><td>distribuição de espécies em continentes e ilhas</td></tr><tr><td>Homologias</td><td>estruturas herdadas de ancestrais comuns, modificadas para funções diferentes</td></tr><tr><td>DNA/proteínas</td><td>graus de semelhança molecular e relações de ancestralidade</td></tr><tr><td>Evolução observada</td><td>mudanças mensuráveis em populações atuais, como resistência</td></tr></tbody></table></div><div class="ok-box"><strong>Força da convergência</strong><p>A explicação evolutiva é fortalecida quando fósseis, anatomia, embriologia, biogeografia e dados moleculares apontam para relações compatíveis.</p></div></section>

  <section><h3>6. Homologia e analogia não são a mesma coisa</h3><p>Estruturas <strong>homólogas</strong> compartilham origem evolutiva, embora possam ter funções diferentes. Estruturas <strong>análogas</strong> têm funções semelhantes que evoluíram independentemente, frequentemente por <strong>convergência evolutiva</strong>.</p><div class="two-col"><div class="example-box"><strong class="card-title">Homologia</strong><p>membro anterior humano, asa de morcego e nadadeira de baleia compartilham um padrão ósseo herdado de ancestral tetrápode.</p></div><div class="example-box"><strong class="card-title">Analogia funcional</strong><p>asa de inseto e asa de ave produzem voo, mas surgiram de estruturas ancestrais diferentes.</p></div></div></section>

  <section><h3>7. Árvores filogenéticas mostram parentesco por ancestralidade comum</h3><p>Uma árvore filogenética não é uma escada de “seres inferiores para superiores”. Nós internos representam ancestrais comuns inferidos; espécies atuais aparecem nas pontas e nenhuma espécie atual precisa ser ancestral de outra atual.</p><div class="visual-box"><strong class="card-title">Leia pelos ramos, não pela posição esquerda/direita</strong><svg class="lesson-visual" viewBox="0 0 760 310" role="img" aria-label="Árvore filogenética simples com ancestral comum e quatro espécies nas pontas."><line x1="120" y1="260" x2="120" y2="80" stroke="#2f7d32" stroke-width="4"/><line x1="120" y1="220" x2="320" y2="220" stroke="#2f7d32" stroke-width="4"/><line x1="320" y1="220" x2="320" y2="160" stroke="#2f7d32" stroke-width="4"/><line x1="320" y1="160" x2="520" y2="160" stroke="#2f7d32" stroke-width="4"/><line x1="520" y1="160" x2="520" y2="105" stroke="#2f7d32" stroke-width="4"/><line x1="520" y1="105" x2="680" y2="105" stroke="#2f7d32" stroke-width="4"/><line x1="520" y1="160" x2="680" y2="205" stroke="#2f7d32" stroke-width="4"/><line x1="320" y1="220" x2="680" y2="260" stroke="#2f7d32" stroke-width="4"/><text x="685" y="110" font-weight="900">A</text><text x="685" y="210" font-weight="900">B</text><text x="685" y="267" font-weight="900">C</text><text x="105" y="75" font-size="13">ancestrais comuns</text><circle cx="520" cy="160" r="7" fill="#6d4aff"/><circle cx="320" cy="220" r="7" fill="#6d4aff"/></svg><p class="visual-caption">A e B compartilham ancestral comum mais recente entre si do que com C.</p></div>${q('C','Árvore','Se A e B compartilham um ancestral comum mais recente entre si que com C, então:',[['a','A é ancestral atual de B'],['b','A e B são mais aparentados entre si nessa árvore'],['c','C é menos evoluído']],'b','Correto. Parentesco é inferido pela recência do ancestral comum.','Pontas atuais são parentes; posição não mede “grau de evolução”.')}</section>

  <section><h3>8. Radiação adaptativa e convergência produzem padrões diferentes</h3><p>Na <strong>radiação adaptativa</strong>, uma linhagem ancestral diversifica-se em várias linhagens associadas a nichos distintos. Na <strong>convergência</strong>, linhagens distantes desenvolvem características semelhantes sob pressões seletivas semelhantes.</p><div class="comparison-grid"><div class="example-box"><strong class="card-title">Radiação</strong><p>um ancestral → várias linhagens e nichos</p></div><div class="example-box"><strong class="card-title">Convergência</strong><p>linhagens distantes → soluções funcionais semelhantes</p></div></div></section>

  <section><h3>9. A endossimbiose explica a origem de mitocôndrias e cloroplastos</h3><p>A teoria endossimbiótica propõe que ancestrais de mitocôndrias e cloroplastos eram bactérias incorporadas por outra célula, estabelecendo uma relação que se tornou permanente ao longo da evolução.</p><p>Evidências incluem DNA próprio, ribossomos semelhantes aos bacterianos, divisão por processo parecido com fissão e dupla membrana. Isso não significa que organelas atuais sejam bactérias independentes: houve longa integração evolutiva e transferência de genes.</p></section>

  <section><h3>10. Evolução humana é uma árvore ramificada, não uma fila do “macaco ao homem”</h3><p>Humanos e outros primatas atuais compartilham ancestrais comuns. Humanos <strong>não descendem dos macacos atuais</strong>. A linhagem humana inclui várias espécies de hominínios e episódios de coexistência e cruzamento entre algumas linhagens.</p><div class="note-box"><strong>“Mais evoluído” é uma expressão enganosa</strong><p>Todas as espécies atuais possuem histórias evolutivas igualmente longas desde seus ancestrais comuns. Complexidade, tamanho cerebral ou tecnologia não formam uma escala universal de valor biológico.</p></div></section>

  <section><h3>11. Investigador evolutivo</h3><div class="interactive-lab" id="bio07Lab"><div class="lab-heading"><h4>Qual mecanismo ou evidência aparece?</h4></div><div class="choice-row"><button type="button" data-case="antibiotic">Resistência bacteriana</button><button type="button" data-case="island">Aves de ilhas</button><button type="button" data-case="wing">Asas semelhantes</button></div><div class="lab-result" id="bio07Result"><strong>Escolha um caso.</strong><span>A análise aparecerá aqui.</span></div></div></section>

  <section class="chapter-checkpoint"><span class="lesson-kicker">Checkpoint</span><h3>12. Você consegue explicar evolução sem intenção ou escada?</h3>
  ${q('1','Unidade da evolução','Quem evolui ao longo das gerações?',[['a','populações'],['b','um indivíduo porque se esforça'],['c','somente espécies extintas']],'a','Correto. Mudam frequências de características herdáveis nas populações.','Indivíduos desenvolvem-se; populações evoluem.')}
  ${q('2','Seleção','Seleção natural exige:',[['a','variação herdável e diferenças no sucesso reprodutivo'],['b','intenção consciente'],['c','mutações sempre benéficas']],'a','Correto. O ambiente não precisa “criar” a variante necessária.','Seleção atua sobre variação; não planeja resultados.')}
  ${q('3','Mutação','Mutações surgem:',[['a','em relação às necessidades futuras do organismo'],['b','sem direção para produzir exatamente a adaptação necessária'],['c','apenas quando um antibiótico está presente']],'b','Correto. A ocorrência de mutações não é guiada pela necessidade adaptativa.','O ambiente seleciona efeitos; não ordena mutações específicas.')}
  ${q('4','Deriva','Deriva genética é:',[['a','mudança de frequências por efeitos aleatórios de amostragem'],['b','sempre adaptação'],['c','migração planejada']],'a','Correto. Pode ser intensa em populações pequenas.','Nem toda mudança evolutiva é seleção.')}
  ${q('5','Homologia','Estruturas homólogas indicam principalmente:',[['a','origem evolutiva compartilhada'],['b','função necessariamente idêntica'],['c','ausência de ancestral comum']],'a','Correto. A função pode divergir.','Homologia é definida pela origem, não pela função.')}
  ${q('6','Filogenia','Uma árvore filogenética deve ser lida como:',[['a','hierarquia de valor'],['b','hipótese de relações de ancestralidade'],['c','fila temporal com humanos no topo']],'b','Correto. Ramos representam parentesco.','Não existe “topo evolutivo” obrigatório.')}
  ${q('7','Endossimbiose','Qual evidência apoia a origem bacteriana de mitocôndrias?',[['a','DNA próprio e divisão semelhante à fissão'],['b','ausência de membrana'],['c','capacidade de sair da célula humana e viver livremente']],'a','Correto. Várias características convergem para origem endossimbiótica.','Organelas atuais são integradas à célula e não são bactérias independentes.')}
  ${q('8','Humana','Humanos descendem dos chimpanzés atuais?',[['a','sim'],['b','não; humanos e chimpanzés atuais compartilham ancestrais comuns'],['c','não há parentesco']],'b','Correto. São linhagens irmãs em relação a ancestrais comuns recentes.','Parentesco não significa descendência direta de uma espécie atual.')}
  <div class="challenge-box"><strong>Desafio MbB — resistência sem intenção</strong><p>Explique por que usar a frase “as bactérias ficaram resistentes porque precisavam” é inadequado. Inclua variação, hereditariedade, seleção e mudança de frequência na população.</p><details><summary>Critério para conferir</summary><p>Uma boa resposta explica que variantes podem existir ou surgir sem direção adaptativa; o antibiótico muda o sucesso relativo, e descendentes de variantes resistentes passam a representar maior fração da população.</p></details></div></section>
  <details class="curriculum-box"><summary>Conexão com o currículo</summary><p><strong>EM13CNT201 e EM13CNT208:</strong> Lamarck, Darwin/Wallace, seleção natural, evidências evolutivas, filogenia, convergência, radiação adaptativa, endossimbiose e evolução humana.</p></details>`;
  const cases={antibiotic:['Seleção natural','O antibiótico altera o sucesso relativo de variantes herdáveis; resistência pode aumentar em frequência.'],island:['Biogeografia/radiação','Isolamento e nichos diferentes podem produzir diversificação de linhagens aparentadas ao longo do tempo.'],wing:['Compare homologia e analogia','Função semelhante não garante mesma origem. É preciso analisar estrutura, desenvolvimento e ancestralidade.']};
  function init(root){const r=root.querySelector('#bio07Result');root.querySelectorAll('#bio07Lab [data-case]').forEach(b=>b.addEventListener('click',()=>{const[t,x]=cases[b.dataset.case];r.innerHTML=`<strong>${t}</strong><span>${x}</span>`;}));}
  function show(){MBB.showLesson({unit:'Origem e evolução',technical:'Evolução • seleção, evidências, filogenia e ancestralidade',title:'Como sabemos que populações mudam ao longo das gerações?',objective:'<strong>Objetivo:</strong> compreender mecanismos evolutivos e evidências de ancestralidade, interpretando seleção natural, homologia, filogenias, convergência, radiação adaptativa, endossimbiose e evolução humana.',html:lessonHtml,init});}
  MBB.enableChapter('07 Evolução e ancestralidade',show);
})();
