window.infraestruturaLinuxLessons = Array.isArray(window.infraestruturaLinuxLessons) ? window.infraestruturaLinuxLessons : [];

window.infraestruturaLinuxLessons.push({
  id: 'linux-nginx',
  number: '08',
  unit: 'Servidor da escola · Publicar primeiro, expor depois',
  menuTitle: 'Serviço Web com Nginx',
  technicalTitle: 'Nginx • processo • porta • arquivo • permissão • teste local • nome • log',
  title: 'Como provar que a homologação funciona sem trocar a intranet no escuro?',
  objective: 'Implantar uma página estática de homologação com Nginx, validar processo, configuração, porta, arquivo e resposta local antes de liberar origens de rede.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Mudança 022 · homologação da intranet</span><h2>A matriz de serviços da rede registra o endpoint existente; a coordenação não aceita uma troca sem comparação.</h2><p>A nova página contém apenas avisos fictícios. O nome <strong>intranet.escolahorizonte.example</strong> e o endereço didático <strong>192.168.10.20</strong> serão preservados, mas não há corte de produção nesta homologação. SRV-01 primeiro precisa responder localmente; depois a equipe documentará quem pode alcançá-lo.</p></div>
    <div class="note-box"><strong>Escolha consciente</strong><p><strong>Nginx</strong> atende à página estática com pacote mantido nos repositórios do Ubuntu e configuração pequena o suficiente para o laboratório. Não é declarado “melhor servidor Web”; é a opção proporcional a esta função.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Camadas da evidência</span><h3>Uma tela no navegador é o último elo, não o primeiro</h3></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="diagnostic-flow"><div><strong>Processo</strong><span>Nginx executa?</span></div><div><strong>Configuração</strong><span>teste aceita?</span></div><div><strong>Porta</strong><span>há escuta local?</span></div><div><strong>Conteúdo</strong><span>arquivo pode ser lido?</span></div><div><strong>HTTP</strong><span>resposta é a esperada?</span></div></div><p class="visual-question"><strong>Preveja:</strong> se <code>curl</code> local responde, mas o cliente não, quais camadas externas ainda faltam verificar?</p></div></div>

    <h3>Construir e validar sem exposição</h3>
    <div class="task-box"><strong>Missão 08 · versão de homologação</strong><ol><li>registre a instalação na seção de mudanças e atualizações: <code>sudo apt update</code> e <code>sudo apt install nginx</code>;</li><li>observe <code>systemctl status nginx --no-pager</code>, <code>ss -ltn</code> e os logs antes de editar;</li><li>crie <code>/var/www/intranet</code> com proprietário, grupo e modo planejados na matriz de identidades e permissões; publique apenas o arquivo fictício aprovado;</li><li>crie <code>/etc/nginx/sites-available/intranet</code> com <code>server_name intranet.escolahorizonte.example</code> e raiz nessa pasta; habilite-o por link em <code>sites-enabled</code> sem remover a configuração anterior antes da validação;</li><li>antes de recarregar, execute <code>sudo nginx -t</code>; saída inválida interrompe a mudança;</li><li>recarregue somente após o teste e confira <code>curl -I -H 'Host: intranet.escolahorizonte.example' http://127.0.0.1</code>;</li><li>confira código HTTP, cabeçalhos, conteúdo, access log e error log no mesmo horário;</li><li>não altere DNS nem firewall ainda; documente o retorno para a configuração anterior.</li></ol></div>

    <div class="terminal-card"><strong>Bloco didático representativo — revise caminhos no laboratório</strong><pre>server {&#10;    listen 80;&#10;    server_name intranet.escolahorizonte.example;&#10;    root /var/www/intranet;&#10;    index index.html;&#10;&#10;    location / {&#10;        try_files $uri $uri/ =404;&#10;    }&#10;}</pre><p>Uma configuração aceita por <code>nginx -t</code> ainda precisa de teste funcional. <code>.example</code> identifica somente o cenário controlado; não é nome público real.</p></div>

    <div class="evidence-switcher" data-evidence-switcher><p><strong>Compare o estágio da evidência:</strong></p><div class="switcher-buttons"><button type="button" data-evidence-view="proc" aria-pressed="true">Processo</button><button type="button" data-evidence-view="local" aria-pressed="false">Local</button><button type="button" data-evidence-view="remote" aria-pressed="false">Remoto</button></div><div class="evidence-panel" data-evidence-panel="proc"><h4><code>active (running)</code></h4><p>Mostra que o serviço executa agora; não confirma virtual host, arquivo nem origem remota.</p></div><div class="evidence-panel" data-evidence-panel="local" hidden><h4><code>HTTP/1.1 200 OK</code> no loopback</h4><p>Confirma resposta local ao nome enviado no cabeçalho. Não prova DNS ou firewall.</p></div><div class="evidence-panel" data-evidence-panel="remote" hidden><h4>Ainda não testado</h4><p>Esse vazio é intencional: exposição será decidida pela matriz de fluxos, não por pressa.</p></div></div>
    <div class="danger-box compact"><strong>HTTP de laboratório não transporta credenciais ou dados reais.</strong><p>A matriz de serviços da rede registra HTTPS como requisito do endpoint existente. Esta homologação não deve substituí-lo até haver decisão de TLS e confiança adequada; não ignore aviso de certificado.</p></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>Nginx ausente; endpoint existente preservado</span></div><div class="state-step"><strong>Intervenção</strong><span>site fictício e configuração testada</span></div><div class="state-step"><strong>Depois</strong><span>200 local, log e conteúdo conferidos</span></div><div class="state-step"><strong>O que prova?</strong><span>homologação local funciona; não está liberada aos usuários</span></div></div>
    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="b" data-explanation="Teste local bem-sucedido isola parte do servidor; caminho, DNS e firewall ainda podem impedir o cliente."><p>O <code>curl</code> local retorna 200. A intranet está entregue?</p><label><input type="radio" name="l08a" value="a"> sim, todo cliente necessariamente acessa</label><label><input type="radio" name="l08a" value="b"> não; ainda faltam política, teste remoto, TLS e corte controlado</label><label><input type="radio" name="l08a" value="c"> sim, porque Nginx está instalado</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Serviço Web</strong><p>Proprietário da função, nome, IP, porta, pacote, arquivos, permissões, teste de configuração, processo, escuta, resposta local, logs, conteúdo permitido, retorno, TLS pendente e critério de corte. Esse registro orientará firewall e backup.</p></div>
    <div class="bridge-box"><strong>Outra necessidade chega antes do corte</strong><p>Ana e Caio ainda trocam arquivos por mídia. A coordenação aprova um compartilhamento Samba apenas no laboratório. Agora existem portas de administração, Web e arquivos; o UFW precisa expressar os fluxos mínimos sem bloquear Joana.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://ubuntu.com/server/docs/how-to/web-services/install-nginx/" target="_blank" rel="noopener noreferrer">Ubuntu Server — instalar e verificar Nginx</a></li><li><a href="https://ubuntu.com/server/docs/how-to/web-services/configure-nginx/" target="_blank" rel="noopener noreferrer">Ubuntu Server — configurar Nginx</a></li></ul></details>
  `
});

window.infraestruturaLinuxLessons.push({
  id: 'linux-samba-ufw',
  number: '09',
  unit: 'Servidor da escola · Oferecer somente o fluxo necessário',
  menuTitle: 'Samba e UFW',
  technicalTitle: 'Samba • compartilhamento • identidade dupla • porta • origem • UFW • teste permitido/negado',
  title: 'Quem precisa dos arquivos — e de qual rede?',
  objective: 'Publicar um compartilhamento Samba com controle de identidade e filesystem, então aplicar regras UFW mínimas a SSH, Web e arquivos com testes positivos e negativos.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Solicitação 023 · arquivos de trabalho</span><h2>Ana precisa modificar documentos; Caio não deve sequer listar a pasta da secretaria.</h2><p>O registro de identidades e permissões define quem pode usar cada recurso. O registro de armazenamento localiza os dados em <code>/srv/escola</code>. O registro de rede separa as origens: funcionários e laboratório não têm a mesma necessidade. O servidor Web responde localmente, SSH funciona de ADM-01 e nenhum fluxo deve ser aberto “para qualquer lugar”.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Serviço, porta e origem</span><h3>UFW filtra fluxo; Samba e Linux decidem o acesso ao recurso</h3></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="service-stack"><div><strong>Origem</strong><span>funcionário, laboratório ou visitante</span></div><div class="blocked"><strong>UFW</strong><span>porta/origem necessária?</span></div><div><strong>Samba</strong><span>autentica e aplica share</span></div><div><strong>Filesystem</strong><span>grupo e permissão efetiva</span></div></div><p class="visual-question"><strong>Decida:</strong> regra de firewall liberada prova que Ana consegue gravar? Login Samba bem-sucedido ignora permissões Linux?</p></div></div>

    <h3>O compartilhamento nasce das identidades e permissões</h3>
    <div class="task-box"><strong>Missão 09A · Samba sem convidado</strong><ol><li>instale <code>samba</code> por APT e preserve uma cópia controlada de <code>/etc/samba/smb.conf</code>;</li><li>crie a seção <strong>Secretaria</strong> apontando para <code>/srv/escola/documentos</code>, sem <code>guest ok</code>;</li><li>permita somente o grupo <code>secretaria</code>; mantenha leitura por padrão e escrita apenas para o grupo aprovado;</li><li>lembre que usuários de controle do Samba precisam existir como identidades Linux e Samba; adicione a credencial de laboratório sem registrar senha;</li><li>execute <code>sudo testparm -s</code> antes de recarregar o serviço;</li><li>teste de SEC-02 como Ana: listar, criar, editar e excluir arquivo fictício;</li><li>teste do laboratório como Caio: o acesso à secretaria deve ser negado;</li><li>se o resultado divergir, compare share, identidade, grupo e filesystem antes de ampliar permissões.</li></ol></div>

    <div class="terminal-card"><strong>Trecho didático representativo de <code>smb.conf</code></strong><pre>[Secretaria]&#10;    path = /srv/escola/documentos&#10;    browseable = yes&#10;    read only = yes&#10;    valid users = @secretaria&#10;    write list = @secretaria&#10;    create mask = 0660&#10;    directory mask = 2770</pre><p>Valide com <code>testparm -s</code>. A regra do compartilhamento e a permissão Linux devem concordar; não use <code>777</code> para mascarar divergência.</p></div>

    <h3>O firewall começa como matriz de fluxos, não como <code>ufw enable</code></h3>
    <div class="table-wrap"><table><thead><tr><th>Origem</th><th>Função</th><th>Destino</th><th>Decisão do laboratório</th><th>Teste</th></tr></thead><tbody><tr><td>ADM-01 · 192.168.10.30</td><td>SSH TCP 22</td><td>SRV-01</td><td>permitir somente essa origem</td><td>nova sessão + log</td></tr><tr><td>Funcionários · /26</td><td>Web TCP 80</td><td>homologação</td><td>permitir durante teste</td><td>HTTP + access log</td></tr><tr><td>Laboratório · 192.168.10.64/26</td><td>Web TCP 80</td><td>homologação</td><td>permitir durante teste</td><td>função fictícia</td></tr><tr><td>Funcionários · /26</td><td>Samba</td><td>Secretaria</td><td>permitir; identidade ainda decide</td><td>Ana permitida</td></tr><tr><td>Visitantes · /26</td><td>SSH/Web/Samba</td><td>SRV-01</td><td>não permitir</td><td>conexão negada/sem resposta conforme política</td></tr></tbody></table></div>

    <div class="task-box"><strong>Missão 09B · aplicar sem perder administração</strong><ol><li>registre <code>sudo ufw status verbose</code> e confirme o console e o plano de recuperação do acesso remoto;</li><li>revise perfis com <code>sudo ufw app list</code> e <code>sudo ufw app info Samba</code>;</li><li>simule cada regra com <code>sudo ufw --dry-run ...</code> e confira origem, destino, porta/protocolo;</li><li>adicione primeiro a regra SSH de ADM-01; só depois as regras Web e Samba aprovadas;</li><li>revise <code>sudo ufw status numbered</code> antes de habilitar;</li><li>com console e sessão SSH preservados, habilite o UFW na janela didática;</li><li>abra nova sessão SSH e teste Web/Samba de origens permitidas e de uma origem visitante controlada;</li><li>registre permitido e negado. Se perder administração, use o console e o plano de retorno; não continue às cegas.</li></ol></div>
    <div class="terminal-card warn"><strong>Exemplos para revisar antes de aplicar</strong><pre>sudo ufw --dry-run allow proto tcp from 192.168.10.30 to any port 22&#10;sudo ufw --dry-run allow proto tcp from 192.168.10.0/26 to any port 80&#10;sudo ufw --dry-run allow from 192.168.10.0/26 to any app Samba</pre><p>A simulação mostra regras resultantes; não prova que a política está completa nem que o serviço funciona. Adapte somente ao plano real da rede didática.</p></div>
    <div class="danger-box"><strong>Firewall não é segurança total</strong><p>UFW é controle no host. Atualização, autenticação, permissões, logs, segmentação, proteção do conteúdo e recuperação continuam necessários. Não exponha este laboratório à Internet.</p></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>serviços sem política no host</span></div><div class="state-step"><strong>Intervenção</strong><span>regras mínimas revisadas e habilitadas</span></div><div class="state-step"><strong>Depois</strong><span>fluxos permitidos funcionam; visitante falha</span></div><div class="state-step"><strong>O que prova?</strong><span>regras controlaram os fluxos testados; não segurança total</span></div></div>
    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="c" data-explanation="A regra SSH deve existir e ser revisada antes da ativação; uma sessão e o console preservam recuperação."><p>Qual condição vem antes de habilitar UFW remotamente?</p><label><input type="radio" name="l09a" value="a"> fechar a sessão atual</label><label><input type="radio" name="l09a" value="b"> permitir todas as portas</label><label><input type="radio" name="l09a" value="c"> confirmar regra SSH, console e método de retorno</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Serviços e firewall</strong><p>Reutiliza identidades e permissões, rede, acesso remoto e serviço Web; registra serviço, dono, pacote, protocolo/porta, origem, regra, simulação, teste permitido, teste negado, log e rollback. Ela define o que deve ser monitorado e recuperado.</p></div>
    <div class="bridge-box"><strong>Agora existe algo valioso para perder</strong><p>Há dados, configuração Web, compartilhamento, identidade de acesso e regras. Às 17h, mapa de armazenamento mostra o volume crescendo e ninguém consegue apresentar uma restauração. A continuidade precisa ser testada antes da entrega.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://ubuntu.com/server/docs/how-to/samba/file-server/" target="_blank" rel="noopener noreferrer">Ubuntu Server — Samba como servidor de arquivos</a></li><li><a href="https://ubuntu.com/server/docs/how-to/samba/share-access-controls/" target="_blank" rel="noopener noreferrer">Ubuntu Server — controles de acesso do Samba</a></li><li><a href="https://ubuntu.com/server/docs/how-to/security/firewalls/" target="_blank" rel="noopener noreferrer">Ubuntu Server — UFW, origem específica e dry-run</a></li></ul></details>
  `
});

window.infraestruturaLinuxLessons.push({
  id: 'linux-backup-monitoramento',
  number: '10',
  unit: 'Servidor da escola · Provar continuidade',
  menuTitle: 'Backup e troubleshooting',
  technicalTitle: 'escopo • cópia • restauração • atualização • espaço • falha • baseline • conclusão limitada',
  title: 'A cópia existe. Como saber se a escola consegue voltar?',
  objective: 'Definir escopo de backup, restaurar amostra em local separado, observar saúde básica e integrar troubleshooting sem apagar evidências ou instalar plataforma desproporcional.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Revisão de continuidade · SRV-01</span><h2>Há um arquivo <code>.tgz</code> no destino, mas ninguém restaurou nada.</h2><p>o registro de armazenamento identifica os dados; o registro do serviço Web, a configuração Web; o registro de serviços e firewall, Samba e firewall. A coordenação pergunta quanto perderia e em quanto tempo voltaria. No mesmo plantão, o volume chega a 84% e o journal mostra avisos repetidos. Apagar logs ou declarar “backup concluído” não responde nenhuma das duas questões.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Ciclo de continuidade</span><h3>Cópia sem retorno testado é apenas uma hipótese</h3></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="service-stack"><div><strong>Escopo</strong><span>dados + configurações</span></div><div><strong>Cópia</strong><span>destino separado e restrito</span></div><div><strong>Restauração</strong><span>local isolado</span></div><div><strong>Validação</strong><span>conteúdo + função</span></div></div><p class="visual-question"><strong>Decida:</strong> restaurar sobre o único arquivo válido mede recuperação ou cria outro risco? Que função deve ser testada depois de recuperar a configuração?</p></div></div>

    <h3>Política proporcional</h3>
    <div class="table-wrap"><table><thead><tr><th>Item</th><th>Por que entra</th><th>Frequência de teste</th><th>Restauração segura</th></tr></thead><tbody><tr><td><code>/srv/escola</code></td><td>documentos e materiais fictícios</td><td>cópia diária no cenário</td><td>amostra em diretório separado</td></tr><tr><td><code>/etc/nginx</code> + conteúdo</td><td>reconstruir homologação</td><td>após mudança e rotina</td><td>VM isolada ou caminho de teste</td></tr><tr><td><code>/etc/samba</code></td><td>recuperar compartilhamentos</td><td>após mudança e rotina</td><td>validar com <code>testparm</code> antes de ativar</td></tr><tr><td>Netplan/SSH/UFW</td><td>recuperar administração e exposição</td><td>após mudança</td><td>console, revisão e aplicação controlada</td></tr></tbody></table></div>
    <div class="danger-box compact"><strong>Destino separado e acesso restrito</strong><p>Backup no mesmo volume não protege contra perda do volume. Configurações podem conter informações sensíveis; não publique arquivos, credenciais ou chaves. Nunca teste restauração sobre os únicos dados válidos.</p></div>

    <div class="terminal-card"><strong>Ação planejada: criar a cópia no destino separado já confirmado</strong><pre>findmnt /mnt/backup&#10;sudo tar -czf /mnt/backup/srv-01-lab.tgz /srv/escola /etc/nginx /etc/samba /etc/netplan /etc/ssh/sshd_config.d /etc/ufw</pre><p>Revise o escopo e o destino antes de executar. A cópia contém configurações sensíveis e deve ter acesso restrito.</p></div>
    <div class="terminal-grid"><div class="terminal-card"><strong>Pergunta: o que o arquivo contém?</strong><pre>sudo tar -tzf /mnt/backup/srv-01-lab.tgz</pre><p>Listar é uma verificação inicial, não a melhor prova.</p></div><div class="terminal-card"><strong>Pergunta: uma amostra volta?</strong><pre>sudo install -d -m 0700 /srv/restore-test&#10;sudo tar -xzf /mnt/backup/srv-01-lab.tgz -C /srv/restore-test srv/escola/documentos/amostra.txt</pre><p>Restaure em local separado e compare conteúdo/permissões.</p></div><div class="terminal-card"><strong>Pergunta: a função volta?</strong><pre>sudo testparm -s&#10;sudo nginx -t</pre><p>Em cenário isolado, valide configuração restaurada antes de substituir estado ativo.</p></div></div>

    <h3>Monitoramento básico responde perguntas simples</h3>
    <div class="command-board"><div class="command-card"><strong><code>systemctl --failed</code></strong><span>Que unidades estão em falha agora?</span><small>Lista vazia não prova saúde da aplicação.</small></div><div class="command-card"><strong><code>df -hT</code> e <code>du -xhd1</code></strong><span>Qual filesystem enche e que árvore participa?</span><small>Não apague antes de identificar dono e retenção.</small></div><div class="command-card"><strong><code>journalctl -p warning --since today</code></strong><span>Que avisos coincidem com o período?</span><small>Severidade isolada não prova causa.</small></div><div class="command-card"><strong><code>apt list --upgradable</code></strong><span>Que manutenção está pendente?</span><small>Atualizar exige janela e validação.</small></div><div class="command-card"><strong><code>systemctl is-active nginx smbd ssh</code></strong><span>Os serviços esperados executam?</span><small>Ativo não valida a função do cliente.</small></div><div class="command-card"><strong><code>journalctl --disk-usage</code></strong><span>Quanto espaço o journal usa?</span><small>Não autoriza apagar evidência.</small></div></div>

    <div class="evidence-switcher" data-evidence-switcher><p><strong>Incidente 052 · escolha o próximo teste:</strong></p><div class="switcher-buttons"><button type="button" data-evidence-view="sintoma" aria-pressed="true">Sintoma</button><button type="button" data-evidence-view="espaco" aria-pressed="false">Espaço</button><button type="button" data-evidence-view="causa" aria-pressed="false">Evidência</button></div><div class="evidence-panel" data-evidence-panel="sintoma"><h4>Samba falha ao criar arquivo</h4><p>Ana lê documentos existentes; gravação retorna “sem espaço”. Web e SSH ainda funcionam. Não reinicie serviços: qual filesystem atende o caminho?</p></div><div class="evidence-panel" data-evidence-panel="espaco" hidden><h4>Saída representativa</h4><pre>df -hT /srv/escola → 100%&#10;du -xhd1 /srv/escola → backup-local 14G</pre><p>A hipótese de volume cheio ganha força. Ainda falta descobrir origem e autorização do diretório.</p></div><div class="evidence-panel" data-evidence-panel="causa" hidden><h4>Comparação com o registro de continuidade e monitoramento</h4><p>Uma cópia foi gravada no próprio volume por engano, fora do destino aprovado. Preserve registro, mova/remova somente com autorização e repita criação, leitura e espaço. O fato de Samba voltar não prova que todos os dados estão íntegros.</p></div></div>

    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>/srv cheio; escrita Samba falha</span></div><div class="state-step"><strong>Intervenção</strong><span>cópia indevida tratada com autorização</span></div><div class="state-step"><strong>Depois</strong><span>espaço e função repetidos</span></div><div class="state-step"><strong>O que prova?</strong><span>falta de espaço participou do sintoma; acompanhar crescimento</span></div></div>
    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="a" data-explanation="A melhor evidência é recuperar em destino separado e validar o conteúdo/função sem sobrescrever o estado válido."><p>Qual teste demonstra melhor que a cópia é utilizável?</p><label><input type="radio" name="l10a" value="a"> restaurar amostra separada e conferir</label><label><input type="radio" name="l10a" value="b"> observar o tamanho do arquivo</label><label><input type="radio" name="l10a" value="c"> confiar na mensagem “concluído”</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Continuidade e monitoramento</strong><p>Escopo, destino, frequência, retenção, responsável, horário, resultado, amostra restaurada, comparação, tempo observado, espaço, serviços, avisos, limiar de ação e pendências. Essa seção e os registros anteriores formam a passagem de plantão.</p></div>
    <div class="essence"><strong>Essência</strong><p>Operar servidor é manter estados observáveis e recuperáveis: <strong>medir, correlacionar, mudar com autorização, restaurar em segurança e declarar apenas o que o teste demonstrou</strong>.</p></div>
    <div class="bridge-box"><strong>Plantão final</strong><p>A implantação didática está documentada. Outra equipe receberá SRV-01, serviços, logs, backup e uma ou mais falhas controladas sem saber a causa. O trabalho será pedir evidência, decidir e entregar continuidade.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://ubuntu.com/server/docs/how-to/backups/back-up-using-shell-scripts/" target="_blank" rel="noopener noreferrer">Ubuntu Server — backup com tar e teste de restauração</a></li></ul></details>
  `
});
