window.infraestruturaLinuxLessons = Array.isArray(window.infraestruturaLinuxLessons) ? window.infraestruturaLinuxLessons : [];

window.infraestruturaLinuxLessons.push({
  id: 'linux-diagnostico',
  number: '00',
  unit: 'Servidor da escola · Descobrir a necessidade',
  menuTitle: 'Diagnóstico inicial',
  technicalTitle: 'função • impacto • dados • responsável • privilégio • rede • recuperação',
  title: 'O que precisa deixar de depender de improviso?',
  objective: 'Transformar problemas distribuídos da escola em requisitos verificáveis para um servidor, sem escolher tecnologia antes de compreender pessoas, dados, impacto e recuperação.',
  content: `
    <div class="hero-box story-opening">
      <span class="eyebrow">Segunda-feira · 7h35 · Escola Horizonte</span>
      <h2>A intranet tem endereço, mas ninguém consegue explicar quem a mantém ou como recuperá-la.</h2>
      <p>O prontuário de rede confirma <strong>intranet.escolahorizonte.example</strong> em <strong>192.168.10.20</strong>. O Registro da Rede confirma que esse destino já foi usado em testes, mas não informa onde estão seus arquivos, quem publica avisos nem se existe cópia restaurável. Ana guarda documentos da secretaria em SEC-02; Caio leva materiais em uma mídia removível; Joana recebe pedidos de ambos.</p>
      <p>Quando a estação de Ana ficou indisponível, o atendimento quase parou. Agora a coordenação pede uma solução administrável e recuperável. <strong>Servidor é uma resposta possível; a necessidade vem primeiro.</strong></p>
    </div>

    <section class="checkpoint" data-quiz-group>
      <span class="eyebrow">Triagem de decisões</span><h3>O que precisa ser descoberto antes de instalar?</h3>
      <div class="quiz-item" data-quiz-question data-answer="b" data-explanation="A função, seus usuários, dados, impacto, responsável e recuperação definem a solução e seus controles."><p>1. Qual pergunta tem prioridade?</p><label><input type="radio" name="l00a" value="a"> Qual tema visual terá a tela de login?</label><label><input type="radio" name="l00a" value="b"> Que função será centralizada, quem depende dela e o que acontece quando para?</label><label><input type="radio" name="l00a" value="c"> Quantos comandos cabem no roteiro?</label></div>
      <div class="quiz-item" data-quiz-question data-answer="c" data-explanation="O Registro da Rede confirma nome, IP e testes de comunicação; não comprova propriedade dos dados, administração ou recuperação."><p>2. O Registro da Rede identifica a intranet. O que isso não prova?</p><label><input type="radio" name="l00b" value="a"> Que o nome apareceu no cenário didático.</label><label><input type="radio" name="l00b" value="b"> Que clientes a usaram em testes.</label><label><input type="radio" name="l00b" value="c"> Que seus dados e configurações podem ser restaurados.</label></div>
      <div class="quiz-item" data-quiz-question data-answer="a" data-explanation="Conta compartilhada elimina responsabilização e amplia privilégio; identidades e funções precisam ser planejadas antes."><p>3. “Uma senha de administrador para todos” resolve a continuidade?</p><label><input type="radio" name="l00c" value="a"> Não; cria acesso excessivo e ações sem autoria.</label><label><input type="radio" name="l00c" value="b"> Sim, porque reduz chamados.</label><label><input type="radio" name="l00c" value="c"> Sim, se a senha ficar colada no armário.</label></div>
      <button class="action-button primary" type="button" data-check-quiz>Conferir raciocínio</button><div class="quiz-result" data-quiz-result aria-live="polite"></div>
    </section>

    <h3>Reunir necessidade, impacto e evidência</h3>
    <div class="table-wrap"><table><thead><tr><th>Função observada</th><th>Pessoas</th><th>Evidência atual</th><th>Impacto se parar</th><th>Lacuna</th></tr></thead><tbody>
      <tr><td>Avisos da intranet</td><td>Ana publica; equipe consulta</td><td>Registro da Rede: nome e serviço esperado</td><td>informação desatualizada ou indisponível</td><td>origem, proprietário e recuperação</td></tr>
      <tr><td>Documentos da secretaria</td><td>Ana e coordenação</td><td>arquivos ainda concentrados em SEC-02</td><td>atendimento e matrícula interrompidos</td><td>controle de acesso e cópia central</td></tr>
      <tr><td>Materiais de aula</td><td>Caio e docentes</td><td>mídias e versões dispersas</td><td>aula depende de uma pessoa/dispositivo</td><td>versão, acesso e restauração</td></tr>
      <tr><td>Administração</td><td>Joana e suporte autorizado</td><td>sem responsável formal pelo serviço</td><td>mudanças sem rastreabilidade</td><td>identidade, log e passagem de turno</td></tr>
    </tbody></table></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Diagrama de necessidade</span><h3>O servidor só faz sentido entre dependências e controles</h3><p>Observe quem usa, o que precisa permanecer e quem responde.</p></div><div class="visual-body"><span class="representation-badge">Diagrama próprio · cenário didático controlado</span><div class="service-stack" role="img" aria-label="Pessoas da escola acessam funções centralizadas no futuro servidor, que depende de administração, logs e recuperação"><div><strong>Ana e Caio</strong><span>necessidades reais</span></div><div><strong>Funções</strong><span>intranet e arquivos</span></div><div><strong>SRV-01?</strong><span>ativo a justificar</span></div><div><strong>Controles</strong><span>acesso, log e restauração</span></div></div><p class="visual-question"><strong>Decida antes da solução:</strong> quais funções pertencem ao mesmo ativo? Qual indisponibilidade é aceitável durante o laboratório? Quem autoriza mudanças?</p></div></div>

    <div class="task-box"><strong>Missão 00 · iniciar o Registro do Servidor</strong><p>Registre função, pessoas, dados, frequência de mudança, impacto, tempo tolerável de indisponibilidade, responsável, origens de acesso, privilégio necessário, evidência atual, recuperação esperada e o que permanece fora do escopo. Não escreva “precisa de servidor” como justificativa.</p></div>
    <div class="note-box compact"><strong>Decisão inicial limitada</strong><p>A centralização de uma <strong>homologação da intranet</strong> e de arquivos de laboratório é justificável. A implantação começa isolada: não substitui o serviço existente nem recebe dados pessoais reais. O ativo proposto recebe o ID <strong>SRV-01</strong>; Joana responde pela administração e a coordenação pelos dados.</p></div>
    <div class="essence"><strong>Essência</strong><p>Servidor não é uma máquina “mais forte”. É um ativo que entrega funções a outras pessoas e, por isso, precisa de <strong>responsabilidade, disponibilidade, acesso, observação e recuperação</strong>.</p></div>
    <div class="bridge-box"><strong>A OS 018 é aberta</strong><p>O registro de necessidade autoriza um laboratório de implantação sem dados reais. Antes de criar a VM, a equipe precisa transformar carga, risco e recuperação em CPU, memória, disco, rede e um estado inicial verificável.</p></div>
  `
});

window.infraestruturaLinuxLessons.push({
  id: 'linux-instalacao-vm',
  number: '01',
  unit: 'Servidor da escola · Construir um laboratório recuperável',
  menuTitle: 'VM e instalação',
  technicalTitle: 'VM • CPU • RAM • disco • rede isolada • Ubuntu Server 24.04 LTS • baseline',
  title: 'Que servidor de laboratório atende à função sem fingir produção?',
  objective: 'Dimensionar uma VM pela necessidade, instalar Ubuntu Server 24.04 LTS em ambiente controlado e registrar um baseline que sustente as próximas decisões.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">OS 018 · planejamento do SRV-01</span><h2>A coordenação quer “um servidor”; o host do laboratório tem recursos limitados.</h2><p>O registro de necessidade prevê poucos usuários simultâneos, página estática e documentos de teste. O laboratório precisa permitir erro, console e retorno sem tocar na rede de produção. Aceitar números prontos agora impediria avaliar por que cada recurso existe.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Modelo mental mínimo</span><h3>A VM isola o laboratório; não elimina dependências</h3><p>O host continua fornecendo CPU, memória, disco e rede.</p></div><div class="visual-body"><span class="representation-badge">Diagrama próprio · não aprofunda virtualização</span><div class="service-stack" role="img" aria-label="Computador host fornece recursos ao hipervisor, que executa a máquina virtual SRV-01 conectada à rede isolada do laboratório"><div><strong>Host</strong><span>recursos físicos</span></div><div><strong>Hipervisor</strong><span>isola e controla</span></div><div><strong>VM SRV-01</strong><span>Ubuntu Server</span></div><div><strong>Rede de laboratório</strong><span>sem produção</span></div></div><p class="visual-question"><strong>Preveja:</strong> se a VM consumir toda a RAM do host, quem será afetado? Snapshot substitui backup dos dados?</p></div></div>

    <h3>Critérios antes dos valores</h3>
    <div class="table-wrap"><table><thead><tr><th>Decisão</th><th>Pergunta do registro de necessidade</th><th>Evidência após instalar</th></tr></thead><tbody><tr><td>vCPU</td><td>quantas tarefas simultâneas e qual carga?</td><td><code>lscpu</code> e observação durante testes</td></tr><tr><td>RAM</td><td>quais serviços e quantos usuários?</td><td><code>free -h</code> no estado ocioso e sob carga</td></tr><tr><td>Disco</td><td>sistema, dados, crescimento e recuperação?</td><td><code>lsblk -f</code> e <code>df -hT</code></td></tr><tr><td>Rede</td><td>quem precisa alcançar a VM nesta fase?</td><td><code>ip -br addr</code>, rota e teste de origem autorizada</td></tr><tr><td>Nome</td><td>qual ID já foi aprovado?</td><td><code>hostnamectl</code> mostra <strong>srv-01</strong></td></tr></tbody></table></div>

    <section class="checkpoint compact-check" data-quiz-group><span class="eyebrow">Decisão antes da referência</span><h3>Escolha o projeto mais defensável</h3><div class="quiz-item" data-quiz-question data-answer="b" data-explanation="Os recursos atendem ao laboratório descrito, o disco de dados separado prepara a prática de montagem e a rede isolada evita impacto em produção."><p>Qual proposta melhor corresponde à necessidade registrada?</p><label><input type="radio" name="l01a" value="a"> 16 vCPU, 32 GB e rede de produção, sem justificativa.</label><label><input type="radio" name="l01a" value="b"> 2 vCPU, 4 GB, disco de sistema de 40 GB, disco de dados vazio de 20 GB e rede didática isolada.</label><label><input type="radio" name="l01a" value="c"> 1 GB, disco de 5 GB e todos os dados reais da secretaria.</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir projeto</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box"><strong>Solução de referência, não capacidade universal</strong><p>Para este laboratório: <strong>Oracle VirtualBox 7.2.x</strong>, 2 vCPU, 4 GB de RAM, 40 GB para o sistema e 20 GB vazio para dados. O pacote-base do VirtualBox é suficiente; o Extension Pack não é necessário. A documentação oficial indica mínimos menores, mas o projeto reserva margem para Nginx, Samba e testes práticos. Produção exigiria medição, redundância e política próprias.</p></div>

    <h3>Instalação por estados verificáveis</h3>
    <div class="danger-box"><strong>Alvo exclusivo do laboratório</strong><p>Use somente a VM preparada. A instalação pode apagar o disco virtual escolhido. Confirme nome, tamanho e vínculo com SRV-01; snapshot ajuda a reverter o laboratório, mas não substitui cópia independente.</p></div>
    <ol><li>obtenha a ISO oficial do <strong>Ubuntu Server 24.04 LTS</strong> e registre origem/data;</li><li>se a VM não estiver pronta, no VirtualBox escolha <strong>Nova</strong>, identifique-a como <strong>SRV-01</strong>, selecione Linux/Ubuntu 64-bit, atribua os recursos aprovados e crie somente o disco de sistema de 40 GB;</li><li>em Configurações, conecte a ISO e a <strong>rede interna MBB-LAB do laboratório</strong>; adicione o disco vazio de 20 GB sem formatá-lo;</li><li>inicie pela ISO e confira idioma, teclado e interface detectada;</li><li>selecione apenas o disco virtual de 40 GB para o sistema; preserve o disco de dados de 20 GB sem formatar;</li><li>defina hostname <strong>srv-01</strong> e conta individual de Joana; não habilite root;</li><li>não adicione serviços opcionais sem necessidade; SSH será tratado após identidades e rede;</li><li>reinicie, remova a ISO virtual e confirme boot pelo disco correto. Nesta etapa, a VM serve apenas para oferecer isolamento, console e retorno seguro; redes virtuais e snapshots não são o foco do atendimento.</li></ol>
    <div class="danger-box compact"><strong>A réplica não pode colidir com a escola real</strong><p>MBB-LAB reutiliza endereços apenas dentro de uma réplica virtual controlada, com os elementos de rede do laboratório. Não use modo bridge nem conecte essa réplica simultaneamente à rede real: endereços duplicados podem interromper serviços e tornar a evidência inválida.</p></div>

    <h3>Baseline pós-instalação</h3>
    <div class="terminal-grid"><div class="terminal-card"><strong>Pergunta: que sistema iniciou?</strong><pre>hostnamectl&#10;cat /etc/os-release</pre><p>Registre hostname, versão e arquitetura. Não copie identificadores sensíveis.</p></div><div class="terminal-card"><strong>Pergunta: que recursos a VM vê?</strong><pre>lscpu&#10;free -h&#10;lsblk -f</pre><p>Compare com o projeto; o disco de dados deve continuar sem filesystem.</p></div><div class="terminal-card"><strong>Pergunta: há falha inicial?</strong><pre>ip -br addr&#10;systemctl --failed</pre><p>Uma lista vazia de unidades com falha não valida os serviços futuros.</p></div></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>VM definida, discos vazios e ISO oficial</span></div><div class="state-step"><strong>Intervenção</strong><span>24.04 LTS instalado só no disco de 40 GB</span></div><div class="state-step"><strong>Depois</strong><span>boot local e baseline coletado</span></div><div class="state-step"><strong>O que prova?</strong><span>base inicial funciona; serviços e recuperação ainda não</span></div></div>
    <div class="note-box compact"><strong>Baseline reutilizável</strong><p>O baseline será comparado após atualizações, armazenamento, rede e incidentes. Registre data, comandos, saídas relevantes e limites; saídas fornecidas como exemplo devem permanecer identificadas como representativas.</p></div>
    <div class="bridge-box"><strong>Primeira mudança administrativa</strong><p>O baseline mostra atualizações disponíveis. Antes de instalar pacotes, Joana precisa distinguir observação de alteração e decidir quando o privilégio administrativo é realmente necessário.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://ubuntu.com/server/docs/tutorial/basic-installation/" target="_blank" rel="noopener noreferrer">Ubuntu Server — instalação básica</a></li><li><a href="https://releases.ubuntu.com/24.04/" target="_blank" rel="noopener noreferrer">Canonical — imagens oficiais do Ubuntu 24.04 LTS</a></li></ul></details>
  `
});

window.infraestruturaLinuxLessons.push({
  id: 'linux-shell-apt',
  number: '02',
  unit: 'Servidor da escola · Perguntar antes de elevar',
  menuTitle: 'Shell, sudo e APT',
  technicalTitle: 'shell • identidade • caminho • sudo • APT • atualização • antes/depois',
  title: 'Este comando observa ou muda o servidor?',
  objective: 'Usar o shell para responder perguntas, elevar privilégio somente quando necessário e tratar atualizações como mudanças registradas e validadas.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">OS 018 · primeira manutenção do SRV-01</span><h2>Há 17 pacotes atualizáveis, mas o servidor ainda não tem janela nem registro de mudança.</h2><p>Joana entrou no console com sua conta individual. O baseline é o estado de referência. Digitar <code>sudo</code> antes de tudo apagaria a diferença entre leitura e intervenção; atualizar sem revisar impacto impediria explicar o que mudou.</p></div>

    <div class="command-board"><div class="command-card"><strong><code>whoami</code> e <code>id</code></strong><span>Pergunta: com qual identidade e grupos estou operando?</span><small>Observa; não concede privilégio.</small></div><div class="command-card"><strong><code>pwd</code> e <code>ls -la</code></strong><span>Pergunta: onde estou e o que este diretório contém?</span><small>Leia caminho e permissões antes de editar.</small></div><div class="command-card"><strong><code>sudo</code></strong><span>Pergunta: esta ação administrativa precisa de elevação temporária?</span><small>Não é prefixo automático nem torna o comando correto.</small></div></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Decisão de privilégio</span><h3>Identidade continua sendo parte da evidência</h3></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="service-stack"><div><strong>Joana</strong><span>usuária autenticada</span></div><div><strong>Pergunta</strong><span>ler ou alterar?</span></div><div><strong>sudo pontual</strong><span>somente se necessário</span></div><div><strong>Registro</strong><span>ação, horário e resultado</span></div></div><p class="visual-question"><strong>Decida:</strong> <code>free -h</code> precisa de sudo? E instalar um pacote? O privilégio muda a pergunta ou apenas a autoridade da ação?</p></div></div>

    <h3>APT como mudança de estado</h3>
    <div class="terminal-card"><strong>Pergunta: que atualizações os repositórios configurados oferecem?</strong><pre>sudo apt update&#10;apt list --upgradable</pre><p><strong>Saída didática representativa:</strong> o índice foi atualizado e 17 pacotes aparecem como atualizáveis. Isso ainda não significa que foram instalados.</p></div>
    <div class="task-box"><strong>Missão 02 · planejar e executar a janela</strong><ol><li>compare horário, versão e falhas atuais com baseline do servidor;</li><li>use <code>sudo apt update</code> para atualizar o índice e <code>apt list --upgradable</code> para revisar a proposta;</li><li>registre pacotes relevantes, impacto esperado, console disponível e ponto de retorno da VM;</li><li>na janela autorizada, execute <code>sudo apt upgrade</code> e leia o resumo antes de confirmar;</li><li>verifique <code>systemctl --failed</code>, versão, rede e funções que já existiam;</li><li>se houver reinício requerido, agende e repita o baseline — não reinicie durante uso sem autorização.</li></ol></div>
    <div class="danger-box compact"><strong>Repositório aleatório não é atalho.</strong><p>Não adicione PPA, script baixado ou pacote externo para “ter a versão mais nova”. Origem, suporte e reversão fazem parte da mudança.</p></div>

    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>baseline do servidor e 17 pacotes propostos</span></div><div class="state-step"><strong>Intervenção</strong><span>APT na janela autorizada</span></div><div class="state-step"><strong>Depois</strong><span>0 falhas systemd; funções-base repetidas</span></div><div class="state-step"><strong>O que prova?</strong><span>a atualização concluiu e os testes escolhidos passaram; acompanhar</span></div></div>
    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="c" data-explanation="Leitura de memória é permitida ao usuário comum; elevar sem necessidade amplia risco e enfraquece a disciplina de menor privilégio."><p>Qual comando deve ser tentado primeiro para observar memória?</p><label><input type="radio" name="l02a" value="a"> <code>sudo su</code></label><label><input type="radio" name="l02a" value="b"> habilitar a conta root</label><label><input type="radio" name="l02a" value="c"> <code>free -h</code></label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Mudanças e atualizações</strong><p>Anexe comando/pergunta, identidade, necessidade de privilégio, pacotes antes/depois, horário, resultado, validação e retorno. registro de mudanças orientará a investigação de qualquer falha que coincida com esta janela.</p></div>
    <div class="bridge-box"><strong>A técnica agora tem autoridade; os demais não precisam dela</strong><p>Ana deve trabalhar com documentos e Caio com materiais, mas nenhum deles administrará o sistema. O próximo passo traduz responsabilidade em identidade, grupo e permissão testada.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://ubuntu.com/server/docs/how-to/software/package-management/" target="_blank" rel="noopener noreferrer">Ubuntu Server — gerenciamento de pacotes com APT</a></li><li><a href="https://ubuntu.com/server/docs/how-to/security/user-management/" target="_blank" rel="noopener noreferrer">Ubuntu Server — usuários e sudo</a></li></ul></details>
  `
});

window.infraestruturaLinuxLessons.push({
  id: 'linux-usuarios-permissoes',
  number: '03',
  unit: 'Servidor da escola · Traduzir responsabilidade em acesso',
  menuTitle: 'Usuários e permissões',
  technicalTitle: 'usuário • grupo • UID/GID • proprietário • modo • setgid • teste por identidade',
  title: 'Quem administra, quem altera e quem apenas consulta?',
  objective: 'Modelar pessoas e funções reais como usuários, grupos e permissões Linux, validar o acesso com identidades diferentes e preservar menor privilégio.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Solicitação 019 · identidades do SRV-01</span><h2>A conta única “escola” daria acesso rápido — e nenhuma responsabilidade clara.</h2><p>registro de necessidade separa funções: Joana administra, Ana altera documentos da secretaria e Caio publica materiais docentes. A coordenação consulta relatórios, mas não precisa executar comandos. O modelo precisa funcionar depois no armazenamento, na intranet e no compartilhamento; por isso a matriz será testada agora e reutilizada.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Relação, não receita</span><h3>Da função ao teste de acesso</h3></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="diagnostic-flow"><div><strong>Pessoa</strong><span>Ana, Caio ou Joana</span></div><div><strong>Identidade</strong><span>conta individual</span></div><div><strong>Grupo</strong><span>necessidade comum</span></div><div><strong>Permissão</strong><span>ação no recurso</span></div><div><strong>Teste</strong><span>resultado com aquela conta</span></div></div><p class="visual-question"><strong>Preveja:</strong> pertencer a <code>secretaria</code> deve tornar Ana administradora? Qual evidência demonstra escrita sem conceder <code>sudo</code>?</p></div></div>

    <h3>Identidades e permissões começam como decisão, não como comando</h3>
    <div class="mbb-pause-question"><strong>Antes de conferir a referência</strong><p>Desenhe quatro linhas com: responsabilidade, identidade, grupo, recurso, ação necessária e se precisa administrar o sistema. Use registro de necessidade; não transforme cargo em privilégio automático.</p></div>
    <button class="action-button" type="button" data-reveal-answer="#identity-reference" aria-expanded="false">Conferir leitura da evidência</button>
    <div id="identity-reference" class="table-wrap" hidden><table><thead><tr><th>Identidade</th><th>Grupo funcional</th><th>Recurso futuro</th><th>Ação necessária</th><th>Administra sistema?</th></tr></thead><tbody><tr><td>joana</td><td>suporte</td><td>configurações e serviços</td><td>manter mediante sudo</td><td>sim, individualmente</td></tr><tr><td>ana.sec</td><td>secretaria</td><td>documentos da secretaria</td><td>ler e modificar</td><td>não</td></tr><tr><td>caio.prof</td><td>docentes</td><td>materiais de aula</td><td>ler e modificar</td><td>não</td></tr><tr><td>www-data</td><td>conta de serviço</td><td>conteúdo publicado</td><td>ler o necessário</td><td>não interativa</td></tr></tbody></table></div>

    <div class="terminal-grid"><div class="terminal-card"><strong>Pergunta: a identidade já existe?</strong><pre>getent passwd ana.sec&#10;getent group secretaria</pre><p>Saída vazia exige interpretar a fonte de identidades antes de criar.</p></div><div class="terminal-card"><strong>Ação autorizada: criar</strong><pre>sudo addgroup secretaria&#10;sudo adduser ana.sec&#10;sudo adduser ana.sec secretaria</pre><p>Não registre a senha definida; confirme dados da pessoa.</p></div><div class="terminal-card"><strong>Pergunta: qual acesso efetivo?</strong><pre>id ana.sec&#10;ls -ld /srv/escola-lab&#10;namei -l /srv/escola-lab/documentos</pre><p>Diretórios-pai também participam do acesso.</p></div></div>

    <div class="task-box"><strong>Missão 03 · laboratório com duas identidades</strong><ol><li>registre proprietário, grupo e modo da árvore de teste;</li><li>crie os grupos aprovados e contas individuais sem adicioná-las a <code>sudo</code>;</li><li>prepare pastas de laboratório para secretaria e docentes; conceda somente o grupo necessário;</li><li>use setgid no diretório compartilhado quando a política exigir que novos arquivos herdem o grupo;</li><li>entre ou execute o teste controlado como cada identidade: listar, ler, criar, alterar e excluir arquivo de teste;</li><li>compare com a previsão e reverta usando o estado inicial se houver acesso excessivo.</li></ol></div>
    <div class="danger-box"><strong><code>chmod 777</code> não é diagnóstico</strong><p>Ele concede acesso amplo e pode apenas esconder o erro de grupo, proprietário ou caminho. Não use permissão global como correção rápida, nem aplique <code>-R</code> sem compreender cada filho afetado.</p></div>

    <div class="evidence-switcher" data-evidence-switcher><p><strong>Saída didática representativa — escolha uma identidade:</strong></p><div class="switcher-buttons"><button type="button" data-evidence-view="ana" aria-pressed="true">Ana</button><button type="button" data-evidence-view="caio" aria-pressed="false">Caio</button><button type="button" data-evidence-view="joana" aria-pressed="false">Joana</button></div><div class="evidence-panel" data-evidence-panel="ana"><h4>Teste em documentos</h4><p>Leitura ✓ · criação ✓ · alteração ✓. Ana não executa <code>sudo</code>. A previsão da secretaria foi atendida.</p></div><div class="evidence-panel" data-evidence-panel="caio" hidden><h4>Teste em documentos</h4><p>Listagem bloqueada como previsto. Isso não prova acesso aos materiais, que deve ser testado separadamente.</p></div><div class="evidence-panel" data-evidence-panel="joana" hidden><h4>Teste administrativo</h4><p>Joana lê o estado como usuária e eleva somente a ação autorizada. Acesso de suporte não substitui o teste das identidades funcionais.</p></div></div>

    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="b" data-explanation="Grupos representam necessidades comuns; sudo é reservado a administração. A validação deve usar a identidade funcional."><p>Ana precisa alterar documentos, não o sistema. Qual decisão é adequada?</p><label><input type="radio" name="l03a" value="a"> adicioná-la ao grupo sudo</label><label><input type="radio" name="l03a" value="b"> adicioná-la ao grupo secretaria e testar o recurso</label><label><input type="radio" name="l03a" value="c"> compartilhar a conta de Joana</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Identidades e permissões</strong><p>Registre pessoa, conta, grupos, recurso, ações previstas, testes observados, exceções, responsável e retorno. matriz de identidades e permissões definirá proprietários no armazenamento, leitura da intranet, contas Samba e casos do plantão final.</p></div>
    <div class="bridge-box"><strong>O dado precisa de lugar persistente</strong><p>Com as identidades prontas, a equipe conecta o disco virtual de 20 GB preservado desde baseline do servidor. Ele aparece no sistema, mas ainda não está montado. A próxima decisão precisa confirmar o alvo antes de qualquer formatação.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://ubuntu.com/server/docs/how-to/security/user-management/" target="_blank" rel="noopener noreferrer">Ubuntu Server — gerenciamento de usuários e grupos</a></li></ul></details>
  `
});
