window.infraestruturaLinuxLessons = Array.isArray(window.infraestruturaLinuxLessons) ? window.infraestruturaLinuxLessons : [];

window.infraestruturaLinuxLessons.push({
  id: 'linux-armazenamento',
  number: '04',
  unit: 'Servidor da escola · Tornar dados persistentes',
  menuTitle: 'Armazenamento e montagem',
  technicalTitle: 'bloco • filesystem • UUID • ponto de montagem • fstab • espaço • validação',
  title: 'O disco apareceu. Como provar que é o alvo certo?',
  objective: 'Identificar dispositivos e filesystems, montar armazenamento persistente com alvo confirmado e preparar recuperação antes de ações destrutivas.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">OS 018 · disco de dados do SRV-01</span><h2>Depois do reinício, a VM mostra <code>vda</code> e <code>vdb</code>. Um deles contém o sistema.</h2><p>O baseline do servidor registra o disco de 40 GB com Ubuntu e o disco vazio de 20 GB. A matriz de identidades e permissões já define quem usará cada pasta. Um colega sugere formatar <code>/dev/vdb</code> “porque normalmente é o segundo”. Normalmente não é evidência: a ordem pode mudar e o comando não pergunta se havia dados.</p></div>
    <div class="danger-box"><strong>Formatação é destrutiva</strong><p>Execute somente na VM do laboratório, com console e snapshot anterior disponíveis. Confirme dispositivo, tamanho, filesystem, UUID, montagem e vínculo com a configuração da VM. Se qualquer dado divergir do baseline do servidor, pare.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Relação de armazenamento</span><h3>Dispositivo não é diretório</h3></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="service-stack"><div><strong>Disco virtual</strong><span>bloco de 20 GB</span></div><div><strong>Partição</strong><span>alvo confirmado</span></div><div><strong>Filesystem</strong><span>ext4 identificado por UUID</span></div><div><strong>/srv/escola</strong><span>ponto de montagem</span></div></div><p class="visual-question"><strong>Preveja:</strong> se o filesystem existe, mas não está montado em <code>/srv/escola</code> após reiniciar, qual registro deve ser comparado?</p></div></div>

    <h3>Observar antes de criar</h3>
    <div class="terminal-card"><strong>Pergunta: quais dispositivos, filesystems e montagens existem?</strong><pre>lsblk -o NAME,SIZE,FSTYPE,LABEL,UUID,MOUNTPOINTS&#10;findmnt&#10;df -hT</pre><p><strong>Saída didática representativa:</strong> <code>vda1</code> tem ext4 e monta em <code>/</code>; <code>vdb</code> tem 20 GB, sem filesystem e sem ponto de montagem. A saída deve ser confrontada com o baseline do servidor e com a configuração da VM.</p></div>
    <div class="mbb-pause-question"><strong>Decisão de duas evidências</strong><p>A equipe identifica o alvo por tamanho/ausência de filesystem <em>e</em> pela configuração do hipervisor. Nome do dispositivo isolado não autoriza a mudança.</p></div>

    <div class="task-box"><strong>Missão 04 · preparar o volume do laboratório</strong><ol><li>registre a saída observacional na seção Armazenamento do Registro do Servidor e confirme o alvo com outra pessoa;</li><li>se o laboratório já vier com uma partição vazia <code>/dev/vdb1</code>, confirme-a novamente antes de continuar;</li><li>na autorização explícita, crie ext4 com rótulo <code>DADOS_ESCOLA</code> somente nesse alvo;</li><li>obtenha o UUID com <code>lsblk -f</code> ou <code>blkid</code> e crie <code>/srv/escola</code>;</li><li>faça uma montagem temporária, confirme com <code>findmnt /srv/escola</code> e aplique as identidades e permissões planejadas;</li><li>registre no <code>/etc/fstab</code> usando UUID, não um nome sujeito à ordem de detecção;</li><li>teste a sintaxe/efeito com <code>sudo mount -a</code>, confira novamente e reinicie apenas com console disponível;</li><li>após o boot, valide montagem, permissões e criação/leitura por cada identidade prevista.</li></ol></div>

    <div class="terminal-card warn"><strong>Exemplo autorizado — substitua o UUID pela evidência real</strong><pre>UUID=11111111-2222-3333-4444-555555555555 /srv/escola ext4 defaults 0 2</pre><p>Esta é uma <strong>linha didática representativa</strong> de <code>/etc/fstab</code>. Não copie o UUID. Em caso de falha de boot, use o console da VM para comentar/reverter a linha e retornar ao registro anterior.</p></div>

    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>vdb vazio, confirmado pelo baseline do servidor e pela VM</span></div><div class="state-step"><strong>Intervenção</strong><span>filesystem, UUID e fstab documentados</span></div><div class="state-step"><strong>Depois</strong><span>/srv/escola monta após reinício</span></div><div class="state-step"><strong>O que prova?</strong><span>persistência e acesso testados neste volume; não é backup</span></div></div>
    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="c" data-explanation="Tamanho, filesystem, montagem, UUID e configuração externa precisam convergir antes de qualquer ação destrutiva."><p>Qual evidência autoriza formatar?</p><label><input type="radio" name="l04a" value="a"> o nome termina em b</label><label><input type="radio" name="l04a" value="b"> o disco apareceu por último</label><label><input type="radio" name="l04a" value="c"> o baseline do servidor, lsblk e a configuração da VM confirmam o mesmo disco vazio</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Armazenamento</strong><p>Registre dispositivo, tamanho, partição, tipo, rótulo, UUID, ponto, finalidade, proprietário/grupo, uso inicial, risco, teste pós-boot e retorno. Esse registro definirá os caminhos do Samba e do backup.</p></div>
    <div class="bridge-box"><strong>Persistente não significa alcançável</strong><p>Os dados agora têm lugar, mas SRV-01 ainda usa configuração temporária da rede isolada. O Registro da Rede já documenta endereço, gateway e DNS; a equipe deve aplicar esse plano sem perder o console ou o acesso futuro.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://manpages.ubuntu.com/manpages/noble/man8/lsblk.8.html" target="_blank" rel="noopener noreferrer">Ubuntu 24.04 manpage — lsblk</a></li><li><a href="https://manpages.ubuntu.com/manpages/noble/man5/fstab.5.html" target="_blank" rel="noopener noreferrer">Ubuntu 24.04 manpage — fstab e uso de UUID</a></li></ul></details>
  `
});

window.infraestruturaLinuxLessons.push({
  id: 'linux-netplan',
  number: '05',
  unit: 'Servidor da escola · Entrar na rede documentada',
  menuTitle: 'Rede com Netplan',
  technicalTitle: 'interface • endereço • rota • DNS • Netplan • teste temporário • rollback',
  title: 'Que configuração pertence ao SRV-01?',
  objective: 'Reutilizar o plano de rede já documentado para configurar o servidor com Netplan, prever perda de acesso e validar interface, rota, DNS e nome.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Mudança 020 · janela da rede didática</span><h2>O endereço <code>192.168.10.20</code> já tem significado; escolher outro “livre” criaria conflito documental.</h2><p>O plano de endereçamento coloca funcionários em <strong>192.168.10.0/26</strong>. O estado de rede registra gateway/DNS <strong>192.168.10.1</strong>; a matriz de serviços associa a intranet a <strong>192.168.10.20</strong>. A equipe decide preservar essa identidade na rede isolada do laboratório. Ainda falta descobrir o nome real da interface e como retornar se a mudança cortar o acesso.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Reutilização do mapa de rede</span><h3>Configuração é uma relação completa</h3></div><div class="visual-body"><span class="representation-badge">Diagrama próprio · endereços do cenário didático</span><div class="service-stack"><div><strong>SRV-01</strong><span>192.168.10.20/26</span></div><div><strong>SW-01</strong><span>caminho documentado</span></div><div><strong>RTR-01</strong><span>gateway/DNS .1</span></div><div><strong>Clientes</strong><span>nome e serviços</span></div></div><p class="visual-question"><strong>Decida antes de revelar:</strong> o endereço cabe no bloco de funcionários? Está reservado? O nome <code>intranet.escolahorizonte.example</code> identifica o host ou a função?</p></div></div>

    <div class="note-box"><strong>Referência aprovada após a decisão</strong><p>Hostname do ativo: <strong>srv-01</strong>. Endereço: <strong>192.168.10.20/26</strong>. Gateway e DNS: <strong>192.168.10.1</strong>. <strong>intranet.escolahorizonte.example</strong> é o nome reservado da função no cenário didático controlado; não é domínio público real e não substitui o ID do servidor.</p></div>

    <h3>Capturar o estado que pode ser perdido</h3>
    <div class="terminal-grid"><div class="terminal-card"><strong>Pergunta: qual interface está ativa?</strong><pre>ip -br link&#10;ip -br addr</pre><p>Use o nome observado; não copie <code>eth0</code> de outro tutorial.</p></div><div class="terminal-card"><strong>Pergunta: qual caminho e DNS existem?</strong><pre>ip route&#10;resolvectl status</pre><p>Registre rota e servidor consultado antes de alterar.</p></div><div class="terminal-card"><strong>Pergunta: quais arquivos geram a rede?</strong><pre>ls -l /etc/netplan&#10;sudo netplan get</pre><p>Mais de um arquivo pode participar. Preserve uma cópia controlada.</p></div></div>

    <h3>Proposta Netplan do laboratório</h3>
    <div class="terminal-card"><strong>Representação didática — substitua somente após confirmar interface e plano</strong><pre>network:&#10;  version: 2&#10;  renderer: networkd&#10;  ethernets:&#10;    enp0s3:&#10;      addresses: [192.168.10.20/26]&#10;      routes:&#10;        - to: default&#10;          via: 192.168.10.1&#10;      nameservers:&#10;        addresses: [192.168.10.1]</pre><p>YAML depende de indentação. O nome <code>enp0s3</code> é apenas representativo; use a interface obtida no servidor.</p></div>

    <div class="task-box"><strong>Missão 05 · testar sem se trancar para fora</strong><ol><li>registre o baseline do servidor, o plano de endereçamento, o estado de rede e a configuração atual; confirme console disponível;</li><li>crie um arquivo Netplan próprio com cópia da configuração anterior;</li><li>execute <code>sudo netplan generate</code> para detectar erro de sintaxe;</li><li>use <code>sudo netplan try --timeout 120</code>; confirme somente se console, endereço, rota e DNS funcionarem;</li><li>se o tempo expirar ou o teste falhar, verifique se a reversão ocorreu de fato antes de reiniciar;</li><li>valide localmente <code>netplan status</code>, <code>ip -br addr</code>, <code>ip route</code> e <code>resolvectl status</code>;</li><li>de uma origem autorizada, teste alcance ao IP e resolução do nome didático;</li><li>registre o que o teste comprovou e o que ainda depende de SSH, Web ou Samba.</li></ol></div>
    <div class="danger-box compact"><strong>Remoto muda o risco</strong><p><code>netplan try</code> oferece retorno por tempo, mas a documentação alerta para verificar a reversão. Sem console ou recuperação confirmada, não altere a única interface de administração.</p></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>DHCP temporário e baseline salvo</span></div><div class="state-step"><strong>Intervenção</strong><span>generate + try com console</span></div><div class="state-step"><strong>Depois</strong><span>.20/26, rota e DNS conferidos</span></div><div class="state-step"><strong>O que prova?</strong><span>estado de rede atual; não prova disponibilidade dos serviços</span></div></div>
    <div class="note-box compact"><strong>Rede do servidor</strong><p>Inclua interface/MAC de laboratório, arquivo, endereço, rota, DNS, nomes, origem dos dados, testes local/remoto, retorno e horário. Esse registro orientará SSH, Nginx, Samba, UFW e o plantão.</p></div>
    <div class="bridge-box"><strong>O console não escala a rotina</strong><p>SRV-01 está na rede didática, mas Joana ainda precisa ir ao host para administrar. A próxima solicitação define quem pode acessar por SSH, de onde e com qual forma de recuperação.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://ubuntu.com/server/docs/explanation/networking/configuring-networks/" target="_blank" rel="noopener noreferrer">Ubuntu Server — configuração de rede com Netplan</a></li><li><a href="https://netplan.readthedocs.io/en/stable/netplan-try/" target="_blank" rel="noopener noreferrer">Netplan — <code>netplan try</code> e rollback temporizado</a></li></ul></details>
  `
});

window.infraestruturaLinuxLessons.push({
  id: 'linux-ssh',
  number: '06',
  unit: 'Servidor da escola · Administrar sem depender do console',
  menuTitle: 'SSH seguro',
  technicalTitle: 'OpenSSH • identidade • host key • chave pública • sessão paralela • log • recuperação',
  title: 'Quem pode administrar, de onde e como volta se falhar?',
  objective: 'Implantar acesso SSH no laboratório com identidade individual, verificação do servidor, chave protegida, teste em nova sessão e método de recuperação preservado.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Solicitação 021 · acesso de Joana</span><h2>O host fica na sala técnica; a administração diária parte de ADM-01.</h2><p>matriz de identidades e permissões autoriza somente Joana a administrar. O registro de rede mostra SRV-01 em <strong>192.168.10.20</strong>. A coordenação não autoriza root remoto, senha compartilhada, exposição à Internet nem remoção do console. Antes de instalar, a equipe define origem, identidade, finalidade, log e recuperação.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Caminho de confiança</span><h3>Conexão segura não começa aceitando qualquer aviso</h3></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="service-stack"><div><strong>ADM-01</strong><span>origem autorizada</span></div><div><strong>SSH TCP 22</strong><span>canal criptografado</span></div><div><strong>SRV-01</strong><span>host verificado</span></div><div><strong>joana</strong><span>identidade individual</span></div></div><p class="visual-question"><strong>Observe e decida:</strong> como Joana confirma que a chave do host pertence ao SRV-01? Onde a tentativa de login ficará registrada?</p></div></div>

    <h3>Instalar, observar e comparar</h3>
    <div class="terminal-grid"><div class="terminal-card"><strong>No servidor: o serviço existe?</strong><pre>sudo apt install openssh-server&#10;systemctl status ssh --no-pager&#10;ss -ltn</pre><p>Serviço ativo e porta em escuta não provam acesso a partir de ADM-01.</p></div><div class="terminal-card"><strong>No console: qual fingerprint?</strong><pre>sudo ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub</pre><p>Compare por canal confiável antes de aceitar a primeira conexão.</p></div><div class="terminal-card"><strong>Em ADM-01: qual identidade?</strong><pre>ssh joana@192.168.10.20</pre><p>Registre origem, horário e resultado; não use root.</p></div></div>

    <div class="task-box"><strong>Missão 06 · chave sem cortar o acesso funcional</strong><ol><li>confirme console e snapshot; instale OpenSSH pela fonte oficial do Ubuntu;</li><li>verifique serviço, escuta e fingerprint no console;</li><li>faça a primeira conexão de ADM-01 e compare a fingerprint antes de aceitar;</li><li>no PowerShell de ADM-01, crie uma chave <code>ed25519</code> com frase secreta: <code>ssh-keygen -t ed25519</code>;</li><li>transfira <strong>somente a chave pública</strong> com o OpenSSH nativo: <code>Get-Content $env:USERPROFILE\.ssh\id_ed25519.pub | ssh joana@192.168.10.20 "umask 077; mkdir -p ~/.ssh; cat &gt;&gt; ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys"</code>;</li><li><strong>mantenha a sessão atual aberta</strong> e teste a chave em uma nova sessão;</li><li>correlacione a tentativa com <code>sudo journalctl -u ssh.service --since "10 minutes ago"</code>;</li><li>não desative autenticação existente nem altere porta nesta missão; registre melhoria futura separadamente.</li></ol></div>
    <div class="note-box compact"><strong>Por que não <code>ssh-copy-id</code>?</strong><p>Esse utilitário não integra o OpenSSH nativo padrão do Windows. Ele pode existir em WSL ou Git Bash, mas exigiria essa dependência adicional. O procedimento acima mantém ADM-01 no PowerShell e envia apenas o conteúdo do arquivo <code>.pub</code>.</p></div>
    <div class="danger-box"><strong>A chave privada não vai ao servidor nem ao relatório</strong><p>Proteja-a com frase secreta e permissões adequadas. Não copie credenciais reais para screenshots. Mudar a porta não substitui autenticação, firewall, atualização e logs.</p></div>

    <div class="mbb-pause-question"><strong>Qualquer mudança futura em SSH exige teste de configuração.</strong><p>Use um arquivo em <code>/etc/ssh/sshd_config.d/</code>, guarde o estado anterior e execute <code>sudo sshd -t</code> antes de recarregar/reiniciar. Valide em nova sessão antes de fechar a sessão funcional.</p></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>administração somente no console</span></div><div class="state-step"><strong>Intervenção</strong><span>OpenSSH + chave pública de Joana</span></div><div class="state-step"><strong>Depois</strong><span>nova sessão validada e log correlacionado</span></div><div class="state-step"><strong>O que prova?</strong><span>essa origem/identidade funcionou; firewall ainda será definido</span></div></div>
    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="a" data-explanation="A sessão existente e o console preservam recuperação enquanto a nova autenticação é validada separadamente."><p>Quando fechar a sessão SSH atual?</p><label><input type="radio" name="l06a" value="a"> após a nova sessão funcionar e o retorno estar confirmado</label><label><input type="radio" name="l06a" value="b"> antes de instalar a chave</label><label><input type="radio" name="l06a" value="c"> assim que editar a configuração</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Acesso remoto</strong><p>Identidade, origem, destino, fingerprint verificada, método, porta, teste, log, retorno e restrições. registro de acesso remoto será usado para permitir a origem mínima no UFW e para investigar falhas de administração.</p></div>
    <div class="bridge-box"><strong>Incidente controlado 051</strong><p>Após um reinício de laboratório, ADM-01 alcança o IP, mas a conexão SSH é recusada. O ambiente contém uma falha controlada, mas a causa não foi informada. Joana usa o console e o horário registrado para investigar serviço e log antes de reiniciar qualquer coisa.</p></div>
    <details class="sources-box"><summary>Documentação oficial atual</summary><ul><li><a href="https://ubuntu.com/server/docs/how-to/security/openssh-server/" target="_blank" rel="noopener noreferrer">Ubuntu Server — OpenSSH, chaves, validação e logs</a></li></ul></details>
  `
});

window.infraestruturaLinuxLessons.push({
  id: 'linux-systemd-logs',
  number: '07',
  unit: 'Servidor da escola · Investigar antes de reiniciar',
  menuTitle: 'systemd e logs',
  technicalTitle: 'systemctl • ativo • habilitado • falha • journalctl • horário • configuração',
  title: 'A porta parou de responder depois do boot. Onde está a evidência?',
  objective: 'Usar systemd e journalctl como ferramentas de investigação, revelar evidências progressivamente e corrigir somente quando a causa estiver sustentada.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Incidente 051 · 8h12 · SRV-01</span><h2>O ping responde; SSH funcionava ontem; hoje a porta 22 recusa conexão.</h2><p>baseline de rede torna uma falha total de rede menos provável. O registro de acesso remoto confirma origem, identidade e sucesso anterior. O registro de mudanças informa reinício na janela. Reiniciar novamente pode repetir o efeito sem explicar nada. A pergunta agora é: o serviço existe, tentou iniciar, falhou quando e por quê?</p></div>

    <div class="evidence-switcher" data-evidence-switcher><p><strong>Solicite uma evidência por vez e escolha o próximo teste:</strong></p><div class="switcher-buttons"><button type="button" data-evidence-view="e1" aria-pressed="true">E1 · sintoma</button><button type="button" data-evidence-view="e2" aria-pressed="false">E2 · estado</button><button type="button" data-evidence-view="e3" aria-pressed="false">E3 · log</button><button type="button" data-evidence-view="e4" aria-pressed="false">E4 · validação</button></div>
      <div class="evidence-panel" data-evidence-panel="e1"><h4>ADM-01 · 8h12</h4><div class="terminal-card"><pre>ping 192.168.10.20  → resposta&#10;ssh joana@192.168.10.20 → conexão recusada</pre></div><p>Qual hipótese ganhou força: rede total, serviço/porta ou credencial? Qual comando observacional vem a seguir?</p></div>
      <div class="evidence-panel" data-evidence-panel="e2" hidden><h4>Console · saída didática representativa</h4><div class="terminal-card"><pre>systemctl is-active ssh  → failed&#10;systemctl is-enabled ssh → enabled</pre></div><p><strong>Ativo</strong> descreve agora; <strong>habilitado</strong> descreve intenção de iniciar no boot. Um serviço pode estar habilitado e falhar.</p></div>
      <div class="evidence-panel" data-evidence-panel="e3" hidden><h4>Journal · 8h10</h4><div class="terminal-card"><pre>ssh.service: Main process exited&#10;sshd: /etc/ssh/sshd_config.d/90-escola.conf line 3:&#10;Bad configuration option: PasswordAuthenticaton</pre></div><p>A mensagem e o horário ligam a falha ao arquivo. Compare com os registros de acesso remoto e de mudanças antes de corrigir.</p></div>
      <div class="evidence-panel" data-evidence-panel="e4" hidden><h4>Teste da configuração</h4><div class="terminal-card"><pre>sudo sshd -t&#10;/etc/ssh/sshd_config.d/90-escola.conf line 3:&#10;Bad configuration option: PasswordAuthenticaton</pre></div><p>O teste confirma erro de diretiva. A saída é representativa; a falha controlada foi introduzida após o snapshot do laboratório.</p></div>
    </div>

    <h3>Ferramenta ligada a pergunta</h3>
    <div class="table-wrap"><table><thead><tr><th>Pergunta</th><th>Comando</th><th>Limite</th></tr></thead><tbody><tr><td>Qual é o estado atual?</td><td><code>systemctl status ssh --no-pager</code></td><td>mostra resumo e linhas recentes, não toda a causa</td></tr><tr><td>Deveria iniciar no boot?</td><td><code>systemctl is-enabled ssh</code></td><td>habilitado não significa saudável</td></tr><tr><td>Quando e como falhou?</td><td><code>journalctl -u ssh --since "today 08:00"</code></td><td>correlacione relógio, serviço e sintoma</td></tr><tr><td>A configuração é aceita?</td><td><code>sudo sshd -t</code></td><td>valida sintaxe; não prova acesso remoto</td></tr></tbody></table></div>

    <div class="task-box"><strong>Missão 07 · correção sustentada</strong><ol><li>preserve log, arquivo e horário antes de editar;</li><li>compare a diretiva com a referência aprovada e corrija somente o erro tipográfico;</li><li>execute <code>sudo sshd -t</code>; se houver saída/erro, não reinicie;</li><li>com configuração válida, inicie/reinicie o serviço na janela autorizada;</li><li>confirme <code>is-active</code>, escuta da porta e conexão real de ADM-01;</li><li>se a previsão falhar, restaure o snippet anterior e mantenha o console;</li><li>registre conclusão limitada: causa do incidente controlado, não garantia de disponibilidade futura.</li></ol></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>IP responde; ssh failed</span></div><div class="state-step"><strong>Intervenção</strong><span>uma diretiva corrigida após log/teste</span></div><div class="state-step"><strong>Depois</strong><span>ativo, escutando e login validado</span></div><div class="state-step"><strong>O que prova?</strong><span>o erro causava esta falha controlada; acompanhar</span></div></div>
    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="c" data-explanation="Reiniciar sem ler estado e log altera o cenário e não testa a hipótese sobre configuração."><p>Qual ação tem menor valor diagnóstico no início?</p><label><input type="radio" name="l07a" value="a"> correlacionar horário no journal</label><label><input type="radio" name="l07a" value="b"> validar a configuração</label><label><input type="radio" name="l07a" value="c"> reiniciar repetidamente até voltar</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Serviços e logs</strong><p>Sintoma, impacto, serviço, ativo/habilitado, horário, saída relevante, hipótese, teste, mudança, retorno e validação. O mesmo formato será usado no Nginx, Samba e plantão final.</p></div>
    <div class="bridge-box"><strong>Mudança concluída; nova entrega</strong><p>O incidente 051 é fechado. A coordenação aprova uma versão de homologação da intranet em SRV-01. Ela deve ser testada localmente antes de qualquer liberação na rede e não pode substituir o endpoint existente por surpresa.</p></div>
  `
});
