window.infraestruturaModernLessons = Array.isArray(window.infraestruturaModernLessons) ? window.infraestruturaModernLessons : [];

window.infraestruturaModernLessons.push({
  id: 'moderna-implantacao',
  number: '08',
  unit: 'Portal de Eventos · Operar e expor com controle',
  menuTitle: 'Ensaio de implantação',
  technicalTitle: 'IaaS simulado • SSH • configuração • segredo • túnel • validação • passagem',
  title: 'Implante em outro host sem publicar na internet',
  objective: 'Reproduzir o serviço em uma VM remota controlada, transferir apenas artefatos necessários e validar por túnel SSH.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Quinta-feira · 13h40 · sala de laboratório</span><h2>VPS-LAB-01 simula um servidor contratado, mas continua dentro da rede didática.</h2><p>A documentação de acesso informa IP, fingerprint e a conta individual de Joana. A equipe recebe console de recuperação, janela e snapshot-base. A VM não contém dados reais nem representa segurança/ disponibilidade de um provedor comercial.</p></div>

    <div class="danger-box"><strong>Origem e destino precisam ser inequívocos</strong><p>Confirme fingerprint por um canal separado de confirmação, hostname e diretório antes de copiar. Não transfira chave privada, segredos antigos, dump com dados reais ou todo o diretório pessoal. Mantenha a porta web em loopback.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Diagrama didático · caminho do teste</span><h3>O túnel transporta a conexão; não publica a aplicação</h3></div><div class="visual-body"><div class="diagnostic-flow"><div><span>1</span><strong>ADM-01</strong><small>navegador em 127.0.0.1:8080</small></div><div><span>2</span><strong>SSH</strong><small>canal autenticado até a VM</small></div><div><span>3</span><strong>VPS-LAB-01</strong><small>loopback 127.0.0.1:8080</small></div><div><span>4</span><strong>Compose</strong><small>web → rede back → db</small></div></div><p class="visual-question">Se o túnel fechar, quem ainda consegue alcançar a porta 8080? Teste antes de responder.</p></div></div>

    <div class="task-box"><strong>Missão · implantação reproduzível</strong><ol><li>registre baseline da VM remota: sistema, recurso, disco, rede, horário e serviços;</li><li>instale o Docker pela mesma fonte oficial e registre versões;</li><li>transfira apenas <code>compose.yaml</code> e documentação sem segredos;</li><li>crie novos arquivos de segredo diretamente na VM, com permissão restrita;</li><li>revise <code>sudo docker compose config</code>, faça pull e registre digests;</li><li>suba o conjunto e valide localmente na VM com <code>curl -I http://127.0.0.1:8080</code>;</li><li>em ADM-01/PowerShell, abra <code>ssh -L 8080:127.0.0.1:8080 joana@&lt;IP_DO_LAB&gt;</code>;</li><li>acesse <code>http://127.0.0.1:8080</code> em ADM-01 e cadastre somente uma inscrição fictícia;</li><li>feche o túnel e confirme que não há publicação externa inesperada;</li><li>registre parada, retorno e pessoa responsável.</li></ol></div>

    <div class="table-wrap"><table><thead><tr><th>Evidência</th><th>Pergunta</th><th>Limite</th></tr></thead><tbody><tr><td><code>ss -ltnp</code> na VM</td><td>em qual endereço a porta escuta?</td><td>não prova regra fora do host</td></tr><tr><td><code>curl</code> na VM</td><td>o serviço responde localmente?</td><td>não prova caminho de ADM-01</td></tr><tr><td>navegador pelo túnel</td><td>SSH encaminha a função até ADM-01?</td><td>não torna serviço público</td></tr><tr><td>teste com túnel fechado</td><td>o acesso dependia do canal?</td><td>não é auditoria completa de exposição</td></tr></tbody></table></div>

    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="b" data-explanation="O túnel dá acesso ao cliente autenticado enquanto existe; DNS público, firewall de borda e TLS público não foram implementados."><p>A página abriu em ADM-01 pelo túnel. O que isso prova?</p><label><input type="radio" name="m08a" value="a"> o portal está publicado com segurança na internet</label><label><input type="radio" name="m08a" value="b"> o serviço local da VM foi alcançado através daquela sessão SSH autenticada</label><label><input type="radio" name="m08a" value="c"> qualquer usuário da escola consegue acessar</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Registro da Evolução · implantação remota</strong><p>Atualize o Registro da Evolução com baseline, origem, arquivos transferidos, segredos recriados (sem valores), versões/digests, escutas, teste local, teste pelo túnel, teste negado e passagem.</p></div>
    <div class="bridge-box"><strong>Consequência</strong><p>O serviço remoto funciona de forma privada. Antes de discutir acesso por nome e HTTPS, a equipe precisa separar DNS, porta, TLS e aplicação — e respeitar o domínio reservado do cenário.</p></div>
  `
});

window.infraestruturaModernLessons.push({
  id: 'moderna-dns-tls',
  number: '09',
  unit: 'Portal de Eventos · Operar e expor com controle',
  menuTitle: 'DNS, TLS e exposição',
  technicalTitle: 'DNS • endereço • porta • TLS • HTTP • certificado • ACME • log • firewall',
  title: 'Um nome não publica um serviço — e um cadeado não autoriza acesso',
  objective: 'Diagnosticar a cadeia DNS–TCP–TLS–HTTP e planejar exposição sem solicitar certificado público para domínio reservado.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Sexta-feira · 8h00 · revisão de segurança</span><h2>Ana pede <code>eventos.escolahorizonte.example</code>; Caio tenta emitir um certificado público.</h2><p>Joana interrompe a ação. O sufixo <code>.example</code> é reservado para documentação e não representa domínio público controlado pela escola. O laboratório continuará privado, e nenhuma advertência de certificado será ignorada.</p></div>

    <div class="danger-box"><strong>Nunca solicite certificado público para <code>.example</code></strong><p>Autoridades públicas validam controle de nomes reais por desafios como HTTP-01 ou DNS-01. Para este cenário, use HTTP pelo túnel ou, se houver, uma CA interna com certificado e confiança distribuídos corretamente. Não clique em “continuar mesmo assim”.</p></div>
    <div class="note-box compact"><strong>Fontes primárias</strong><p>A IANA mantém <a href="https://www.iana.org/help/example-domains" target="_blank" rel="noopener">domínios de exemplo</a> para documentação. Para um domínio real controlado, consulte os <a href="https://letsencrypt.org/docs/challenge-types/" target="_blank" rel="noopener">desafios ACME</a>; para portas Docker, revise a documentação oficial de <a href="https://docs.docker.com/engine/network/packet-filtering-firewalls/" target="_blank" rel="noopener">firewall e filtragem de pacotes</a>.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Diagrama didático · cadeia de evidências</span><h3>Localize a primeira camada que diverge</h3></div><div class="visual-body"><div class="diagnostic-flow"><div><span>1</span><strong>DNS</strong><small>nome → endereço esperado</small></div><div><span>2</span><strong>TCP</strong><small>origem alcança porta?</small></div><div><span>3</span><strong>TLS</strong><small>nome, cadeia e validade</small></div><div><span>4</span><strong>HTTP/app</strong><small>status, conteúdo e log</small></div></div><p class="visual-question">Se DNS aponta para o IP correto e a porta recusa, qual camada ganhou força? Qual ainda não foi testada?</p></div></div>

    <div class="table-wrap"><table><thead><tr><th>Observação</th><th>Ferramenta</th><th>Conclusão válida</th></tr></thead><tbody><tr><td>nome resolve</td><td><code>nslookup</code> ou <code>dig</code></td><td>o resolvedor devolveu aquele endereço</td></tr><tr><td>porta escuta</td><td><code>ss -ltnp</code></td><td>há processo associado localmente</td></tr><tr><td>TLS apresenta certificado</td><td><code>openssl s_client -servername</code></td><td>cadeia/nome/datas podem ser examinados</td></tr><tr><td>HTTP responde</td><td><code>curl -I</code> e logs</td><td>a aplicação respondeu naquele caminho</td></tr></tbody></table></div>

    <div class="task-box"><strong>Missão · diagnóstico em camadas</strong><ol><li>receba três saídas representativas do cenário, rotuladas com origem e horário: DNS correto/porta fechada, DNS incorreto e TLS interno sem confiança instalada;</li><li>para cada caso, escreva a primeira divergência e o próximo teste de menor risco;</li><li>no laboratório real, confirme escuta em loopback e acesso pelo túnel;</li><li>se houver CA interna preparada, instale a confiança somente pelo procedimento institucional e valide nome, cadeia e período;</li><li>registre por que <code>eventos.escolahorizonte.example</code> permanece interno/didático;</li><li>desenhe, sem executar, a extensão pública: domínio real controlado, DNS, autorização, exposição mínima, ACME, renovação, logs, proteção e rollback.</li></ol></div>
    <div class="note-box compact"><strong>Docker e UFW exigem verificação específica</strong><p>Portas publicadas pelo Docker podem ser desviadas por NAT antes das cadeias usuais do UFW. Não conclua que “UFW bloqueia” apenas pelo status. Prefira loopback no laboratório e, numa publicação autorizada, revise as regras Docker/DOCKER-USER e teste de uma origem externa controlada.</p></div>

    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="a" data-explanation="Certificado válido autentica o nome/canal segundo a cadeia de confiança; autorização da aplicação continua separada."><p>Um certificado válido prova que o usuário pode acessar inscrições?</p><label><input type="radio" name="m09a" value="a"> não; TLS protege/autentica o canal, enquanto identidade e autorização continuam na aplicação</label><label><input type="radio" name="m09a" value="b"> sim, o cadeado concede permissão</label><label><input type="radio" name="m09a" value="c"> sim, se a porta for 443</label></div><div class="quiz-item" data-quiz-question data-answer="c" data-explanation="A resolução correta apenas confirma a resposta DNS observada; porta, TLS, HTTP e função ainda precisam de testes próprios."><p>O nome resolveu para o IP esperado. O que ainda não pode ser concluído?</p><label><input type="radio" name="m09b" value="a"> qual IP foi devolvido</label><label><input type="radio" name="m09b" value="b"> qual resolvedor respondeu</label><label><input type="radio" name="m09b" value="c"> que a porta, o TLS e a aplicação funcionam</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir diagnóstico</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Registro da Evolução · exposição e TLS</strong><p>Registre nome, escopo, DNS, endereço/porta, TLS, origem autorizada, log, teste permitido/negado, renovação, rollback e itens não implementados.</p></div>
    <div class="bridge-box"><strong>Consequência</strong><p>A coordenação agora consegue separar “funciona no laboratório” de “pode ser publicado”. Falta consolidar uma arquitetura justificável e uma transição segura.</p></div>
  `
});

window.infraestruturaModernLessons.push({
  id: 'moderna-arquitetura',
  number: '10',
  unit: 'Portal de Eventos · Arquitetura justificável',
  menuTitle: 'Decisão de arquitetura',
  technicalTitle: 'requisito • matriz • domínio de falha • operação • continuidade • transição • decisão',
  title: 'Escolha a arquitetura que a equipe consegue sustentar',
  objective: 'Consolidar evidências técnicas e organizacionais em uma decisão condicional, com operação, continuidade e limites explícitos.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Sexta-feira · 10h30 · conselho de implantação</span><h2>O protótipo funciona. A pergunta agora é se a escola consegue operá-lo.</h2><p>Ana apresenta o impacto da feira; Caio apresenta desempenho e implantação; Joana apresenta segurança, recuperação e passagem. O conselho não escolherá uma tecnologia “vencedora”, mas uma arquitetura adequada à fase e condições para mudar de fase.</p></div>

    <h3>Comparar com rastreabilidade</h3>
    <div class="table-wrap"><table><thead><tr><th>Critério</th><th>Evidência acumulada</th><th>Peso sugerido</th></tr></thead><tbody><tr><td>Preservar SRV-01</td><td>necessidade + VM: domínio de falha separado</td><td>alto</td></tr><tr><td>Capacidade e operação</td><td>VM + capacidade + runtime: medidas e tarefas</td><td>alto</td></tr><tr><td>Reprodução/persistência</td><td>persistência + Compose + atualização</td><td>alto</td></tr><tr><td>Acesso e exposição</td><td>implantação + exposição</td><td>alto</td></tr><tr><td>Custo, privacidade, saída</td><td>hospedagem + decisão institucional</td><td>alto para produção</td></tr></tbody></table></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Decisão da fase · não regra universal</span><h3>Arquitetura recomendada para homologação</h3></div><div class="visual-body"><div class="service-stack"><div><strong>LAB-06</strong><span>host de laboratório medido</span></div><div><strong>APP-LAB-01</strong><span>VM separada do SRV-01</span></div><div><strong>Compose</strong><span>WordPress + MariaDB<br>loopback + volumes</span></div></div><p class="visual-question"><strong>Decisão:</strong> adequada para homologação interna fictícia. <strong>Não autoriza:</strong> produção, dados reais ou acesso público.</p></div></div>

    <h3>Aplicar · plano de transição</h3>
    <div class="task-box"><strong>Missão · registro de decisão</strong><ol><li>defina a fase: homologação interna, público e dados fictícios;</li><li>cite as seções e evidências do Registro da Evolução que sustentam a proposta;</li><li>desenhe componentes, redes, dados, fluxos e responsáveis;</li><li>registre rotina de atualização, backup, restauração, monitoramento e passagem;</li><li>defina sinais de capacidade/risco que exigem nova decisão;</li><li>liste pré-condições para produção externa: responsável institucional, domínio real, privacidade, custo, disponibilidade, suporte, TLS e resposta a incidente;</li><li>inclua alternativa e rollback;</li><li>submeta a decisão a outra equipe, que deve localizar uma suposição ainda não provada.</li></ol></div>
    <div class="danger-box"><strong>Não promova o laboratório por conveniência</strong><p>Uma VM local com Compose pode ser adequada à aprendizagem e inadequada à produção. O ambiente real pode favorecer serviço gerenciado, outra arquitetura ou não publicação. A evidência decide junto com governança, não o entusiasmo pela ferramenta.</p></div>

    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="b" data-explanation="A recomendação é limitada à homologação; produção depende de requisitos e decisões ainda ausentes."><p>Qual conclusão deve entrar no decisão arquitetural?</p><label><input type="radio" name="m10a" value="a"> Docker é a arquitetura definitiva da escola</label><label><input type="radio" name="m10a" value="b"> VM separada + Compose atende à homologação fictícia medida; produção externa permanece condicionada</label><label><input type="radio" name="m10a" value="c"> o SRV-01 deve receber o portal para economizar recursos</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir decisão</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Registro da Evolução · decisão arquitetural</strong><p>Atualize o Registro da Evolução com contexto, alternativas, critérios/pesos, evidências, decisão, diagrama, responsabilidades, segurança, continuidade, custo, limitações, gatilhos de revisão e aprovação.</p></div>
    <div class="essence"><strong>Essência da infraestrutura moderna</strong><p>Infraestrutura moderna é escolher e operar fronteiras: <strong>host, VM, contêiner, rede, dado, identidade, fornecedor e responsabilidade</strong>. Abstração não elimina o equipamento nem a obrigação de provar recuperação.</p></div>
    <div class="bridge-box"><strong>Próximo passo</strong><p>A oficina 99 não entregará uma falha conhecida. Outra equipe receberá os A-registros e um ambiente alterado, devendo migrar, diagnosticar, validar e passar o serviço.</p></div>
  `
});
