window.infraestruturaNetworkLessons = Array.isArray(window.infraestruturaNetworkLessons) ? window.infraestruturaNetworkLessons : [];

window.infraestruturaNetworkLessons.push({
  id: 'redes-configuracao',
  number: '04',
  unit: 'Rede da escola · Ler a configuração recebida',
  menuTitle: 'DHCP, gateway e DNS',
  technicalTitle: 'ipconfig • DHCP • APIPA • gateway • DNS • comparação de estados',
  title: 'Três sintomas, três configurações para comparar',
  objective: 'Interpretar a configuração IPv4 de estações Windows e escolher testes que diferenciem DHCP, alcance ao gateway e resolução de nomes.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Chamado 034 · 9h20 · após troca do equipamento do provedor</span><h2>ADM-01, SALA-04 e SEC-02 não estão no mesmo estado.</h2><p>SEC-02 continua trabalhando. ADM-01 mostra “rede não identificada”. SALA-04 abre <strong>http://192.168.10.20</strong>, mas não <strong>intranet.escolahorizonte.example</strong>. Reiniciar tudo esconderia a diferença. A equipe consulta o plano de endereçamento e coleta a configuração antes de modificar.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Evidência transcrita de laboratório Windows</span><h3>Compare as três saídas de <code>ipconfig /all</code></h3><p>Os valores são didáticos e pertencem à rede de laboratório. Não copie endereços para outra rede.</p></div><div class="visual-body"><div class="terminal-grid">
      <div class="terminal-card"><strong>SEC-02 · referência</strong><pre>IPv4 . . . . . : 192.168.10.22&#10;Máscara . . . . : 255.255.255.0&#10;Gateway . . . . : 192.168.10.1&#10;DHCP habilitado : Sim&#10;Servidor DHCP  . : 192.168.10.1&#10;Servidores DNS . : 192.168.10.1</pre></div>
      <div class="terminal-card warn"><strong>ADM-01 · estado A</strong><pre>IPv4 autoconfig.: 169.254.44.18&#10;Máscara . . . . : 255.255.0.0&#10;Gateway . . . . :&#10;DHCP habilitado : Sim&#10;Servidor DHCP  . :</pre></div>
      <div class="terminal-card warn"><strong>SALA-04 · estado B</strong><pre>IPv4 . . . . . : 192.168.10.41&#10;Máscara . . . . : 255.255.255.0&#10;Gateway . . . . : 192.168.10.1&#10;DHCP habilitado : Não&#10;Servidores DNS . : 192.168.10.250</pre></div>
    </div><ol class="observation-prompts"><li><strong>Localize</strong>Qual estação não obteve configuração DHCP utilizável?</li><li><strong>Compare</strong>Qual campo explica a falha apenas por nome?</li><li><strong>Limite</strong>A saída prova se o cabo está íntegro?</li></ol></div></div>

    <div class="evidence-switcher" data-evidence-switcher><div class="switcher-buttons"><button type="button" data-evidence-view="adm" aria-pressed="true">ADM-01</button><button type="button" data-evidence-view="sala" aria-pressed="false">SALA-04</button></div><div class="evidence-panel" data-evidence-panel="adm"><h4>Hipótese mais forte</h4><p>ADM-01 não recebeu concessão DHCP e adotou endereço automático 169.254/16. Isso <strong>não identifica sozinho a causa</strong>: enlace, porta, VLAN, caminho até o DHCP ou o próprio serviço continuam possíveis.</p><p><strong>Próximo teste:</strong> comparar LED/link e porta com o mapa de portas e cabos; só depois, em janela controlada, renovar a concessão.</p></div><div class="evidence-panel" data-evidence-panel="sala" hidden><h4>Hipótese mais forte</h4><p>SALA-04 alcança o servidor por IP, mas aponta DNS manual fora do plano. A resolução de nomes merece teste específico.</p><p><strong>Próximo teste:</strong> <code>nslookup intranet.escolahorizonte.example</code> e registro de servidor consultado, resposta e horário.</p></div></div>

    <h3>Comando só existe porque há uma pergunta</h3>
    <div class="table-wrap"><table><thead><tr><th>Pergunta</th><th>Ação segura</th><th>Resultado esperado</th><th>O que não prova</th></tr></thead><tbody><tr><td>Que configuração esta interface recebeu?</td><td><code>ipconfig /all</code></td><td>interface, DHCP, IPv4, gateway e DNS</td><td>que todos os destinos respondem</td></tr><tr><td>O nome resolve e por qual DNS?</td><td><code>nslookup intranet.escolahorizonte.example</code></td><td>servidor consultado e resposta</td><td>que o serviço web está saudável</td></tr><tr><td>A concessão pode ser refeita?</td><td><code>ipconfig /release</code> e <code>ipconfig /renew</code> apenas em laboratório autorizado</td><td>nova tentativa DHCP</td><td>que renovar em produção não causará interrupção</td></tr></tbody></table></div>
    <div class="danger-box"><strong>Não use “liberar/renovar” como reflexo</strong><p>O comando interrompe a configuração daquela interface e pode afetar sessão remota. Registre o antes, confirme autorização e forma de recuperação e use apenas no equipamento controlado.</p></div>
    <div class="task-box"><strong>Missão 04 · comparar estados de rede</strong><p>Para cada estação, registre interface, endereço/prefixo, origem da configuração, gateway, DNS, horário, hipótese, teste escolhido e resultado. Corrija SALA-04 pela interface gráfica autorizada para usar DHCP; em ADM-01, descubra primeiro que a porta 17 do SW-01 não pertence ao caminho documentado após a troca.</p></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>SALA-04 usa DNS 192.168.10.250</span></div><div class="state-step"><strong>Intervenção</strong><span>retorno autorizado a DHCP</span></div><div class="state-step"><strong>Depois</strong><span>DNS 192.168.10.1; nome resolve</span></div><div class="state-step"><strong>O que prova?</strong><span>a configuração de DNS participava do sintoma testado</span></div></div>
    <div class="note-box compact"><strong>Reutilização</strong><p>O estado de rede registrado passa a integrar o mapa e o inventário. O incidente também revela que “IP correto” ainda não responde se o destino está na rede local ou além do gateway.</p></div>
    <div class="bridge-box"><strong>Chamado 035 · portal externo lento</strong><p>Às 10h10, SEC-02 alcança o gateway e a intranet, mas um portal externo falha. A equipe precisa observar o <strong>caminho</strong> antes de culpar o provedor ou o computador.</p></div>
    <details class="sources-box"><summary>Documentação oficial usada</summary><ul><li><a href="https://learn.microsoft.com/windows-server/administration/windows-commands/ipconfig" target="_blank" rel="noopener noreferrer">Microsoft Learn — ipconfig</a></li><li><a href="https://learn.microsoft.com/windows-server/administration/windows-commands/nslookup" target="_blank" rel="noopener noreferrer">Microsoft Learn — nslookup</a></li></ul></details>
  `
});

window.infraestruturaNetworkLessons.push({
  id: 'redes-rota',
  number: '05',
  unit: 'Rede da escola · Seguir o caminho',
  menuTitle: 'Roteamento, NAT e caminho',
  technicalTitle: 'destino local • gateway • saltos • rota • NAT • limite do tracert',
  title: 'O primeiro salto responde. Onde o caminho muda?',
  objective: 'Relacionar destino, gateway, rota e NAT a uma investigação concreta, interpretando saltos sem tratar ausência de resposta como prova automática de falha.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Chamado 035 · SEC-02</span><h2>A intranet funciona; um portal externo não.</h2><p>Ana precisa emitir um documento no portal conveniado. O estado de rede registrado mostra configuração coerente. A intranet em 192.168.10.20 responde, assim como o gateway 192.168.10.1. O impacto está restrito a um destino externo, mas a equipe ainda precisa distinguir estação, saída local, caminho intermediário e serviço remoto.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Representação didática</span><h3>Leia o caminho da origem ao serviço</h3><p>Cada bloco responde a uma pergunta diferente.</p></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="route-map"><div class="route-node"><strong>SEC-02</strong><span>192.168.10.22</span></div><div class="route-arrow"><span>rede local</span></div><div class="route-node"><strong>RTR-01</strong><span>gateway / NAT</span></div><div class="route-arrow"><span>provedor</span></div><div class="route-node"><strong>Internet</strong><span>saltos intermediários</span></div><div class="route-arrow"><span>destino</span></div><div class="route-node"><strong>Portal</strong><span>serviço HTTPS</span></div></div><p class="visual-question"><strong>Preveja:</strong> se SEC-02 alcança RTR-01, mas o rastreamento para no salto 2, o que ficou menos provável? O que ainda não pode ser concluído?</p></div></div>

    <div class="terminal-card"><strong>Rastreamento observado · <code>tracert portal.exemplo.gov.br</code> · 10h14</strong><pre>1     1 ms     1 ms     1 ms  192.168.10.1&#10;2     8 ms     7 ms     8 ms  100.64.0.1&#10;3     *        *        *     Esgotado o tempo limite.&#10;4    18 ms    17 ms    18 ms  203.0.113.9</pre><p>Um salto sem resposta não significa necessariamente interrupção: equipamentos podem encaminhar tráfego e limitar mensagens usadas pelo rastreamento.</p></div>

    <div class="two-col"><div class="definition-box"><strong>Rota</strong><p>Decisão de próximo caminho para alcançar uma rede. O gateway padrão atende destinos que não estão na rede local.</p></div><div class="definition-box"><strong>NAT no caso</strong><p>RTR-01 traduz a origem privada ao sair. Isso permite comunicação externa; não comprova disponibilidade do portal e não substitui política de segurança.</p></div></div>
    <div class="task-box"><strong>Missão 05 · registrar o caminho</strong><ol><li>Pergunta: a falha ocorre antes ou depois do gateway?</li><li>Previsão: o primeiro salto deve ser 192.168.10.1 conforme o estado de rede registrado.</li><li>Ação: compare <code>ping 192.168.10.1</code>, <code>tracert</code> para o destino e um destino externo de referência autorizado.</li><li>Registro: origem, destino, horário, primeiro salto, mudança observada e limite.</li><li>Rollback: nenhum estado foi alterado; os comandos são observacionais.</li></ol></div>
    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="c" data-explanation="O gateway responde e saltos seguintes aparecem; isso reduz a força de uma falha local total, mas não determina sozinho onde o portal falhou."><p>Qual conclusão cabe após o rastreamento observado?</p><label><input type="radio" name="r05a" value="a"> O salto 3 está quebrado.</label><label><input type="radio" name="r05a" value="b"> O provedor é culpado.</label><label><input type="radio" name="r05a" value="c"> Há encaminhamento além do gateway; a falha total da LAN ficou menos provável.</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Conclusão limitada</strong><p>O portal voltou sem intervenção local às 10h27. Registre indisponibilidade observada no período e mantenha a saída registrada; não declare “provedor corrigido” sem evidência do responsável externo.</p></div>
    <div class="bridge-box"><strong>O caminho pode funcionar e o serviço falhar</strong><p>No Chamado 032, IMP-01 responde na rede, mas a impressão continua parada. O próximo passo é testar <strong>o serviço certo na porta certa</strong>, não encerrar no ping.</p></div>
    <details class="sources-box"><summary>Documentação oficial usada</summary><ul><li><a href="https://learn.microsoft.com/windows-server/administration/windows-commands/ping" target="_blank" rel="noopener noreferrer">Microsoft Learn — ping</a></li><li><a href="https://learn.microsoft.com/windows-server/administration/windows-commands/tracert" target="_blank" rel="noopener noreferrer">Microsoft Learn — tracert</a></li></ul></details>
  `
});

window.infraestruturaNetworkLessons.push({
  id: 'redes-portas',
  number: '06',
  unit: 'Rede da escola · Testar o serviço',
  menuTitle: 'TCP, UDP, portas e serviços',
  technicalTitle: 'serviço • porta • TCP/UDP • escuta • conexão • Test-NetConnection',
  title: 'Ping responde, mas a fila não imprime',
  objective: 'Relacionar serviço e porta ao caso real da impressora e diferenciar alcance IP de disponibilidade de aplicação.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Retorno ao Chamado 032 · IMP-01</span><h2>A impressora está alcançável, mas isso não é o mesmo que aceitar trabalhos.</h2><p>O mapa e inventário agora localiza IMP-01 na secretaria e o estado de rede registra seu endereço reservado. O ping responde. O manual do modelo, arquivado pela escola, informa impressão direta em <strong>TCP 9100</strong>. A fila de SEC-02 usa esse destino. A pergunta deixa de ser “há rede?” e passa a ser “o serviço esperado aceita conexão?”.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Representação didática</span><h3>Do equipamento ao serviço específico</h3><p>Localize onde cada teste termina.</p></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="service-stack"><div><strong>SEC-02</strong><span>origem</span></div><div><strong>192.168.10.50</strong><span>IMP-01 alcançável</span></div><div class="blocked"><strong>TCP 9100</strong><span>conexão falhou</span></div><div><strong>Fila de impressão</strong><span>trabalho pendente</span></div></div><p class="visual-question"><strong>Interprete:</strong> qual teste enfraquece a hipótese de falha total de rede? Qual evidência aponta para serviço/configuração específica?</p></div></div>

    <div class="terminal-card"><strong>Teste de porta TCP · pergunta: a porta documentada aceita TCP?</strong><pre>PS&gt; Test-NetConnection 192.168.10.50 -Port 9100&#10;ComputerName     : 192.168.10.50&#10;RemotePort       : 9100&#10;InterfaceAlias   : Ethernet&#10;SourceAddress    : 192.168.10.22&#10;PingSucceeded    : True&#10;TcpTestSucceeded : False</pre><p><strong>Interpretação:</strong> houve resposta ao teste de alcance, mas a conexão TCP à porta 9100 não foi estabelecida. Isso não prova sozinho defeito físico da impressora; configuração, serviço, política e estado do dispositivo permanecem hipóteses.</p></div>

    <h3>Observar portas locais sem “matar processos”</h3>
    <div class="table-wrap"><table><thead><tr><th>Pergunta</th><th>Ferramenta</th><th>Use para</th><th>Limite</th></tr></thead><tbody><tr><td>Que conexões TCP esta estação mantém?</td><td><code>Get-NetTCPConnection</code></td><td>observar estado, endereço e porta locais/remotos</td><td>não identifica automaticamente causa ou legitimidade</td></tr><tr><td>Preciso de alternativa no Prompt?</td><td><code>netstat -ano</code></td><td>listar conexões/escutas e PID</td><td>PID exige correlação; não encerre processo ao acaso</td></tr><tr><td>Uma porta TCP remota aceita conexão?</td><td><code>Test-NetConnection IP -Port 9100</code></td><td>testar o destino documentado</td><td>sucesso de conexão não valida toda a função da aplicação</td></tr></tbody></table></div>
    <div class="danger-box"><strong>Porta aberta não é convite para varredura</strong><p>Teste apenas ativos e portas autorizados no escopo. Não instale scanners, não enumere a rede e não encerre serviços/processos aleatoriamente.</p></div>
    <div class="task-box"><strong>Missão 06 · mapear serviços necessários</strong><p>Registre serviço, proprietário, ativo, protocolo, porta, origem autorizada, teste, horário e resultado. Após autorização, a equipe descobre que o modo de impressão direta foi desabilitado durante manutenção da IMP-01. Reabilita a função conforme o manual, testa um documento sem dados pessoais e mantém a fila anterior preservada.</p></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>ping sim; TCP 9100 não</span></div><div class="state-step"><strong>Intervenção</strong><span>serviço reabilitado no ativo correto</span></div><div class="state-step"><strong>Depois</strong><span>TCP sim; página de teste impressa</span></div><div class="state-step"><strong>O que prova?</strong><span>serviço participou da falha; acompanhar recorrência</span></div></div>
    <div class="note-box compact"><strong>Chamado 032 atualizado</strong><p>O laboratório e a impressora tinham causas distintas. O registro evita a falsa narrativa de “uma queda geral”. matriz de serviços passa a integrar a documentação operacional.</p></div>
    <div class="bridge-box"><strong>Agora há várias ferramentas</strong><p>Para não transformá-las em catálogo, a equipe monta uma matriz: <strong>hipótese → teste que discrimina → evidência → próximo passo</strong>.</p></div>
    <details class="sources-box"><summary>Documentação oficial usada</summary><ul><li><a href="https://learn.microsoft.com/powershell/module/nettcpip/test-netconnection" target="_blank" rel="noopener noreferrer">Microsoft Learn — Test-NetConnection</a></li><li><a href="https://learn.microsoft.com/powershell/module/nettcpip/get-nettcpconnection" target="_blank" rel="noopener noreferrer">Microsoft Learn — Get-NetTCPConnection</a></li><li><a href="https://learn.microsoft.com/windows-server/administration/windows-commands/netstat" target="_blank" rel="noopener noreferrer">Microsoft Learn — netstat</a></li></ul></details>
  `
});

window.infraestruturaNetworkLessons.push({
  id: 'redes-ferramentas',
  number: '07',
  unit: 'Rede da escola · Escolher teste que separa hipóteses',
  menuTitle: 'Ferramentas de diagnóstico',
  technicalTitle: 'ipconfig • ping • arp • tracert • nslookup • Test-NetConnection • correlação',
  title: 'Não cole comandos: formule perguntas',
  objective: 'Selecionar e interpretar ferramentas Windows como testes de hipóteses, documentando resultado esperado, observado e limite.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Reunião de passagem · Joana assume o plantão</span><h2>Os registros têm saídas de comandos, mas algumas não dizem por que foram executadas.</h2><p>Caio anotou “ping ok” sem origem, destino ou horário. Ana salvou um <code>ipconfig</code>, mas não indicou a interface usada. Joana não consegue continuar o raciocínio. O problema não é falta de comandos: é falta de perguntas e correlação.</p></div>

    <div class="command-board"><div class="command-card"><strong><code>ipconfig /all</code></strong><span>Pergunta: que configuração esta interface recebeu?</span><small>Não prova disponibilidade de destino.</small></div><div class="command-card"><strong><code>ping destino</code></strong><span>Pergunta: há resposta ICMP neste momento?</span><small>Ausência pode ser filtro; resposta não valida serviço.</small></div><div class="command-card"><strong><code>arp -a</code></strong><span>Pergunta: que vizinhos IPv4 locais foram aprendidos?</span><small>A tabela depende de tráfego e tempo; não é inventário completo.</small></div><div class="command-card"><strong><code>tracert destino</code></strong><span>Pergunta: que saltos respondem no caminho?</span><small>“*” não prova que o salto deixou de encaminhar.</small></div><div class="command-card"><strong><code>nslookup nome</code></strong><span>Pergunta: qual DNS respondeu e com quê?</span><small>Resposta DNS não valida a aplicação.</small></div><div class="command-card"><strong><code>Test-NetConnection -Port</code></strong><span>Pergunta: a conexão TCP documentada é estabelecida?</span><small>Não serve para testar qualquer porta sem autorização.</small></div></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Sequência de decisão</span><h3>Escolha o próximo teste que mais separa as hipóteses</h3><p>O usuário diz: “a intranet não abre”. A configuração ainda não foi coletada.</p></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="diagnostic-flow"><div><strong>1 · Delimite</strong><span>origem, destino, serviço, horário</span></div><div><strong>2 · Leia o estado</strong><span>interface e <code>ipconfig /all</code></span></div><div><strong>3 · Compare alcance</strong><span>local, gateway e destino</span></div><div><strong>4 · Teste a função</strong><span>nome e porta autorizada</span></div><div><strong>5 · Registre</strong><span>observado, limite e próximo teste</span></div></div><p class="visual-question"><strong>Por que não começar com tracert?</strong> Porque, sem saber interface e configuração, ele produz uma saída difícil de interpretar e pode pular uma diferença local simples.</p></div></div>

    <section class="checkpoint" data-quiz-group><span class="eyebrow">Interpretação de evidência</span><h3>Qual próximo teste tem melhor poder de discriminação?</h3>
      <div class="quiz-item" data-quiz-question data-answer="b" data-explanation="Se o IP abre e o nome não, consultar o DNS e registrar servidor/resposta separa resolução de disponibilidade do serviço."><p>1. A intranet abre por IP, mas não por nome.</p><label><input type="radio" name="r07a" value="a"> Reiniciar SW-01.</label><label><input type="radio" name="r07a" value="b"> Executar <code>nslookup</code> para o nome e comparar o DNS com estado de rede.</label><label><input type="radio" name="r07a" value="c"> Trocar o cabo de todos.</label></div>
      <div class="quiz-item" data-quiz-question data-answer="c" data-explanation="O ping só testa uma condição específica; o serviço pode falhar apesar da resposta ICMP."><p>2. O ping à IMP-01 responde. O que isso permite concluir?</p><label><input type="radio" name="r07b" value="a"> A impressão está normal.</label><label><input type="radio" name="r07b" value="b"> A porta 9100 está aberta.</label><label><input type="radio" name="r07b" value="c"> Houve resposta ao teste de alcance; a função ainda precisa de teste próprio.</label></div>
      <div class="quiz-item" data-quiz-question data-answer="a" data-explanation="Uma entrada ARP indica associação aprendida localmente e deve ser correlacionada; não comprova identidade, saúde ou autorização do dispositivo."><p>3. <code>arp -a</code> mostra um IP/MAC. Isso prova que é um ativo autorizado e saudável?</p><label><input type="radio" name="r07c" value="a"> Não; é uma associação observada, não uma validação completa.</label><label><input type="radio" name="r07c" value="b"> Sim, toda entrada ARP é confiável.</label><label><input type="radio" name="r07c" value="c"> Sim, desde que seja dinâmica.</label></div>
      <button class="action-button primary" type="button" data-check-quiz>Conferir raciocínio</button><div class="quiz-result" data-quiz-result aria-live="polite"></div>
    </section>

    <div class="task-box"><strong>Missão 07 · escolher hipótese, previsão e teste</strong><p>Receba três cartões de incidente. Para cada um, escreva hipótese principal e alternativa, teste escolhido, previsão para cada hipótese, evidência observada, interpretação e próximo passo. Ganhe crédito por <strong>não executar</strong> um comando que não separa as hipóteses.</p></div>
    <div class="note-box compact"><strong>Padrão de registro adotado</strong><p><strong>Pergunta → contexto/origem → comando → previsão → saída relevante → interpretação → limite → próximo teste.</strong> Essa matriz hipótese–teste será reutilizada na passagem de plantão.</p></div>
    <div class="bridge-box"><strong>Chamado 036 · visitante acessou a administração da impressora</strong><p>A rede funciona, mas a topologia lógica não expressa quem deveria alcançar o quê. O plano de endereçamento já propôs grupos; agora a escola precisa avaliar <strong>segmentação e política</strong>.</p></div>
    <details class="sources-box"><summary>Documentação oficial usada</summary><ul><li><a href="https://learn.microsoft.com/windows-server/administration/windows-commands/windows-commands" target="_blank" rel="noopener noreferrer">Microsoft Learn — referência de comandos do Windows</a></li><li><a href="https://learn.microsoft.com/windows-server/administration/windows-commands/arp" target="_blank" rel="noopener noreferrer">Microsoft Learn — arp</a></li></ul></details>
  `
});
