window.infraestruturaNetworkLessons = Array.isArray(window.infraestruturaNetworkLessons) ? window.infraestruturaNetworkLessons : [];

window.infraestruturaNetworkLessons.push({
  id: 'redes-vlan',
  number: '08',
  unit: 'Rede da escola · Separar por necessidade e aplicar política',
  menuTitle: 'Segmentação e VLANs',
  technicalTitle: 'VLAN • sub-rede • domínio de broadcast • roteamento entre VLANs • ACL/firewall • rollback',
  title: 'Visitante não precisa alcançar a administração da impressora',
  objective: 'Projetar uma segmentação coerente com pessoas e serviços, distinguindo separação lógica de controle efetivo de acesso.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Chamado 036 · evento de famílias</span><h2>Um visitante abriu a página administrativa da IMP-01.</h2><p>A pessoa não alterou configurações, mas o acesso expôs uma falha de projeto. O mapa e inventário mostra todos no mesmo domínio lógico; o plano de endereçamento já separa funcionários, laboratório e visitantes em faixas. Ana precisa imprimir, Caio e os alunos usam a intranet pedagógica, visitantes precisam apenas de internet. O risco agora tem sujeitos, ativos e fluxos concretos.</p></div>
    <div class="danger-box"><strong>VLAN não é sinônimo de segurança</strong><p>Ela cria separação lógica em camada 2. Quando há roteamento entre VLANs, políticas no roteador/firewall determinam o que passa. Credenciais, atualização, proteção do serviço e administração segura continuam necessárias.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Representação didática</span><h3>Do plano de endereçamento à matriz de acesso</h3><p>As cores mostram grupos; as setas permitidas dependem de política documentada.</p></div><div class="visual-body"><span class="representation-badge">Diagrama próprio · não é tela de switch</span><div class="vlan-map">
      <div class="vlan-zone staff"><strong>VLAN 10 · Funcionários</strong><span>192.168.10.0/26</span><small>SEC-02 · ADM-01 · IMP-01</small></div>
      <div class="vlan-zone lab"><strong>VLAN 20 · Laboratório</strong><span>192.168.10.64/26</span><small>LAB-06 e estações de alunos</small></div>
      <div class="vlan-zone guest"><strong>VLAN 30 · Visitantes</strong><span>192.168.10.128/26</span><small>dispositivos não gerenciados</small></div>
      <div class="policy-gate"><strong>RTR-01 · política entre redes</strong><span>nega por padrão o que não foi justificado</span></div>
    </div><p class="visual-question"><strong>Decida:</strong> em qual grupo IMP-01 deve ficar? Quais origens realmente precisam imprimir? “Visitantes → internet” exige acesso a SEC-02?</p></div></div>

    <div class="table-wrap"><table><thead><tr><th>Origem</th><th>Destino/função</th><th>Necessidade</th><th>Decisão proposta</th><th>Validação</th></tr></thead><tbody><tr><td>Funcionários</td><td>IMP-01 TCP 9100</td><td>atendimento</td><td>permitir</td><td>página de teste autorizada</td></tr><tr><td>Laboratório</td><td>intranet pedagógica</td><td>aulas</td><td>permitir porta documentada</td><td>abrir função real</td></tr><tr><td>Visitantes</td><td>internet</td><td>evento</td><td>permitir saída necessária</td><td>navegação de referência</td></tr><tr><td>Visitantes</td><td>IMP-01 / SEC-02</td><td>nenhuma</td><td>negar e registrar</td><td>teste falha como previsto</td></tr></tbody></table></div>

    <div class="task-box"><strong>Missão 08 · planejar segmentação e acesso</strong><ol><li>Reutilize o mapa e inventário, o plano de endereçamento e a matriz de serviços para listar pessoas, ativos e serviços.</li><li>Preencha a matriz antes de configurar.</li><li>Em equipamento didático ou simulador de laboratório, associe uma porta de acesso a cada VLAN e o SSID visitante à VLAN 30. Não use a rede de produção.</li><li>Aplique política mínima no gateway didático, teste permitido e negado e registre ambos.</li><li>Rollback: exporte/salve a configuração anterior, anote portas e restaure o cenário de laboratório se a validação falhar.</li></ol></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>visitante alcança IMP-01</span></div><div class="state-step"><strong>Intervenção</strong><span>VLAN + rota/política controlada</span></div><div class="state-step"><strong>Depois</strong><span>internet sim; IMP-01 não</span></div><div class="state-step"><strong>O que prova?</strong><span>o fluxo testado foi bloqueado; não prova segurança total</span></div></div>

    <section class="checkpoint compact-check" data-quiz-group><div class="quiz-item" data-quiz-question data-answer="b" data-explanation="VLANs separam domínios lógicos; o tráfego entre eles depende de roteamento e das políticas aplicadas."><p>O visitante ficou na VLAN 30. Isso basta para proteger IMP-01?</p><label><input type="radio" name="r08a" value="a"> Sim, VLAN é firewall.</label><label><input type="radio" name="r08a" value="b"> Não; é preciso controlar e validar o tráfego entre redes.</label><label><input type="radio" name="r08a" value="c"> Sim, se o nome da VLAN for “segura”.</label></div><button class="action-button primary" type="button" data-check-quiz>Conferir</button><div class="quiz-result" data-quiz-result aria-live="polite"></div></section>
    <div class="note-box compact"><strong>Plano de segmentação e acesso</strong><p>Inclui topologia lógica, associação porta/SSID, matriz, estado anterior, testes positivos e negativos, responsável e retorno. A implantação real permanece pendente de janela e equipamento compatível.</p></div>
    <div class="bridge-box"><strong>A segmentação chega ao rádio</strong><p>O SSID visitante precisa alcançar seu grupo, mas o <strong>Chamado 037</strong> informa quedas em SALA-04 durante aulas cheias. Antes de mover AP-01, a escola precisa medir ambiente, cobertura e capacidade.</p></div>
    <details class="sources-box"><summary>Referências técnicas</summary><ul><li><a href="https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst6500/ios/15-4SY/config_guide/sup6T/15_3_sy_swcg_6T/vlans.html" target="_blank" rel="noopener noreferrer">Cisco — VLAN overview</a></li><li><a href="https://www.cisco.com/c/en/us/tech/lan-switching/virtual-lans-vlan-trunking-protocol-vlans-vtp/index.html" target="_blank" rel="noopener noreferrer">Cisco — Virtual LANs e 802.1Q</a></li></ul></details>
  `
});

window.infraestruturaNetworkLessons.push({
  id: 'redes-wifi',
  number: '09',
  unit: 'Rede da escola · Medir o ambiente sem fio',
  menuTitle: 'Wi-Fi no ambiente real',
  technicalTitle: 'cobertura • capacidade • 2,4 GHz • 5 GHz • canal • obstáculos • clientes • segurança',
  title: 'O sinal existe, mas a aula cheia não funciona',
  objective: 'Investigar Wi-Fi por local, horário, banda e carga, evitando conclusões universais sobre alcance e frequência.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Chamado 037 · SALA-04 · 13h40</span><h2>Com cinco alunos a atividade funciona; com vinte e oito, vídeos pausam e sessões caem.</h2><p>AP-01 está no corredor, atrás de uma parede estrutural em relação à SALA-04. Pela manhã, Joana mediu conexão estável perto da porta. À tarde, Caio registrou o sintoma no fundo da sala com 28 clientes. A foto de reconhecimento físico usada no levantamento ajuda a reconhecer o equipamento, mas somente uma medição distribuída explica o uso.</p></div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Representação didática do pavimento</span><h3>Posição, obstáculo e ocupação</h3><p>Os círculos são pontos de medição, não promessa de “alcance”.</p></div><div class="visual-body"><span class="representation-badge">Planta simplificada · não é mapa de calor medido</span><div class="wifi-plan" role="img" aria-label="Corredor com ponto de acesso AP-01, sala 04 atrás de parede estrutural, três pontos de medição A, B e C e laboratório ao lado"><div class="hall">Corredor <b>AP-01</b></div><div class="wall">parede estrutural</div><div class="room"><strong>SALA-04</strong><span class="measure a">A · porta</span><span class="measure b">B · centro</span><span class="measure c">C · fundo</span><small>28 clientes no horário crítico</small></div><div class="lab-room">Laboratório<br><small>atividade simultânea</small></div></div><p class="visual-question"><strong>Planeje:</strong> medir apenas no ponto A e com a sala vazia representa o sintoma? Qual variável deve permanecer igual ao comparar bandas?</p></div></div>

    <div class="table-wrap"><table><thead><tr><th>Ponto/horário</th><th>Clientes</th><th>Banda</th><th>Sinal observado</th><th>Teste de função</th><th>Interpretação limitada</th></tr></thead><tbody><tr><td>A · 9h</td><td>5</td><td>5 GHz</td><td>forte</td><td>atividade estável</td><td>referência próxima e baixa carga</td></tr><tr><td>B · 13h40</td><td>28</td><td>5 GHz</td><td>médio</td><td>pausas</td><td>carga e posição participam</td></tr><tr><td>C · 13h40</td><td>28</td><td>5 GHz</td><td>fraco</td><td>sessões caem</td><td>obstáculo/distância fortalecem hipótese</td></tr><tr><td>C · 13h55</td><td>28</td><td>2,4 GHz</td><td>médio</td><td>estável, menor taxa</td><td>maior alcance útil aqui; não é “melhor” sempre</td></tr></tbody></table></div>

    <div class="two-col"><div class="definition-box"><strong>2,4 GHz no caso</strong><p>Chegou melhor ao fundo, porém costuma ter menos canais disponíveis e mais fontes de interferência. Resultado depende do ambiente.</p></div><div class="definition-box"><strong>5 GHz no caso</strong><p>Ofereceu melhor desempenho perto do AP, mas perdeu nível através do obstáculo. Não é automaticamente superior ou inferior.</p></div></div>
    <div class="task-box"><strong>Missão 09 · medir o Wi-Fi nas condições reais</strong><ol><li>Defina o sintoma reproduzível e o horário de maior uso.</li><li>Meça A, B e C com o mesmo equipamento e a mesma função; anote banda, canal, sinal, clientes e horário.</li><li>No Windows autorizado, <code>netsh wlan show interfaces</code> pode registrar interface, rádio, canal e sinal. Use-o para observar, não para alterar perfis.</li><li>Compare uma variável por vez e não divulgue chaves ou perfis.</li><li>Proponha posicionamento/capacidade e segurança; a mudança real exige planejamento e nova medição.</li></ol></div>
    <div class="danger-box"><strong>Segurança e privacidade</strong><p>Não exporte perfis Wi-Fi com chaves, não faça captura de tráfego de usuários e não instale AP improvisado. Use SSID de laboratório e dados sem identificação pessoal.</p></div>
    <div class="state-comparison"><div class="state-step"><strong>Antes</strong><span>C falha com 28 clientes</span></div><div class="state-step"><strong>Intervenção-piloto</strong><span>AP didático reposicionado e canais revistos</span></div><div class="state-step"><strong>Depois</strong><span>A/B/C repetidos no mesmo horário</span></div><div class="state-step"><strong>O que prova?</strong><span>melhora nas condições medidas; requer acompanhamento</span></div></div>
    <div class="note-box compact"><strong>O levantamento Wi-Fi completa o mapa da rede</strong><p>O mapa passa a registrar AP, cabo/porta, SSIDs, grupo lógico, pontos de referência e data do levantamento. A direção recebe uma proposta, não uma promessa de alcance universal.</p></div>
    <div class="bridge-box"><strong>Próxima competência</strong><p>Os chamados agora misturam meio físico, configuração, caminho, nome, serviço, política e rádio. Na passagem de plantão, a equipe precisa escolher <strong>o próximo teste mais informativo</strong> em incidentes integrados.</p></div>
    <details class="sources-box"><summary>Documentação oficial usada</summary><ul><li><a href="https://learn.microsoft.com/windows-server/administration/windows-commands/netsh-wlan" target="_blank" rel="noopener noreferrer">Microsoft Learn — netsh wlan</a></li><li><a href="https://learn.microsoft.com/troubleshoot/windows-client/networking/wireless-network-connectivity-issues-troubleshooting" target="_blank" rel="noopener noreferrer">Microsoft Learn — coleta de informações para problemas Wi-Fi</a></li><li><a href="https://www.cisco.com/c/en/us/td/docs/wireless/controller/9800/technical-reference/wireless-rf-reference-guide.html" target="_blank" rel="noopener noreferrer">Cisco — Wireless RF Reference Guide</a></li></ul></details>
  `
});

window.infraestruturaNetworkLessons.push({
  id: 'redes-diagnostico-integrado',
  number: '10',
  unit: 'Rede da escola · Diagnóstico integrado',
  menuTitle: 'Resolver sem adivinhar',
  technicalTitle: 'escopo • camada • hipótese • teste discriminante • antes/depois • conclusão limitada',
  title: 'Escolha o teste que muda a decisão',
  objective: 'Integrar os registros acumulados da rede para diagnosticar incidentes em camadas, evitando ações amplas e conclusões além da evidência.',
  content: `
    <div class="hero-box story-opening"><span class="eyebrow">Passagem do plantão · quatro ocorrências</span><h2>Nem todo “sem rede” começa — ou termina — no mesmo lugar.</h2><p>Joana recebe os registros abaixo e todos os artefatos as seções acumuladas do Registro da Rede. Ela não ganha pontos por executar mais comandos: precisa justificar qual teste separa melhor as hipóteses, preservar o estado e deixar o próximo responsável capaz de continuar.</p></div>

    <div class="evidence-switcher" data-evidence-switcher><div class="switcher-buttons"><button type="button" data-evidence-view="a" aria-pressed="true">Caso A · link</button><button type="button" data-evidence-view="b" aria-pressed="false">Caso B · nomes</button><button type="button" data-evidence-view="c" aria-pressed="false">Caso C · serviço</button><button type="button" data-evidence-view="d" aria-pressed="false">Caso D · Wi-Fi</button></div>
      <div class="evidence-panel" data-evidence-panel="a"><h4>LAB-06 · após limpeza</h4><p>Ícone indica cabo desconectado; LED da porta 08 apagado; demais PCs funcionam. <strong>Próximo teste:</strong> inspecionar conector/caminho e comparar cabo de referência na mesma porta, preservando o mapa de portas e cabos.</p></div>
      <div class="evidence-panel" data-evidence-panel="b" hidden><h4>ADM-01 · IP funciona, nome não</h4><p>Gateway e intranet por IP respondem; o estado de rede diverge apenas no DNS. <strong>Próximo teste:</strong> <code>nslookup</code> com registro do servidor consultado e resposta.</p></div>
      <div class="evidence-panel" data-evidence-panel="c" hidden><h4>SEC-02 · servidor alcançável, aplicação não</h4><p>Ping responde; a matriz de serviços informa o serviço TCP específico. <strong>Próximo teste:</strong> testar apenas a porta documentada e comparar com uma origem que funciona.</p></div>
      <div class="evidence-panel" data-evidence-panel="d" hidden><h4>SALA-04 · falha só em aula cheia</h4><p>Teste vazio perto da porta não reproduz. <strong>Próximo teste:</strong> repetir o levantamento Wi-Fi em horário, pontos e carga comparáveis.</p></div>
    </div>

    <div class="visual-lab"><div class="visual-lab-header"><span class="visual-kicker">Mapa de decisão</span><h3>Do sintoma à conclusão limitada</h3><p>Volte um passo sempre que faltar evidência.</p></div><div class="visual-body"><span class="representation-badge">Diagrama próprio</span><div class="diagnostic-flow"><div><strong>Entender</strong><span>origem, destino, função e impacto</span></div><div><strong>Experimentar</strong><span>prever e testar com baixo risco</span></div><div><strong>Analisar</strong><span>comparar esperado e observado</span></div><div><strong>Aplicar</strong><span>uma mudança autorizada</span></div><div><strong>Validar</strong><span>repetir função e registrar limite</span></div></div></div></div>

    <section class="checkpoint" data-quiz-group><span class="eyebrow">Decisão baseada em evidência</span><h3>O que fazer — e o que não concluir?</h3>
      <div class="quiz-item" data-quiz-question data-answer="b" data-explanation="A diferença entre uma origem funcional e outra que falha, no mesmo serviço e horário, ajuda a localizar o problema com menor risco."><p>1. Um serviço funciona em SEC-02 e falha em ADM-01. Qual comparação é mais útil?</p><label><input type="radio" name="r10a" value="a"> Reiniciar RTR-01.</label><label><input type="radio" name="r10a" value="b"> Comparar interface, configuração, caminho e teste da porta nas duas origens.</label><label><input type="radio" name="r10a" value="c"> Alterar DNS, cabo e firewall ao mesmo tempo.</label></div>
      <div class="quiz-item" data-quiz-question data-answer="c" data-explanation="A ausência após uma mudança fortalece a relação nas condições medidas, mas duração e recorrência limitam a conclusão."><p>2. Após trocar o cabo, o sintoma não reaparece por 15 minutos. Como registrar?</p><label><input type="radio" name="r10b" value="a"> Causa definitivamente provada.</label><label><input type="radio" name="r10b" value="b"> Rede totalmente corrigida.</label><label><input type="radio" name="r10b" value="c"> Sintoma ausente por 15 minutos na condição repetida; cabo anterior permanece suspeito e requer destinação.</label></div>
      <div class="quiz-item" data-quiz-question data-answer="a" data-explanation="Se a intervenção ultrapassa autorização, equipamento ou competência, parar e encaminhar com evidência preserva segurança e continuidade."><p>3. A hipótese exige mudar o switch de produção sem backup da configuração.</p><label><input type="radio" name="r10c" value="a"> Não alterar; documentar risco e encaminhar para janela/responsável.</label><label><input type="radio" name="r10c" value="b"> Testar rapidamente antes que alguém perceba.</label><label><input type="radio" name="r10c" value="c"> Resetar o switch para obter um estado conhecido.</label></div>
      <button class="action-button primary" type="button" data-check-quiz>Conferir raciocínio</button><div class="quiz-result" data-quiz-result aria-live="polite"></div>
    </section>

    <div class="task-box"><strong>Missão 10 · mini-plantão em equipe</strong><p>Escolha um caso, preencha a matriz hipótese–teste, cite os artefatos anteriores que sustentam a previsão, execute somente o teste autorizado e entregue uma passagem de turno de 90 segundos: impacto, estado atual, evidência, hipótese, ação realizada, limite e próximo passo.</p></div>
    <div class="note-box compact"><strong>Registro da Rede</strong><p>As seções do Registro da Rede não são exercícios descartáveis. Juntas, formam memória operacional: quem usa, o que existe, como se conecta, quais serviços são necessários, qual estado é referência e o que mudou.</p></div>
    <div class="essence"><strong>Essência</strong><p>O melhor teste não é o mais sofisticado; é o que, com baixo risco, <strong>muda a força das hipóteses e orienta a próxima decisão</strong>.</p></div>
    <div class="bridge-box"><strong>Oficina 99</strong><p>O plantão final entrega documentação parcial e falhas controladas. A equipe terá de reconstruir o contexto, investigar, corrigir apenas quando autorizado, validar e produzir um relatório que outro técnico consiga usar.</p></div>
  `
});
