(() => {
  'use strict';

  const MBB = window.MBBPhysics = window.MBBPhysics || {};
  const $ = (selector, root = document) => root.querySelector(selector);

  const lessonHtml = `
    <section class="physics-opening">
      <span class="lesson-kicker">Uma história para investigar</span>
      <div class="hero-box physics-story">
        <strong class="card-title">À noite, o clube de ciências da escola organiza uma observação no pátio. O professor monta o telescópio para observar a Lua e consulta um aplicativo de mapa do céu, que indica o horário e a direção da passagem de um satélite.</strong>
        <p>Enquanto o grupo espera, o professor solta uma pequena bola a partir da altura da mão: ela cai imediatamente. Pouco depois, o satélite aparece como um ponto luminoso atravessando o céu. A Lua também continua em sua trajetória ao redor da Terra.</p>
        <div class="quick-question" data-choice-question data-correct="b"><strong>Antes de continuar, faça uma aposta</strong><p>Se a gravidade puxa a bola para a Terra, por que o satélite e a Lua não caem diretamente no chão?</p><div class="choice-row"><button type="button" data-choice="a">Porque fora da atmosfera não existe gravidade</button><button type="button" data-choice="b">Porque eles têm movimento lateral e a gravidade curva continuamente sua trajetória</button><button type="button" data-choice="c">Porque objetos no espaço deixam de ter massa</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. A gravidade continua atuando; o movimento lateral faz com que a queda se transforme em uma trajetória orbital." data-wrong-text="Não retire a gravidade da situação. Compare uma queda vertical com um corpo que também possui grande velocidade lateral."></div></div>
        <p class="central-question"><strong>Nossa missão:</strong> explicar claramente essa diferença entre cair e orbitar e, a partir dela, ampliar a escala até as órbitas planetárias, a expansão do Universo e a relatividade geral.</p>
      </div>
    </section>

    <section>
      <h3>1. A bola cai no chão; o satélite está caindo ao redor da Terra</h3>
      <p>A Terra atrai a bola, o satélite e a Lua. A diferença não é a presença ou ausência de gravidade. A diferença está na combinação entre <strong>atração gravitacional e velocidade</strong>.</p>
      <p>Imagine um objeto lançado horizontalmente de uma grande altura. Com pouca velocidade lateral, ele cai e atinge a superfície. Se sua velocidade lateral for suficientemente grande e desconsiderarmos a atmosfera e obstáculos, enquanto ele cai a superfície curva da Terra também se afasta abaixo dele. O resultado pode ser uma <strong>queda contínua ao redor da Terra</strong>: uma órbita.</p>
      <div class="note-box"><strong>Resposta à pergunta do início</strong><p>O satélite não está fora do alcance da gravidade. Pelo contrário: a gravidade fornece a aceleração que muda continuamente a direção de sua velocidade e curva a trajetória. A Lua também permanece em movimento orbital pela interação gravitacional com a Terra.</p></div>
      <div class="note-box"><strong>E por que astronautas parecem flutuar?</strong><p>Uma estação orbital e seus ocupantes caem juntos ao redor da Terra. Como não existe um piso sustentando o astronauta da mesma forma que no chão, a sensação é de aparente ausência de peso, embora a gravidade continue atuando.</p></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>Conecte com o movimento circular</strong><p>Por que uma órbita aproximadamente circular possui aceleração mesmo quando o módulo da velocidade permanece quase constante?</p><div class="choice-row"><button type="button" data-choice="a">Porque o tempo fica mais lento automaticamente</button><button type="button" data-choice="b">Porque a massa do satélite aumenta</button><button type="button" data-choice="c">Porque a direção da velocidade muda continuamente</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. Velocidade é vetorial: mudar sua direção significa acelerar." data-wrong-text="Retome a ideia de que uma curva exige mudança contínua da direção da velocidade."></div></div>
    </section>

    <section>
      <h3>2. Se a gravidade alcança a Lua, por que ela fica mais fraca com a distância?</h3>
      <p>A Lua está muito mais distante do centro da Terra do que a bola que caiu no pátio. A interação gravitacional continua existindo, mas sua intensidade depende da distância entre os corpos.</p>
      <p>Na descrição de Newton, a força gravitacional depende das duas massas e da distância <strong>r</strong> entre seus centros.</p>
      <div class="equation-walk"><div><span>1</span><p>Aumentar uma das massas aumenta a interação gravitacional.</p></div><div><span>2</span><p>Aumentar a distância reduz a força gravitacional.</p></div><div><span>3</span><p>A distância aparece ao quadrado: a força varia com <strong>1/r²</strong>.</p></div></div>
      <div class="formula-box"><span class="formula-name">Lei da Gravitação Universal</span><div class="big-formula">F = G · m₁ · m₂ / r²</div><p><strong>G</strong> é a constante gravitacional; m₁ e m₂ são as massas; r é a distância entre os centros dos corpos.</p></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>Faça a previsão</strong><p>Se a distância entre dois corpos dobra e as massas permanecem iguais, a força gravitacional passa a ser:</p><div class="choice-row"><button type="button" data-choice="a">duas vezes maior</button><button type="button" data-choice="b">metade</button><button type="button" data-choice="c">um quarto</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. Se r dobra, r² fica quatro vezes maior e a força cai para 1/4." data-wrong-text="Observe o quadrado no denominador de F = Gm₁m₂/r²."></div></div>
      <div class="note-box"><strong>Então por que a Lua não escapa?</strong><p>A força gravitacional na distância da Lua é menor do que perto da superfície terrestre, mas não é zero. Ela é suficiente para alterar continuamente a velocidade da Lua e manter sua trajetória orbital em torno da Terra.</p></div>
    </section>

    <section>
      <h3>3. Para entender os planetas, o grupo olha registros feitos ao longo de muitos anos</h3>
      <p>Uma única noite de telescópio não revela a forma completa de uma órbita planetária. Foi comparando posições registradas durante longos períodos que astrônomos encontraram padrões no movimento dos planetas. Johannes Kepler expressou esses padrões em três leis.</p>
      <div class="three-col"><div class="example-box"><strong class="card-title">1ª lei — órbitas</strong><p>Os planetas descrevem órbitas elípticas, com o Sol em um dos focos.</p></div><div class="example-box"><strong class="card-title">2ª lei — áreas</strong><p>A linha que liga o planeta ao Sol varre áreas iguais em tempos iguais. O planeta se move mais rapidamente quando está mais perto do Sol.</p></div><div class="example-box"><strong class="card-title">3ª lei — períodos</strong><p>Para corpos que orbitam o mesmo centro, órbitas maiores estão associadas a períodos orbitais maiores.</p></div></div>
      <div class="formula-box"><span class="formula-name">Terceira Lei de Kepler, para o mesmo corpo central</span><div class="big-formula">T² ∝ a³</div><p><strong>T</strong> é o período orbital e <strong>a</strong> é o semieixo maior da órbita.</p></div>
      <div class="example-box"><strong class="card-title">O que a proporcionalidade permite prever?</strong><p>Se, em um modelo comparativo, o semieixo maior ficar 4 vezes maior, então T² cresce por 4³ = 64. Logo, T cresce por √64 = <strong>8 vezes</strong>.</p></div>
      <div class="note-box"><strong>Kepler descreveu o padrão; Newton ajudou a explicar a causa</strong><p>As leis de Kepler organizam regularidades observadas nas órbitas. A gravitação de Newton mostrou como uma mesma interação gravitacional pode explicar tanto quedas próximas da Terra quanto movimentos orbitais.</p></div>
    </section>

    <section>
      <h3>4. Laboratório: afaste uma órbita e observe o que muda</h3>
      <p>No modelo abaixo, mantemos o mesmo corpo central e comparamos órbitas circulares de raios relativos diferentes. Assim podemos observar, separadamente, como mudam a força gravitacional, a velocidade orbital circular e o período.</p>
      <div class="interactive-lab" id="orbitLab"><div class="lab-heading"><span class="lesson-kicker">Laboratório interativo</span><h4>Afaste a órbita e faça uma previsão antes de olhar os números</h4></div><div class="lab-controls"><label>Distância orbital relativa <strong><span id="orbitRadiusValue">1,00</span> r</strong><input id="orbitRadiusRange" type="range" min="1" max="5" step="0.25" value="1"></label></div><svg class="lesson-visual" id="orbitLabSvg" viewBox="0 0 760 300" role="img" aria-label="Simulação de uma órbita circular cuja distância pode ser alterada"><circle cx="380" cy="150" r="32" fill="#f6c453"/><circle id="orbitPath" cx="380" cy="150" r="70" fill="none" stroke="#aab9ca" stroke-width="3" stroke-dasharray="8 7"/><circle id="orbitPlanet" cx="450" cy="150" r="13" fill="#1967d2"/><text x="350" y="158" class="visual-note">Sol</text></svg><div class="lab-result" aria-live="polite"><span>Força gravitacional relativa:</span><strong id="relativeGravityValue">1,00</strong><span>Velocidade orbital relativa:</span><strong id="relativeSpeedValue">1,00</strong><span>Período orbital relativo:</span><strong id="relativePeriodValue">1,00</strong></div><p id="orbitConclusion">Perto do corpo central, a atração é mais intensa e o período orbital é menor.</p></div>
      <div class="note-box"><strong>O que o modelo está mostrando?</strong><p>Para órbitas circulares em torno do mesmo corpo central, aumentar r reduz a atração segundo 1/r², reduz a velocidade orbital segundo 1/√r e aumenta o período segundo r<sup>3/2</sup>.</p></div>
    </section>

    <section>
      <h3>5. A observação termina, mas surge uma pergunta maior: o Universo sempre foi assim?</h3>
      <p>Depois de discutir Lua e planetas, o professor mostra imagens de galáxias distantes. A pergunta muda de escala: em vez de acompanhar um corpo em órbita, queremos compreender a história do próprio Universo.</p>
      <p>O modelo cosmológico do <strong>Big Bang</strong> descreve um Universo que, no passado, esteve em um estado extremamente quente e denso e que se expandiu e evoluiu ao longo do tempo.</p>
      <div class="note-box"><strong>Big Bang não é uma bomba explodindo dentro de um espaço vazio</strong><p>Essa imagem produz uma ideia errada. Na descrição cosmológica, a expansão envolve o próprio espaço em grande escala. Não é necessário imaginar um ponto central lançando matéria para dentro de um espaço que já existia pronto.</p></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>Qual descrição é mais adequada?</strong><p>Em nível introdutório, o Big Bang é melhor entendido como:</p><div class="choice-row"><button type="button" data-choice="a">uma explosão comum ocorrida em um ponto central do espaço</button><button type="button" data-choice="b">a evolução de um Universo antes muito quente e denso, com expansão em grande escala</button><button type="button" data-choice="c">uma única galáxia que se dividiu e formou todas as outras</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. O modelo descreve a evolução e a expansão do Universo, não uma explosão comum em um centro espacial." data-wrong-text="Evite imaginar o Big Bang como uma bomba explodindo dentro de um espaço vazio já existente."></div></div>
    </section>

    <section>
      <h3>6. Como podemos afirmar que o Universo se expandiu?</h3>
      <p>Um modelo cosmológico precisa ser confrontado com observações. A ideia de um Universo em expansão e com um passado quente e denso é sustentada por diferentes conjuntos de evidências que se complementam.</p>
      <div class="three-col"><div class="example-box"><strong class="card-title">Espectros de galáxias</strong><p>Em grande escala, a luz de galáxias distantes apresenta padrões de desvio espectral compatíveis com a expansão cosmológica.</p></div><div class="example-box"><strong class="card-title">Radiação cósmica de fundo</strong><p>Uma radiação muito antiga permeia o Universo e corresponde a uma importante evidência de seu passado quente e denso.</p></div><div class="example-box"><strong class="card-title">Elementos leves</strong><p>As abundâncias observadas de certos elementos leves são compatíveis com previsões de processos ocorridos no Universo primordial.</p></div></div>
      <div class="note-box"><strong>O que significa “modelo cosmológico”?</strong><p>É uma representação científica usada para descrever a estrutura e a evolução do Universo e produzir previsões que podem ser comparadas com observações. Um modelo não é aceito apenas por parecer plausível; ele precisa ser testado pelas evidências disponíveis.</p></div>
      <div class="note-box"><strong>Uma analogia com limite</strong><p>Pontos desenhados num balão que infla podem ajudar a visualizar distâncias crescendo entre vários pontos ao mesmo tempo. A analogia serve apenas para essa ideia: o Universo não precisa ser literalmente a superfície de um balão.</p></div>
    </section>

    <section>
      <h3>7. Se Newton explica órbitas tão bem, por que precisamos da relatividade geral?</h3>
      <p>A gravitação de Newton descreve com excelente precisão uma enorme variedade de situações. Mas ela não é a descrição mais geral da gravidade. Na <strong>relatividade geral</strong>, Einstein relacionou matéria e energia à geometria do espaço-tempo.</p>
      <p>Isso não torna Newton “inútil” ou simplesmente “errado”. Em campos gravitacionais não extremos e nas precisões usuais de muitos problemas, a teoria newtoniana funciona como uma excelente aproximação. A relatividade geral torna-se necessária quando os efeitos relativísticos não podem ser desprezados ou quando buscamos uma descrição gravitacional mais geral.</p>
      <div class="two-col"><div class="example-box"><strong class="card-title">Newton</strong><p>Descreve a gravidade como uma interação entre massas e permite calcular com grande eficiência muitos movimentos e órbitas.</p></div><div class="example-box"><strong class="card-title">Einstein</strong><p>Descreve a gravidade em termos da geometria do espaço-tempo e constitui uma teoria mais geral.</p></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>Então por que continuamos usando Newton?</strong><p>Qual resposta é mais adequada?</p><div class="choice-row"><button type="button" data-choice="a">Porque a relatividade geral foi abandonada</button><button type="button" data-choice="b">Porque Newton é exato em qualquer situação</button><button type="button" data-choice="c">Porque a teoria newtoniana é uma excelente aproximação em muitos domínios</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. Modelos e teorias podem ter diferentes domínios de validade e níveis de precisão." data-wrong-text="Uma teoria mais geral não torna inútil uma aproximação que funciona muito bem em seu domínio."></div></div>
    </section>

    <section>
      <h3>8. Volte à primeira cena: afinal, por que a bola cai e a Lua não atinge a Terra?</h3>
      <p>A bola solta da mão praticamente não possui velocidade horizontal suficiente para contornar a Terra; ela cai e encontra o chão. A Lua possui velocidade orbital e está continuamente sendo acelerada pela gravidade em direção à Terra, mas seu movimento lateral faz com que sua trajetória curve ao redor do planeta.</p>
      <p>O satélite observado no início segue a mesma ideia básica. Em uma órbita, <strong>cair e continuar se movendo lateralmente acontecem ao mesmo tempo</strong>.</p>
      <div class="note-box"><strong>Resposta final à pergunta da noite</strong><p>A gravidade não faz apenas objetos “despencarem”. Ela também pode fornecer a aceleração necessária para trajetórias orbitais. A partir dessa mesma investigação, as leis de Kepler descrevem padrões planetários, a gravitação de Newton explica grande parte desses movimentos e modelos cosmológicos e a relatividade geral ampliam a descrição para outras escalas e perguntas.</p></div>
    </section>

    <section>
      <h3>9. Experimento de mesa: construa uma elipse e identifique seus focos</h3>
      <div class="experiment-box"><strong class="card-title">Barbante, dois focos e lápis</strong><ol class="reason-steps"><li>Prenda dois pontos numa folha sobre uma base adequada.</li><li>Faça um laço de barbante envolvendo os dois pontos.</li><li>Mantenha o barbante esticado com um lápis e percorra a curva.</li><li>Observe que a elipse possui dois focos.</li><li>Relacione a construção à 1ª Lei de Kepler: numa órbita elíptica idealizada, o Sol ocupa um dos focos.</li></ol><p class="safety-note"><strong>Segurança:</strong> use material escolar adequado e evite pontas expostas ou superfícies que possam ser danificadas.</p></div>
    </section>

    <section class="chapter-checkpoint">
      <span class="lesson-kicker">Antes de guardar o telescópio</span>
      <h3>10. Você consegue ligar queda, órbitas e Universo?</h3>
      <div class="quick-question" data-choice-question data-correct="c"><strong>1. Distância</strong><p>Se a distância entre dois corpos triplica, mantendo as massas, a força gravitacional fica:</p><div class="choice-row"><button type="button" data-choice="a">3 vezes maior</button><button type="button" data-choice="b">1/3</button><button type="button" data-choice="c">1/9</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. F é proporcional a 1/r²." data-wrong-text="Triplique r e depois eleve esse fator ao quadrado."></div></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>2. Satélite</strong><p>Um satélite em órbita:</p><div class="choice-row"><button type="button" data-choice="a">está sem gravidade</button><button type="button" data-choice="b">está em queda contínua ao redor da Terra</button><button type="button" data-choice="c">não possui velocidade</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. A gravidade curva continuamente sua trajetória." data-wrong-text="Órbita não significa ausência de gravidade."></div></div>
      <div class="quick-question" data-choice-question data-correct="a"><strong>3. Kepler 1</strong><p>Na Primeira Lei de Kepler, o Sol fica:</p><div class="choice-row"><button type="button" data-choice="a">em um dos focos da elipse</button><button type="button" data-choice="b">sempre no centro geométrico</button><button type="button" data-choice="c">fora da órbita</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. A elipse possui dois focos e o Sol ocupa um deles." data-wrong-text="Retome a construção da elipse e seus dois focos."></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>4. Kepler 2</strong><p>Segundo a Segunda Lei de Kepler, o planeta se move mais rapidamente quando:</p><div class="choice-row"><button type="button" data-choice="a">a velocidade nunca muda</button><button type="button" data-choice="b">está mais longe do Sol</button><button type="button" data-choice="c">está mais perto do Sol</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. A lei das áreas implica maior rapidez nas regiões mais próximas do Sol." data-wrong-text="Pense em áreas iguais varridas em tempos iguais."></div></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>5. Kepler 3</strong><p>Para corpos em torno do mesmo centro, uma órbita maior tende a ter:</p><div class="choice-row"><button type="button" data-choice="a">período menor</button><button type="button" data-choice="b">período maior</button><button type="button" data-choice="c">período zero</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. T² é proporcional a a³." data-wrong-text="Aumente a e observe como T deve variar."></div></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>6. Big Bang</strong><p>Qual descrição é adequada em nível introdutório?</p><div class="choice-row"><button type="button" data-choice="a">uma bomba que explodiu em um ponto central do espaço vazio</button><button type="button" data-choice="b">a evolução de um Universo antes muito quente e denso, com expansão em grande escala</button><button type="button" data-choice="c">uma galáxia que se dividiu em todas as outras</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. Essa formulação representa melhor o modelo cosmológico introdutório." data-wrong-text="Evite a imagem de uma explosão comum dentro de um espaço vazio."></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>7. Newton e Einstein</strong><p>Por que a gravitação de Newton continua sendo usada?</p><div class="choice-row"><button type="button" data-choice="a">porque Einstein foi descartado</button><button type="button" data-choice="b">porque Newton é exato em qualquer situação</button><button type="button" data-choice="c">porque é uma excelente aproximação em muitos domínios</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. Uma teoria mais geral não elimina uma aproximação muito eficaz em seu domínio." data-wrong-text="Pense em domínio de validade e precisão necessária."></div></div>
      <div class="quick-question" data-choice-question data-correct="a"><strong>8. Relatividade geral</strong><p>Em nível introdutório, a relatividade geral relaciona a gravidade à:</p><div class="choice-row"><button type="button" data-choice="a">geometria do espaço-tempo</button><button type="button" data-choice="b">ausência de movimento</button><button type="button" data-choice="c">inexistência de massa</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. A geometria do espaço-tempo é central nessa descrição." data-wrong-text="Retome a comparação entre as descrições de Newton e Einstein."></div></div>
      <div class="challenge-box"><strong>Desafio MbB — responda à pergunta da observação</strong><p>Explique, sem começar por fórmulas, por que a bola solta no pátio cai no chão enquanto a Lua permanece em órbita. Sua resposta deve usar gravidade, velocidade lateral e queda contínua. Depois explique por que dizer “no espaço não há gravidade” contradiz o próprio movimento orbital.</p></div>
    </section>

    <details class="curriculum-box"><summary>Conexão com o plano de curso</summary><p>O capítulo trabalha os objetos previstos de <strong>Astronomia e Universo</strong>: Big Bang, expansão do Universo, leis de Kepler, gravitação universal, modelos cosmológicos e relatividade geral.</p></details>
  `;

  function initOrbitLab(root){
    const radius=$('#orbitRadiusRange',root),radiusValue=$('#orbitRadiusValue',root),gravityValue=$('#relativeGravityValue',root),speedValue=$('#relativeSpeedValue',root),periodValue=$('#relativePeriodValue',root),path=$('#orbitPath',root),planet=$('#orbitPlanet',root),conclusion=$('#orbitConclusion',root);
    if(!radius||!radiusValue||!gravityValue||!speedValue||!periodValue||!path||!planet||!conclusion)return;
    const format=(v,d=2)=>Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
    const draw=()=>{const r=Number(radius.value),force=1/(r*r),speed=1/Math.sqrt(r),period=Math.pow(r,1.5); radiusValue.textContent=format(r); gravityValue.textContent=format(force); speedValue.textContent=format(speed); periodValue.textContent=format(period); const visualRadius=55+((r-1)/4)*110; path.setAttribute('r',visualRadius.toFixed(1)); planet.setAttribute('cx',(380+visualRadius).toFixed(1)); planet.setAttribute('cy','150'); conclusion.textContent=r<2?'Mais perto do corpo central, a atração é mais intensa, a velocidade orbital circular é maior e o período é menor.':r<4?'Ao afastar a órbita, a atração cai com 1/r² e o período cresce conforme r^(3/2).':'Em uma órbita bem mais distante, a atração é muito menor e o tempo para completar uma volta é muito maior.';};
    radius.addEventListener('input',draw); draw();
  }

  MBB.enableChapter?.('08 Da queda de uma maçã ao Universo',()=>{MBB.showLesson({unit:'Terra e Cosmos',technical:'Astronomia • Big Bang • expansão do Universo • Kepler • gravitação universal • modelos cosmológicos • relatividade geral',title:'Da queda de uma maçã ao Universo',objective:'<strong>Propósito:</strong> acompanhar uma noite de observação para compreender por que a gravidade produz quedas e órbitas e ampliar essa investigação até Kepler, Newton, a expansão do Universo e a relatividade geral.',html:lessonHtml,init:initOrbitLab});});
})();
