(() => {
  'use strict';

  const MBB = window.MBBPhysics = window.MBBPhysics || {};

  const lessonHtml = `
    <section class="physics-opening">
      <span class="lesson-kicker">Prática acumulativa</span>
      <div class="hero-box physics-story">
        <strong class="card-title">Agora você vai usar a Física para explicar situações, calcular quando necessário e decidir até onde uma conclusão é válida.</strong>
        <p>Os exercícios foram organizados numa progressão: <strong>entender → observar → explicar → calcular → comparar → aplicar → investigar</strong>. Sempre tente resolver antes de abrir a resposta.</p>
        <p class="central-question"><strong>Regra de ouro:</strong> uma conta sem interpretação está incompleta; uma explicação física sem evidência também pode estar incompleta.</p>
      </div>
    </section>

    <section>
      <h3>1. Movimento e forças — da descrição à causa</h3>

      <div class="quick-question" data-choice-question data-correct="b"><strong>1. Entenda — posição e trajetória</strong><p>Um ciclista percorre 600 m em linha reta e retorna 200 m pelo mesmo caminho. Qual é o deslocamento em relação ao ponto inicial?</p><div class="choice-row"><button type="button" data-choice="a">800 m</button><button type="button" data-choice="b">400 m</button><button type="button" data-choice="c">600 m</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Ele terminou 400 m adiante do ponto inicial: 600 − 200 = 400 m." data-wrong-text="Deslocamento depende da posição final em relação à inicial, não do caminho total percorrido."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>2. Observe — velocidade média</strong><p>Um ônibus percorre 12 km em 30 min. Qual é sua velocidade média escalar?</p><div class="choice-row"><button type="button" data-choice="a">12 km/h</button><button type="button" data-choice="b">18 km/h</button><button type="button" data-choice="c">24 km/h</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="30 min = 0,5 h; então v = 12/0,5 = 24 km/h." data-wrong-text="Converta 30 min para horas antes de dividir a distância pelo tempo."></div></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>3. Explique — inércia</strong><p>Quando um ônibus freia de repente, o passageiro tende a continuar se movendo para a frente. Qual explicação é adequada?</p><div class="choice-row"><button type="button" data-choice="a">Surge uma força misteriosa empurrando o corpo para a frente</button><button type="button" data-choice="b">O corpo tende a manter seu estado de movimento enquanto o ônibus reduz a velocidade</button><button type="button" data-choice="c">A gravidade muda de direção</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso é uma manifestação da inércia: o corpo tende a manter sua velocidade até que forças resultantes a modifiquem." data-wrong-text="Separe o movimento do passageiro do movimento do ônibus durante a freada."></div></div>

      <div class="quick-question" data-choice-question data-correct="a"><strong>4. Calcule — segunda lei de Newton</strong><p>Uma força resultante de 900 N atua sobre um carrinho de 300 kg. Qual é a aceleração?</p><div class="choice-row"><button type="button" data-choice="a">3 m/s²</button><button type="button" data-choice="b">300 m/s²</button><button type="button" data-choice="c">1.200 m/s²</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="a = F/m = 900/300 = 3 m/s²." data-wrong-text="Use F = m·a e isole a."></div></div>

      <div class="challenge-box"><strong>5. Aplique — curva molhada</strong><p>Um carro entra numa curva com velocidade alta durante chuva intensa. Explique por que reduzir a velocidade aumenta a segurança, relacionando atrito e necessidade de aceleração centrípeta.</p><details><summary>Resposta orientada</summary><p>Para fazer a curva, o carro precisa de uma força resultante dirigida para o centro da trajetória. Em condições comuns, o atrito entre pneu e pista participa dessa força. Com pista molhada, o atrito disponível pode diminuir. Como a necessidade de aceleração centrípeta cresce com o quadrado da velocidade, reduzir a velocidade diminui a força lateral necessária e aumenta a margem de segurança.</p></details></div>
    </section>

    <section>
      <h3>2. Energia, potência, impulso e colisões</h3>

      <div class="quick-question" data-choice-question data-correct="c"><strong>6. Entenda — energia potencial</strong><p>Uma mochila de 5 kg é elevada 2 m. Usando g ≈ 10 m/s², qual é o aumento da energia potencial gravitacional?</p><div class="choice-row"><button type="button" data-choice="a">10 J</button><button type="button" data-choice="b">25 J</button><button type="button" data-choice="c">100 J</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="ΔEpg = mgh = 5·10·2 = 100 J." data-wrong-text="Use m·g·h."></div></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>7. Compare — potência</strong><p>Duas pessoas realizam o mesmo trabalho para subir a mesma escada. Uma leva 5 s e a outra 10 s. Qual desenvolve maior potência média?</p><div class="choice-row"><button type="button" data-choice="a">A que leva 10 s</button><button type="button" data-choice="b">A que leva 5 s</button><button type="button" data-choice="c">As duas necessariamente têm a mesma potência</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Para o mesmo trabalho, menor tempo significa maior potência: P = W/Δt." data-wrong-text="Potência compara trabalho realizado por unidade de tempo."></div></div>

      <div class="quick-question" data-choice-question data-correct="a"><strong>8. Calcule — quantidade de movimento</strong><p>Um carrinho de 4 kg move-se a 3 m/s. Qual é sua quantidade de movimento?</p><div class="choice-row"><button type="button" data-choice="a">12 kg·m/s</button><button type="button" data-choice="b">7 kg·m/s</button><button type="button" data-choice="c">1,3 kg·m/s</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="p = m·v = 4·3 = 12 kg·m/s." data-wrong-text="Multiplique massa pela velocidade."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>9. Explique — airbag</strong><p>Por que o airbag ajuda a reduzir a força média sobre o ocupante numa colisão?</p><div class="choice-row"><button type="button" data-choice="a">Porque elimina a variação da quantidade de movimento</button><button type="button" data-choice="b">Porque aumenta a velocidade do ocupante</button><button type="button" data-choice="c">Porque aumenta o tempo em que a mudança de quantidade de movimento ocorre</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Para uma variação de quantidade de movimento semelhante, aumentar o tempo de interação reduz a força média." data-wrong-text="Relacione impulso, força média e intervalo de tempo."></div></div>

      <div class="challenge-box"><strong>10. Investigue — colisão</strong><p>Dois carrinhos colidem em uma pista e permanecem juntos depois do choque. O que você precisa medir antes e depois para verificar a conservação da quantidade de movimento do sistema?</p><details><summary>Resposta orientada</summary><p>É preciso conhecer as massas e velocidades antes da colisão e a velocidade do conjunto depois. Calcula-se a quantidade de movimento total antes e depois. A comparação deve considerar as incertezas e a presença de forças externas relevantes durante a colisão.</p></details></div>
    </section>

    <section>
      <h3>3. Temperatura, calor e materiais</h3>

      <div class="quick-question" data-choice-question data-correct="b"><strong>11. Entenda — temperatura do ar</strong><p>O aplicativo indica 31 °C, mas o asfalto ao Sol mede 52 °C. Qual interpretação é adequada?</p><div class="choice-row"><button type="button" data-choice="a">Um dos valores está obrigatoriamente errado</button><button type="button" data-choice="b">São temperaturas de corpos ou condições diferentes</button><button type="button" data-choice="c">Todo o ambiente está a 52 °C</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="A temperatura do ar e a temperatura de uma superfície exposta ao Sol podem ser muito diferentes." data-wrong-text="Pergunte o que cada medição representa."></div></div>

      <div class="quick-question" data-choice-question data-correct="a"><strong>12. Calcule — calor específico</strong><p>0,5 kg de água recebem 42.000 J. Use c = 4.200 J/(kg·°C). Qual é a variação de temperatura no modelo ideal?</p><div class="choice-row"><button type="button" data-choice="a">20 °C</button><button type="button" data-choice="b">10 °C</button><button type="button" data-choice="c">42 °C</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="ΔT = Q/(m·c) = 42.000/(0,5·4.200) = 20 °C." data-wrong-text="Use Q = m·c·ΔT e isole ΔT."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>13. Compare — mesma energia</strong><p>Água e areia de mesma massa recebem a mesma energia. Se a água tem maior calor específico, qual tende a sofrer menor variação de temperatura?</p><div class="choice-row"><button type="button" data-choice="a">A areia</button><button type="button" data-choice="b">As duas necessariamente variam igual</button><button type="button" data-choice="c">A água</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Com Q e m iguais, maior c implica menor ΔT." data-wrong-text="Observe ΔT = Q/(m·c)."></div></div>

      <div class="challenge-box"><strong>14. Aplique — cobertura de uma sala</strong><p>Uma empresa afirma que um revestimento “reduz 12 °C”. Liste quatro informações que precisam ser conhecidas antes de interpretar esse número.</p><details><summary>Resposta orientada</summary><p>Exemplos: qual temperatura foi medida; onde o sensor estava; qual era a situação de comparação; horário e condições ambientais; instrumento e procedimento; duração do teste; características da construção. A afirmação só pode ser avaliada quando o número recebe contexto físico.</p></details></div>
    </section>

    <section>
      <h3>4. Equilíbrio e fluidos</h3>

      <div class="quick-question" data-choice-question data-correct="b"><strong>15. Calcule — torque</strong><p>Uma força perpendicular de 80 N atua a 0,50 m de um eixo. Qual é o torque em módulo?</p><div class="choice-row"><button type="button" data-choice="a">160 N·m</button><button type="button" data-choice="b">40 N·m</button><button type="button" data-choice="c">80,5 N·m</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="τ = F·d = 80·0,50 = 40 N·m." data-wrong-text="Multiplique a força pela distância perpendicular ao eixo."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>16. Explique — equilíbrio completo</strong><p>Para um corpo rígido permanecer em equilíbrio estático no plano, qual condição é necessária?</p><div class="choice-row"><button type="button" data-choice="a">Somente ΣF = 0</button><button type="button" data-choice="b">Somente Στ = 0</button><button type="button" data-choice="c">ΣF = 0 e Στ = 0</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="É preciso impedir tanto a aceleração de translação quanto a aceleração de rotação." data-wrong-text="Um corpo pode ter força resultante zero e ainda tender a girar."></div></div>

      <div class="quick-question" data-choice-question data-correct="a"><strong>17. Calcule — pressão hidrostática</strong><p>Na água, qual é aproximadamente a diferença de pressão entre dois pontos separados verticalmente por 4 m? Use ρ = 1.000 kg/m³ e g = 10 m/s².</p><div class="choice-row"><button type="button" data-choice="a">40.000 Pa</button><button type="button" data-choice="b">4.000 Pa</button><button type="button" data-choice="c">400 Pa</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Δp = ρgΔh = 1.000·10·4 = 40.000 Pa." data-wrong-text="Use a Lei de Stevin."></div></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>18. Explique — navio</strong><p>Por que um navio de aço pode flutuar enquanto um pequeno bloco maciço de aço afunda?</p><div class="choice-row"><button type="button" data-choice="a">Porque a gravidade deixa de atuar no navio</button><button type="button" data-choice="b">Porque o casco aumenta o volume total e permite deslocar água suficiente para equilibrar o peso</button><button type="button" data-choice="c">Porque o motor produz empuxo vertical mesmo quando desligado</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="A forma do casco reduz a densidade média do conjunto e permite um volume deslocado suficiente para que o empuxo equilibre o peso." data-wrong-text="Compare massa total, volume total e volume de fluido deslocado."></div></div>

      <div class="challenge-box"><strong>19. Aplique — prateleira</strong><p>Uma caixa exerce peso de 150 N a 0,80 m do apoio. Calcule o torque e explique por que aproximá-la para 0,20 m reduz a tendência de giro.</p><details><summary>Resposta orientada</summary><p>Na primeira posição, τ = 150·0,80 = 120 N·m. Na segunda, τ = 150·0,20 = 30 N·m. A força é a mesma, mas o braço de alavanca ficou quatro vezes menor; por isso o torque também ficou quatro vezes menor.</p></details></div>
    </section>

    <section>
      <h3>5. Terra, órbitas e Universo</h3>

      <div class="quick-question" data-choice-question data-correct="b"><strong>20. Entenda — órbita</strong><p>Um satélite em órbita está sem gravidade?</p><div class="choice-row"><button type="button" data-choice="a">Sim, porque está no espaço</button><button type="button" data-choice="b">Não; a gravidade participa da curvatura de sua trajetória</button><button type="button" data-choice="c">Somente se o motor estiver desligado</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Órbita é uma forma de queda contínua em torno do corpo central, não ausência de gravidade." data-wrong-text="Pergunte qual força muda continuamente a direção da velocidade."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>21. Calcule proporcionalmente — gravitação</strong><p>Se a distância entre dois corpos dobra e as massas permanecem iguais, a força gravitacional passa a ser:</p><div class="choice-row"><button type="button" data-choice="a">2 vezes maior</button><button type="button" data-choice="b">metade</button><button type="button" data-choice="c">um quarto</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Como F ∝ 1/r², dobrar r reduz a força para 1/4." data-wrong-text="Eleve a nova distância ao quadrado."></div></div>

      <div class="quick-question" data-choice-question data-correct="a"><strong>22. Kepler</strong><p>Segundo a primeira lei de Kepler, o Sol ocupa:</p><div class="choice-row"><button type="button" data-choice="a">um dos focos da elipse</button><button type="button" data-choice="b">sempre o centro geométrico da elipse</button><button type="button" data-choice="c">um ponto fora da órbita</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="A órbita planetária idealizada é elíptica, com o Sol em um dos focos." data-wrong-text="Lembre que uma elipse possui dois focos."></div></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>23. Big Bang</strong><p>Qual descrição é mais adequada em nível introdutório?</p><div class="choice-row"><button type="button" data-choice="a">Uma bomba explodiu num ponto central de um espaço vazio</button><button type="button" data-choice="b">O Universo evoluiu a partir de um estado muito quente e denso, com expansão em grande escala</button><button type="button" data-choice="c">Uma galáxia se partiu e formou todas as outras</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="O modelo do Big Bang descreve a evolução do próprio Universo, não uma explosão comum dentro de um espaço vazio pré-existente." data-wrong-text="Evite a analogia literal de uma bomba no espaço."></div></div>

      <div class="challenge-box"><strong>24. Explique — Newton e Einstein</strong><p>Se a relatividade geral é mais abrangente, por que ainda usamos a gravitação de Newton em muitos problemas?</p><details><summary>Resposta orientada</summary><p>Porque o modelo newtoniano fornece aproximações excelentes em muitos domínios de velocidade, campo gravitacional e precisão. Uma teoria mais geral não torna automaticamente inútil um modelo mais simples dentro de seu domínio de validade.</p></details></div>
    </section>

    <section>
      <h3>6. Vida em outros mundos e informação confiável</h3>

      <div class="quick-question" data-choice-question data-correct="c"><strong>25. Habitabilidade</strong><p>Um planeta está na zona habitável de sua estrela. O que podemos concluir?</p><div class="choice-row"><button type="button" data-choice="a">Existe vida nele</button><button type="button" data-choice="b">Ele possui necessariamente oceanos</button><button type="button" data-choice="c">A posição pode favorecer certas condições, mas não prova vida</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Zona habitável é uma condição possível do modelo, não uma evidência direta de organismos." data-wrong-text="Separe condição favorável de evidência de vida."></div></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>26. Fonte e evidência</strong><p>Uma postagem apresenta um gráfico sem indicar autoria, método, unidades ou origem dos dados. Qual atitude é mais adequada?</p><div class="choice-row"><button type="button" data-choice="a">Aceitar porque possui gráfico</button><button type="button" data-choice="b">Tratar a afirmação com cautela e buscar origem, método e fontes independentes</button><button type="button" data-choice="c">Concluir que é falsa apenas porque está na internet</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="A qualidade da evidência depende de origem, método, dados, contexto e possibilidade de conferência." data-wrong-text="Nem aceitar nem rejeitar automaticamente: primeiro investigue a evidência."></div></div>

      <div class="challenge-box"><strong>27. Aplique — manchete sobre exoplaneta</strong><p>Uma manchete afirma: “Planeta semelhante à Terra tem vida confirmada”. O texto, porém, diz apenas que o planeta tem tamanho aproximado ao da Terra e está numa faixa de temperatura estimada compatível com água líquida. Reescreva a manchete de forma cientificamente responsável.</p><details><summary>Resposta orientada</summary><p>Uma versão possível: <strong>“Planeta com tamanho semelhante ao da Terra apresenta condições que podem ser compatíveis com água líquida”</strong>. A redação evita transformar características físicas em confirmação de vida.</p></details></div>
    </section>

    <section>
      <h3>7. Cobertura curricular — conceitos que merecem um exercício próprio</h3>

      <div class="quick-question" data-choice-question data-correct="b"><strong>28. Aceleração</strong><p>A velocidade de um móvel passa de 4 m/s para 10 m/s em 3 s. Qual é a aceleração média?</p><div class="choice-row"><button type="button" data-choice="a">1 m/s²</button><button type="button" data-choice="b">2 m/s²</button><button type="button" data-choice="c">14 m/s²</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Δv = 10 − 4 = 6 m/s; a = 6/3 = 2 m/s²." data-wrong-text="Calcule primeiro a variação da velocidade e depois divida pelo intervalo de tempo."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>29. Equação horária do movimento uniforme</strong><p>Um ciclista está na posição 100 m e mantém 5 m/s durante 40 s. Em que posição estará?</p><div class="choice-row"><button type="button" data-choice="a">200 m</button><button type="button" data-choice="b">240 m</button><button type="button" data-choice="c">300 m</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="s = s₀ + vt = 100 + 5·40 = 300 m." data-wrong-text="Some à posição inicial o avanço produzido por v·t."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>30. Queda livre</strong><p>Uma bola é solta do repouso e cai durante 2 s. Usando g ≈ 10 m/s² e desprezando o ar, qual distância ela cai?</p><div class="choice-row"><button type="button" data-choice="a">10 m</button><button type="button" data-choice="b">40 m</button><button type="button" data-choice="c">20 m</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="h = ½gt² = 0,5·10·2² = 20 m." data-wrong-text="O tempo aparece ao quadrado na distância de queda a partir do repouso."></div></div>

      <div class="quick-question" data-choice-question data-correct="a"><strong>31. Lançamento horizontal</strong><p>Uma bola sai horizontalmente a 8 m/s de uma borda e permanece 0,5 s no ar. Desprezando o ar, quanto avança horizontalmente nesse intervalo?</p><div class="choice-row"><button type="button" data-choice="a">4 m</button><button type="button" data-choice="b">8 m</button><button type="button" data-choice="c">16 m</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Na horizontal, x = vₓt = 8·0,5 = 4 m." data-wrong-text="O movimento horizontal permanece uniforme neste modelo."></div></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>32. Trabalho mecânico</strong><p>Uma força constante de 50 N atua na mesma direção do deslocamento de 6 m. Qual é o trabalho realizado por essa força?</p><div class="choice-row"><button type="button" data-choice="a">56 J</button><button type="button" data-choice="b">300 J</button><button type="button" data-choice="c">8,3 J</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Como força e deslocamento têm a mesma direção, W = F·d = 50·6 = 300 J." data-wrong-text="Neste caso simples, multiplique a força pelo deslocamento."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>33. Energia cinética</strong><p>Um corpo de 2 kg move-se a 4 m/s. Qual é sua energia cinética?</p><div class="choice-row"><button type="button" data-choice="a">8 J</button><button type="button" data-choice="b">32 J</button><button type="button" data-choice="c">16 J</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Ec = ½mv² = 0,5·2·4² = 16 J." data-wrong-text="Eleve a velocidade ao quadrado antes de multiplicar por ½m."></div></div>

      <div class="challenge-box"><strong>34. Energia elástica e conservação</strong><p>Uma mola de constante elástica 200 N/m é comprimida 0,10 m. Calcule a energia potencial elástica armazenada e diga o que pode acontecer com essa energia se a mola for liberada num sistema ideal sem perdas.</p><details><summary>Resposta orientada</summary><p>E<sub>el</sub> = ½kx² = 0,5·200·0,10² = <strong>1 J</strong>. Num modelo ideal, essa energia pode transformar-se em outras formas de energia mecânica, como energia cinética, mantendo a energia mecânica total do sistema.</p></details></div>

      <div class="quick-question" data-choice-question data-correct="a"><strong>35. Impulso</strong><p>Uma força média de 500 N atua durante 0,20 s. Qual é o impulso produzido?</p><div class="choice-row"><button type="button" data-choice="a">100 N·s</button><button type="button" data-choice="b">2.500 N·s</button><button type="button" data-choice="c">500,2 N·s</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="I = FΔt = 500·0,20 = 100 N·s." data-wrong-text="Multiplique a força média pelo intervalo de tempo."></div></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>36. Coeficiente de restituição e tipo de choque</strong><p>Antes de uma colisão, a velocidade relativa de aproximação entre dois corpos é 4 m/s; depois, a velocidade relativa de afastamento é 2 m/s. Qual é o coeficiente de restituição e como classificar o choque?</p><div class="choice-row"><button type="button" data-choice="a">e = 1; perfeitamente elástico</button><button type="button" data-choice="b">e = 0,5; inelástico</button><button type="button" data-choice="c">e = 2; perfeitamente inelástico</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="e = 2/4 = 0,5. Como 0 < e < 1, o choque é inelástico." data-wrong-text="Divida a velocidade relativa de afastamento pela de aproximação."></div></div>

      <div class="quick-question" data-choice-question data-correct="a"><strong>37. Escalas termométricas</strong><p>Uma temperatura de 25 °C corresponde aproximadamente a:</p><div class="choice-row"><button type="button" data-choice="a">298 K e 77 °F</button><button type="button" data-choice="b">25 K e 45 °F</button><button type="button" data-choice="c">273 K e 25 °F</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="K = 25 + 273,15 ≈ 298 K; °F = 1,8·25 + 32 = 77 °F." data-wrong-text="Use K = °C + 273,15 e °F = 1,8·°C + 32."></div></div>

      <div class="challenge-box"><strong>38. Dilatação térmica — sólidos, líquidos e gases</strong><p>Explique por que existem folgas em estruturas metálicas, por que um líquido pode subir num termômetro e por que aquecer um gás num recipiente fechado pode aumentar a pressão. O que há em comum entre os três casos?</p><details><summary>Resposta orientada</summary><p>O aquecimento pode alterar dimensões ou volume. Sólidos se dilatam e precisam de espaço para variar de tamanho; líquidos podem aumentar de volume e subir no tubo do termômetro; em gases confinados, a expansão é impedida e a pressão pode aumentar. Em todos os casos, a temperatura modifica o comportamento microscópico e as dimensões ou condições macroscópicas do sistema.</p></details></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>39. Capacidade térmica</strong><p>Um corpo de 2 kg é feito de um material com calor específico 900 J/(kg·°C). Qual é sua capacidade térmica?</p><div class="choice-row"><button type="button" data-choice="a">450 J/°C</button><button type="button" data-choice="b">902 J/°C</button><button type="button" data-choice="c">1.800 J/°C</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="C = m·c = 2·900 = 1.800 J/°C." data-wrong-text="Capacidade térmica depende da massa do corpo e do calor específico do material."></div></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>40. Centro de massa</strong><p>Uma massa de 2 kg está em x = 0 m e outra de 1 kg está em x = 3 m. Onde fica o centro de massa?</p><div class="choice-row"><button type="button" data-choice="a">0,5 m</button><button type="button" data-choice="b">1,0 m</button><button type="button" data-choice="c">1,5 m</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="xcm = (2·0 + 1·3)/(2+1) = 1 m." data-wrong-text="Faça a média das posições ponderada pelas massas."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>41. Densidade</strong><p>Um objeto tem massa de 600 kg e volume de 0,75 m³. Qual é sua densidade média?</p><div class="choice-row"><button type="button" data-choice="a">450 kg/m³</button><button type="button" data-choice="b">600 kg/m³</button><button type="button" data-choice="c">800 kg/m³</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="ρ = m/V = 600/0,75 = 800 kg/m³." data-wrong-text="Divida a massa pelo volume."></div></div>

      <div class="challenge-box"><strong>42. Princípio de Pascal</strong><p>Num sistema hidráulico ideal, uma força de 200 N é aplicada a um pistão de área 0,01 m². O outro pistão tem área 0,10 m². Calcule a pressão transmitida e a força ideal no pistão maior.</p><details><summary>Resposta orientada</summary><p>A pressão aplicada é p = F/A = 200/0,01 = <strong>20.000 Pa</strong>. Pelo princípio de Pascal, essa pressão é transmitida ao fluido; no pistão maior, F = pA = 20.000·0,10 = <strong>2.000 N</strong>, no modelo ideal.</p></details></div>

      <div class="quick-question" data-choice-question data-correct="b"><strong>43. Segunda lei de Kepler</strong><p>Em uma órbita elíptica, um planeta se move mais rapidamente quando está:</p><div class="choice-row"><button type="button" data-choice="a">mais distante do Sol</button><button type="button" data-choice="b">mais próximo do Sol</button><button type="button" data-choice="c">sempre com a mesma velocidade</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Áreas iguais são varridas em tempos iguais; por isso o planeta se move mais rapidamente nas regiões mais próximas do Sol." data-wrong-text="Relacione a lei das áreas com a distância ao Sol."></div></div>

      <div class="quick-question" data-choice-question data-correct="c"><strong>44. Terceira lei de Kepler</strong><p>Para corpos orbitando o mesmo centro, se a distância orbital característica for 4 vezes maior, o período orbital será aproximadamente:</p><div class="choice-row"><button type="button" data-choice="a">2 vezes maior</button><button type="button" data-choice="b">4 vezes maior</button><button type="button" data-choice="c">8 vezes maior</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="T² ∝ a³: 4³ = 64 e √64 = 8, então o período cresce por um fator 8." data-wrong-text="Use a proporcionalidade T² ∝ a³."></div></div>
    </section>

    <section class="chapter-checkpoint">
      <span class="lesson-kicker">Desafio final</span>
      <h3>8. Uma situação que mistura vários capítulos</h3>
      <div class="challenge-box"><strong>45. Desafio MbB — estação científica flutuante</strong><p>Uma equipe quer instalar uma pequena estação científica flutuante num lago. Ela terá painéis solares, equipamentos eletrônicos e um mastro com sensores. Durante o teste, a equipe percebe que adicionar equipamentos de um lado inclina a plataforma e aumenta a parte submersa.</p><p>Explique a situação usando pelo menos <strong>quatro</strong> ideias entre: centro de massa, torque, equilíbrio, densidade média, empuxo, pressão, energia e potência. Depois proponha duas medições que ajudariam a verificar se a plataforma permanece segura.</p><details><summary>Resposta orientada</summary><p>Ao adicionar massa de um lado, o centro de massa se desloca e aparece um torque que tende a inclinar a plataforma. Para continuar em equilíbrio, os torques e as forças precisam se compensar. O aumento da massa total exige maior empuxo; por isso a plataforma afunda um pouco mais e desloca mais água até que o empuxo iguale o peso. A pressão hidrostática também aumenta nas partes mais profundas. Se houver painéis e equipamentos, potência e consumo de energia entram no dimensionamento do sistema elétrico. Medições úteis incluem ângulo de inclinação, altura da borda livre, massa total, posição do centro de massa, volume deslocado e distribuição das cargas.</p></details></div>
    </section>

    <details class="curriculum-box"><summary>Conexão com o plano de curso</summary><p>Este conjunto de 45 atividades integra os objetos de aprendizagem trabalhados nos capítulos anteriores: Cinemática, Dinâmica, trabalho e energia, impulso e colisões, termometria, dilatação e propriedades térmicas, Estática, Hidrostática, gravitação, leis de Kepler, cosmologia, análise de informações científicas e aplicações tecnológicas.</p></details>
  `;

  MBB.enableChapter?.('99 Exercícios e desafios', () => {
    MBB.showLesson({
      unit:'Prática',
      technical:'Revisão integrada • interpretação • cálculo • aplicação • investigação',
      title:'Exercícios e desafios',
      objective:'<strong>Propósito:</strong> consolidar a Física da 1ª série por meio de uma progressão de compreensão, cálculo, explicação, aplicação e investigação.',
      html:lessonHtml
    });
  });
})();