(() => {
  'use strict';

  const MBB = window.MBBPhysics = window.MBBPhysics || {};
  const $ = (selector, root = document) => root.querySelector(selector);

  const lessonHtml = `
    <section class="physics-opening">
      <span class="lesson-kicker">Uma história para investigar</span>
      <div class="hero-box physics-story">
        <strong class="card-title">Você chega à praia com sua família por volta das 14h. Antes de sair do estacionamento, abre o aplicativo de tempo para conferir as condições da tarde. A tela informa: “temperatura do ar: 32 °C”.</strong>
        <p>Minutos depois, você pisa descalço na areia exposta ao Sol e tira o pé rapidamente. Ao entrar no mar, a água parece muito mais fria. No começo da noite ocorre outra diferença: a areia esfria depressa, enquanto a água do mar muda de temperatura bem mais lentamente.</p>
        <div class="quick-question" data-choice-question data-correct="c"><strong>Antes de continuar, faça uma aposta</strong><p>Se o aplicativo informa 32 °C, isso significa que ar, areia, água, guarda-sol e seu corpo estão todos exatamente a 32 °C?</p><div class="choice-row"><button type="button" data-choice="a">Sim, porque existe uma única temperatura no lugar</button><button type="button" data-choice="b">Sim, desde que esteja fazendo Sol</button><button type="button" data-choice="c">Não. O valor do aplicativo se refere ao ar da região, e outros corpos podem estar em temperaturas diferentes</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. A temperatura do ar não determina a temperatura de todas as superfícies e corpos ao redor." data-wrong-text="Pergunte primeiro o que exatamente o aplicativo está informando."></div></div>
        <p class="central-question"><strong>Nossa missão:</strong> explicar por que os 32 °C do aplicativo não contradizem a areia quente e a água mais fria, e entender o que temperatura, calor, dilatação, calor específico e capacidade térmica têm a ver com essa tarde.</p>
      </div>
    </section>

    <section>
      <h3>1. O que significam os 32 °C mostrados no aplicativo?</h3>
      <p>O valor de <strong>32 °C</strong> se refere à <strong>temperatura do ar</strong> prevista ou estimada para aquela região e horário a partir de observações meteorológicas e modelos. Não é uma medição da areia, da água do mar ou da pele.</p>
      <p>Em medições meteorológicas, a temperatura do ar é obtida com sensores protegidos da radiação solar direta e instalados em condições apropriadas. Uma superfície escura ao Sol, o interior de um carro fechado ou a própria areia podem atingir temperaturas diferentes da temperatura do ar.</p>
      <div class="note-box"><strong>Resposta à primeira dúvida</strong><p>Não há contradição em o aplicativo indicar <strong>32 °C</strong> e a areia estar muito mais quente. São corpos diferentes, recebendo e transferindo energia de maneiras diferentes, e portanto podem apresentar temperaturas diferentes.</p></div>
      <div class="two-col"><div class="example-box"><strong class="card-title">Tempo</strong><p>Descreve condições atmosféricas em curto prazo: temperatura, chuva, vento, umidade e outras variáveis em determinado momento ou período.</p></div><div class="example-box"><strong class="card-title">Clima</strong><p>Descreve padrões e variações observados ao longo de períodos muito maiores. Uma única tarde quente não define o clima de uma região.</p></div></div>
    </section>

    <section>
      <h3>2. Seu pé sente “quente” e “frio”, mas sensação não é temperatura</h3>
      <p>Quando seu pé toca a areia, ocorre troca de energia entre a pele e a superfície. A sensação térmica depende da temperatura, mas também da rapidez com que essa energia é transferida. Por isso o corpo humano é útil para perceber diferenças, mas não substitui um termômetro.</p>
      <p>A <strong>temperatura</strong> é uma grandeza física que caracteriza o estado térmico de um sistema. Em uma descrição microscópica simples, ela está relacionada à energia cinética média associada ao movimento desordenado das partículas. Já <strong>calor</strong> é energia transferida entre sistemas por causa de uma diferença de temperatura.</p>
      <div class="note-box"><strong>Temperatura não é calor</strong><p>Um corpo não “contém calor” como se calor fosse uma substância armazenada. Quando existe diferença de temperatura, pode ocorrer <strong>transferência de energia por calor</strong>.</p></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>Contato térmico</strong><p>Se um corpo mais quente é colocado em contato com outro mais frio, qual é o sentido líquido da transferência de energia por calor?</p><div class="choice-row"><button type="button" data-choice="a">Do mais frio para o mais quente</button><button type="button" data-choice="b">Do mais quente para o mais frio</button><button type="button" data-choice="c">Não pode haver transferência</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. A transferência líquida ocorre do corpo de maior temperatura para o de menor temperatura até que se atinja o equilíbrio térmico." data-wrong-text="Observe qual corpo perde energia e qual recebe energia durante a aproximação do equilíbrio."></div></div>
      <div class="note-box"><strong>Como um termômetro consegue medir?</strong><p>O sensor troca energia com o meio até que sua leitura represente a condição térmica que está sendo medida. Por isso posição, contato, exposição ao Sol e tempo de estabilização importam.</p></div>
    </section>

    <section>
      <h3>3. Seu amigo vê 89,6 °F: é outra temperatura ou apenas outra escala?</h3>
      <p>É a <strong>mesma condição térmica</strong> escrita em outra escala. No Brasil, Celsius é comum no cotidiano; Kelvin é a escala termodinâmica usada em ciência; Fahrenheit aparece no uso cotidiano de alguns países.</p>
      <div class="formula-box"><span class="formula-name">Conversão entre escalas</span><div class="big-formula">K = °C + 273,15 &nbsp;&nbsp; | &nbsp;&nbsp; °F = 1,8·°C + 32</div><p>Assim, <strong>32 °C = 305,15 K = 89,6 °F</strong>. Em Kelvin não usamos o símbolo de grau.</p></div>
      <div class="interactive-lab" id="scaleLab"><div class="lab-heading"><span class="lesson-kicker">Laboratório interativo</span><h4>Troque a escala sem trocar a temperatura física</h4></div><div class="lab-controls"><label>Temperatura em Celsius <strong><span id="celsiusValue">25</span> °C</strong><input id="celsiusRange" type="range" min="-40" max="100" step="1" value="25"></label></div><div class="lab-result" aria-live="polite"><strong id="kelvinValue">298,15 K</strong><span>e</span><strong id="fahrenheitValue">77 °F</strong></div><p>Experimente 0 °C, 32 °C e 100 °C. O fenômeno não muda; muda apenas o número usado para representá-lo em cada escala.</p></div>
    </section>

    <section>
      <h3>4. Na passarela da praia há pequenas folgas entre peças metálicas. Por quê?</h3>
      <p>Durante o dia, estruturas expostas ao ambiente sofrem variações de temperatura. Muitos materiais mudam ligeiramente suas dimensões quando a temperatura muda. Em uma peça pequena isso pode ser quase imperceptível; em estruturas longas, a variação acumulada pode se tornar importante.</p>
      <p>Esse fenômeno é a <strong>dilatação térmica</strong>. Em um sólido alongado, uma maneira de estimar a variação de comprimento é:</p>
      <div class="formula-box"><span class="formula-name">Dilatação linear</span><div class="big-formula">ΔL = L₀ · α · ΔT</div><p><strong>L₀</strong> é o comprimento inicial, <strong>ΔT</strong> é a variação de temperatura e <strong>α</strong> é o coeficiente de dilatação linear do material no intervalo considerado.</p></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>Por que deixar folgas?</strong><p>Se uma peça metálica longa se aquece e tenta aumentar de comprimento, a folga serve principalmente para:</p><div class="choice-row"><button type="button" data-choice="a">impedir que a temperatura mude</button><button type="button" data-choice="b">acomodar a variação dimensional sem produzir tensões excessivas</button><button type="button" data-choice="c">eliminar o peso da estrutura</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. A folga permite acomodar a expansão e a contração associadas à variação de temperatura." data-wrong-text="A temperatura continuará variando; pense no que acontece com o comprimento da peça."></div></div>
      <div class="two-col"><div class="example-box"><strong class="card-title">Líquidos</strong><p>Também apresentam dilatação volumétrica. É esse tipo de variação que permitiu o funcionamento de muitos termômetros de líquido em vidro.</p></div><div class="example-box"><strong class="card-title">Gases</strong><p>Temperatura, volume e pressão estão relacionados. Se um gás puder se expandir, seu volume pode aumentar ao ser aquecido; se ficar confinado, a pressão também pode mudar.</p></div></div>
      <p class="safety-note"><strong>Segurança:</strong> nunca aqueça recipientes fechados improvisados para observar expansão de gases.</p>
    </section>

    <section>
      <h3>5. Voltamos à areia e à água: por que a areia aquece tão mais depressa?</h3>
      <p>Uma parte importante da resposta está no <strong>calor específico</strong>. Ele indica quanta energia precisa ser transferida para cada unidade de massa de um material para produzir determinada variação de temperatura.</p>
      <p>Como referência aproximada para este modelo, a água líquida tem c ≈ <strong>4.200 J/(kg·°C)</strong>, enquanto a areia seca pode ser representada por um valor em torno de <strong>830 J/(kg·°C)</strong>. Portanto, para a mesma massa e a mesma energia recebida, a água tende a variar menos sua temperatura.</p>
      <div class="formula-box"><span class="formula-name">Energia transferida e variação de temperatura</span><div class="big-formula">Q = m · c · ΔT</div><p>Sem mudança de estado e desprezando outras trocas, podemos escrever <strong>ΔT = Q/(m·c)</strong>. Quanto maior c, menor a variação de temperatura produzida pela mesma energia na mesma massa.</p></div>
      <div class="example-box"><strong class="card-title">Compare 1 kg recebendo 20 kJ</strong><p>Água: ΔT ≈ 20.000/(1·4.200) = <strong>4,8 °C</strong>. Areia seca: ΔT ≈ 20.000/(1·830) = <strong>24,1 °C</strong>. No modelo, a mesma energia produz uma variação de temperatura muito maior na areia.</p></div>
      <div class="note-box"><strong>Isso explica toda a praia?</strong><p>Não sozinho. Na situação real também importam umidade, evaporação, circulação da água, profundidade da camada aquecida, radiação absorvida, vento e outras trocas de energia. O calor específico ajuda a explicar por que a água resiste mais às mudanças de temperatura, mas não é o único fator.</p></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>Faça a previsão</strong><p>Dois materiais de mesma massa recebem a mesma quantidade de energia. O material com maior calor específico tende a apresentar:</p><div class="choice-row"><button type="button" data-choice="a">maior ΔT</button><button type="button" data-choice="b">menor ΔT</button><button type="button" data-choice="c">sempre a mesma ΔT</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. Como ΔT = Q/(m·c), aumentar c reduz ΔT nas mesmas condições do modelo." data-wrong-text="Mantenha Q e m constantes e observe o denominador da relação."></div></div>
    </section>

    <section>
      <h3>6. Um copo de água e uma piscina são do mesmo material. Por que não respondem do mesmo jeito?</h3>
      <p>O calor específico depende do material, mas o comportamento térmico do <strong>corpo inteiro</strong> também depende de sua massa. Uma piscina contém muito mais água do que um copo; por isso exige muito mais energia para sofrer a mesma variação de temperatura.</p>
      <p>A grandeza que representa a quantidade de energia necessária para variar a temperatura de um corpo inteiro é a <strong>capacidade térmica</strong>.</p>
      <div class="formula-box"><span class="formula-name">Capacidade térmica</span><div class="big-formula">C = Q / ΔT = m · c</div><p>Para o mesmo material, aumentar a massa aumenta a capacidade térmica na mesma proporção.</p></div>
      <div class="example-box"><strong class="card-title">Um exemplo numérico</strong><p>Se um corpo recebe 6.000 J e sua temperatura aumenta 20 °C, então C = 6.000/20 = <strong>300 J/°C</strong>. Isso significa que, nas condições consideradas, são necessários 300 J para cada aumento de 1 °C.</p></div>
    </section>

    <section>
      <h3>7. Laboratório: dê a mesma energia para água, areia e alumínio</h3>
      <div class="interactive-lab" id="heatLab"><div class="lab-heading"><span class="lesson-kicker">Laboratório interativo</span><h4>Compare a variação de temperatura</h4></div><div class="lab-controls"><label>Material <select id="materialSelect"><option value="water">Água</option><option value="sand">Areia seca</option><option value="aluminum">Alumínio</option></select></label><label>Massa <strong><span id="heatMassValue">1,0</span> kg</strong><input id="heatMassRange" type="range" min="0.5" max="5" step="0.5" value="1"></label><label>Energia transferida <strong><span id="heatEnergyValue">20</span> kJ</strong><input id="heatEnergyRange" type="range" min="10" max="100" step="10" value="20"></label></div><div class="lab-result"><strong id="materialName">Água</strong><span>c = <b id="specificHeatValue">4.200 J/(kg·°C)</b></span><span>ΔT ≈ <b id="deltaTempValue">4,8 °C</b></span></div><p id="heatLabConclusion">A água tem calor específico elevado e sua temperatura varia relativamente pouco para a mesma energia por unidade de massa.</p><p>Este é um modelo ideal: desconsidera mudanças de estado e outras transferências de energia para o ambiente.</p></div>
    </section>

    <section>
      <h3>8. Faça uma investigação simples com água e areia</h3>
      <div class="experiment-box"><strong class="card-title">Compare aquecimento e resfriamento</strong><p>Coloque massas semelhantes de água e areia em recipientes rasos e semelhantes, lado a lado, em local seguro com iluminação solar moderada. Meça as temperaturas iniciais e registre novas medidas em intervalos regulares.</p><ol class="reason-steps"><li>Use recipientes semelhantes e massas aproximadamente iguais.</li><li>Registre horário e temperatura em uma tabela.</li><li>Compare as <strong>variações de temperatura</strong>, não apenas os valores finais.</li><li>Depois coloque os recipientes à sombra e acompanhe o resfriamento.</li><li>Anote fatores que podem afetar o resultado: vento, nuvens, umidade da areia e diferença entre os recipientes.</li></ol><p class="safety-note"><strong>Segurança:</strong> não use chama, resistência elétrica improvisada, vidro aquecido ou recipientes fechados.</p></div>
    </section>

    <section>
      <h3>9. Agora podemos responder à pergunta da praia</h3>
      <div class="note-box"><strong>Por que 32 °C no aplicativo, areia quente e água mais fria podem coexistir?</strong><p>Porque os <strong>32 °C</strong> se referem à temperatura do ar, não à temperatura de todos os objetos. Areia e água recebem e perdem energia por processos diferentes e têm propriedades térmicas diferentes. A água possui calor específico elevado e, além disso, mistura, evaporação e circulação ajudam a moderar sua temperatura. A areia seca, especialmente na camada superficial exposta ao Sol, pode aquecer e resfriar muito mais rapidamente.</p></div>
      <div class="note-box"><strong>E por que a diferença muda ao anoitecer?</strong><p>Quando a radiação solar diminui, a areia superficial perde energia e sua temperatura pode cair rapidamente. A grande massa de água e sua elevada capacidade térmica fazem o mar variar mais lentamente. Por isso a diferença entre areia e água pode se inverter ou diminuir ao longo da noite.</p></div>
    </section>

    <section class="chapter-checkpoint">
      <span class="lesson-kicker">Voltando para casa</span>
      <h3>10. Você consegue explicar a tarde inteira usando Física?</h3>
      <div class="quick-question" data-choice-question data-correct="b"><strong>1. Temperatura e calor</strong><p>Qual afirmação é correta?</p><div class="choice-row"><button type="button" data-choice="a">Calor é uma substância armazenada dentro do corpo</button><button type="button" data-choice="b">Calor é energia transferida devido a uma diferença de temperatura</button><button type="button" data-choice="c">Temperatura mede massa</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. Temperatura caracteriza o estado térmico; calor descreve energia em transferência por diferença de temperatura." data-wrong-text="Separe a grandeza temperatura do processo de transferência de energia."></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>2. Kelvin</strong><p>25 °C correspondem aproximadamente a:</p><div class="choice-row"><button type="button" data-choice="a">25 K</button><button type="button" data-choice="b">248 K</button><button type="button" data-choice="c">298 K</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="25 + 273,15 ≈ 298,15 K." data-wrong-text="Use K = °C + 273,15."></div></div>
      <div class="quick-question" data-choice-question data-correct="a"><strong>3. Fahrenheit</strong><p>0 °C equivalem a:</p><div class="choice-row"><button type="button" data-choice="a">32 °F</button><button type="button" data-choice="b">0 °F</button><button type="button" data-choice="c">273 °F</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="°F = 1,8·0 + 32 = 32 °F." data-wrong-text="Use a relação de conversão entre Celsius e Fahrenheit."></div></div>
      <div class="quick-question" data-choice-question data-correct="b"><strong>4. Dilatação</strong><p>Por que estruturas longas podem ter juntas ou folgas de dilatação?</p><div class="choice-row"><button type="button" data-choice="a">Para aumentar a massa</button><button type="button" data-choice="b">Para acomodar variações dimensionais quando a temperatura muda</button><button type="button" data-choice="c">Para eliminar a gravidade</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. Materiais podem expandir e contrair com a variação de temperatura." data-wrong-text="Relacione a mudança de temperatura à mudança de dimensões."></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>5. Calor específico</strong><p>Mesma massa e mesma energia recebida: maior c tende a produzir:</p><div class="choice-row"><button type="button" data-choice="a">maior ΔT</button><button type="button" data-choice="b">massa menor</button><button type="button" data-choice="c">menor ΔT</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. ΔT = Q/(m·c)." data-wrong-text="Mantenha Q e m constantes e observe c no denominador."></div></div>
      <div class="quick-question" data-choice-question data-correct="a"><strong>6. Capacidade térmica</strong><p>Dois corpos são feitos do mesmo material; um tem o dobro da massa. Sua capacidade térmica tende a ser:</p><div class="choice-row"><button type="button" data-choice="a">o dobro</button><button type="button" data-choice="b">a metade</button><button type="button" data-choice="c">zero</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Isso. C = m·c." data-wrong-text="Mantenha o material e dobre apenas a massa."></div></div>
      <div class="quick-question" data-choice-question data-correct="c"><strong>7. Aplicativo</strong><p>O aplicativo indica 32 °C, mas um termômetro sobre a areia ao Sol marca um valor maior. A melhor explicação é:</p><div class="choice-row"><button type="button" data-choice="a">um dos aparelhos está necessariamente quebrado</button><button type="button" data-choice="b">todo o ar está na temperatura da areia</button><button type="button" data-choice="c">estão sendo consideradas condições térmicas diferentes: ar e superfície</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="Correto. A temperatura do ar e a de uma superfície aquecida pelo Sol podem ser diferentes." data-wrong-text="Pergunte o que cada medição representa."></div></div>
      <div class="quick-question" data-choice-question data-correct="a"><strong>8. Cálculo</strong><p>0,5 kg de água com c = 4.200 J/(kg·°C) recebe 21.000 J. Qual é a variação ideal de temperatura?</p><div class="choice-row"><button type="button" data-choice="a">10 °C</button><button type="button" data-choice="b">21 °C</button><button type="button" data-choice="c">100 °C</button></div><div class="choice-feedback" data-choice-feedback data-correct-text="ΔT = 21.000/(0,5·4.200) = 10 °C." data-wrong-text="Use Q = m·c·ΔT e isole ΔT."></div></div>
      <div class="challenge-box"><strong>Desafio MbB — explique a praia inteira</strong><p>Explique por que a areia e a água podem ter temperaturas diferentes durante o dia e mudar de temperatura em ritmos diferentes à noite. Sua resposta deve distinguir <strong>temperatura</strong> de <strong>calor</strong>, usar <strong>calor específico</strong> e <strong>capacidade térmica</strong> e citar pelo menos um fator real além desses modelos, como evaporação, vento ou circulação da água.</p></div>
    </section>

    <details class="curriculum-box"><summary>Conexão com o plano de curso</summary><p>O capítulo trabalha <strong>termometria</strong> — temperatura e escalas, condições do ar e clima —, <strong>dilatação térmica</strong> de sólidos, líquidos e gases, além de <strong>capacidade térmica e calor específico</strong>.</p></details>
  `;

  function initTemperatureLabs(root) {
    const format=(value,digits=1)=>Number(value).toLocaleString('pt-BR',{minimumFractionDigits:digits,maximumFractionDigits:digits});
    const celsius=$('#celsiusRange',root);
    if(celsius){
      const drawScale=()=>{const C=Number(celsius.value),K=C+273.15,F=1.8*C+32; $('#celsiusValue',root).textContent=format(C,0); $('#kelvinValue',root).textContent=`${format(K,2)} K`; $('#fahrenheitValue',root).textContent=`${format(F,1)} °F`;};
      celsius.addEventListener('input',drawScale); drawScale();
    }
    const materials={water:{name:'Água',c:4200,text:'A água tem calor específico elevado e, neste modelo, sua temperatura varia relativamente pouco para a mesma energia por unidade de massa.'},sand:{name:'Areia seca',c:830,text:'A areia seca tem calor específico bem menor que o da água, então a mesma energia por unidade de massa produz uma variação de temperatura maior.'},aluminum:{name:'Alumínio',c:900,text:'O alumínio também apresenta calor específico muito menor que o da água e responde com variações de temperatura maiores no mesmo modelo ideal.'}};
    const material=$('#materialSelect',root),mass=$('#heatMassRange',root),energy=$('#heatEnergyRange',root);
    if(!material||!mass||!energy)return;
    const drawHeat=()=>{const selected=materials[material.value]||materials.water,m=Number(mass.value),qKJ=Number(energy.value),dT=qKJ*1000/(m*selected.c); $('#materialName',root).textContent=selected.name; $('#heatMassValue',root).textContent=format(m,1); $('#heatEnergyValue',root).textContent=format(qKJ,0); $('#specificHeatValue',root).textContent=`${selected.c.toLocaleString('pt-BR')} J/(kg·°C)`; $('#deltaTempValue',root).textContent=`${format(dT,1)} °C`; $('#heatLabConclusion',root).textContent=selected.text;};
    [material,mass,energy].forEach(input=>input.addEventListener('input',drawHeat)); material.addEventListener('change',drawHeat); drawHeat();
  }

  MBB.enableChapter?.('05 Temperatura não é calor', () => {
    MBB.showLesson({unit:'Energia e matéria',technical:'Termometria • escalas • dilatação térmica • capacidade térmica • calor específico',title:'Temperatura não é calor',objective:'<strong>Propósito:</strong> investigar uma tarde na praia para distinguir temperatura de calor e compreender escalas, dilatação, capacidade térmica e calor específico.',html:lessonHtml,init:initTemperatureLabs});
  });
})();