(() => {
'use strict';
const R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,P=a=>a[R(0,a.length-1)],F=n=>Number.isInteger(n)?String(n):Number(n.toFixed(2)).toString().replace('.',','),BR=n=>`R$ ${Number(n).toFixed(2).replace('.',',')}`,E=(q,h,s,k)=>({question:q,hint:h,solution:s,key:k||q});
const names={variacao:'Variação e proporcionalidade',algebra:'Linguagem algébrica',funcao1:'Função do 1º grau',reta:'Reta e taxa de variação',partes:'Funções por partes',quadratica:'Função quadrática',parabola:'Parábola',quadrado:'Relação y=ax²',transformacoes:'Transformações de gráficos',pa:'Progressão Aritmética',tangente:'Tangente',porcentagem:'Porcentagem e índices',ladrilhamento:'Ladrilhamento',grandezas:'Grandezas e unidades',dados:'Dados e frequências'};
const levels={1:'Começando',2:'Básico',3:'Intermediário',4:'Vestibular',5:'Desafio'};
const G={
variacao(l){let p=R(2,15),q=R(2,9);if(l<3)return E(`Cada unidade custa ${BR(p)}, sem taxa inicial. Quanto custam ${q} unidades? A relação é proporcional?`,'Multiplique o preço unitário pela quantidade.',`${q}·${p}=${BR(q*p)}. Sim: a razão preço/quantidade é constante.`);let f=R(5,30),r=R(2,10);return E(`Um serviço cobra ${BR(f)} fixos e ${BR(r)} por unidade. É proporcional? Escreva a regra.`,'Veja o valor quando a quantidade é zero.',`Não. A regra é y=${r}x+${f}; a taxa fixa impede proporcionalidade direta.`)},
algebra(l){let a=R(2,9),b=R(1,20),x=R(2,10);if(l<3)return E(`Se y=${a}x+${b}, calcule y para x=${x}.`,'Substitua x.',`y=${a}·${x}+${b}=${a*x+b}.`);return E(`Uma locadora cobra ${BR(b)} de taxa inicial e ${BR(a)} por hora. Escreva C(h).`,'Separe parte fixa e parte variável.',`C(h)=${a}h+${b}.`)},
funcao1(l){let a=R(-6,6)||2,b=R(-10,15),x=R(-3,6);if(l<3)return E(`Na função f(x)=${a}x${b>=0?'+':''}${b}, calcule f(${x}).`,'Substitua x.',`f(${x})=${a*x+b}.`);return E(`Em C(x)=${Math.abs(a)}x+${Math.abs(b)}, o que representam os dois coeficientes numa cobrança por uso?`,'Compare ax+b com taxa por unidade + valor inicial.',`${Math.abs(a)} é a variação por unidade; ${Math.abs(b)} é o valor inicial.`)},
reta(l){let m=R(-5,5)||2,b=R(-8,8);if(l<3)return E(`A reta y=${m}x${b>=0?'+':''}${b} é crescente ou decrescente? Qual é seu coeficiente angular?`,'Observe o sinal de m.',`m=${m}. ${m>0?'A reta é crescente.':'A reta é decrescente.'}`);let x1=R(0,4),x2=x1+R(2,5),y1=R(1,8),y2=y1+m*(x2-x1);return E(`Uma reta passa por (${x1},${y1}) e (${x2},${y2}). Calcule m.`,'Use Δy/Δx.',`m=(${y2}−${y1})/(${x2}−${x1})=${m}.`)},
partes(l){let t=R(8,20),r1=R(2,6),r2=r1+R(2,5);if(l<3)return E(`Uma tarifa cobra ${BR(r1)} por unidade até ${t} unidades e ${BR(r2)} por unidade excedente. Por que uma única fórmula simples pode não bastar?`,'A regra muda depois do limite.','Porque há intervalos com regras diferentes; isso é uma função definida por partes.');let x=t+R(2,8);return E(`C(x)=${r1}x para x≤${t} e C(x)=${r1*t}+${r2}(x−${t}) para x>${t}. Calcule C(${x}).`,'Use a segunda sentença.',`C(${x})=${r1*t}+${r2}·${x-t}=${r1*t+r2*(x-t)}.`)},
quadratica(l){let a=P([-3,-2,-1,1,2,3]),b=R(-5,5),c=R(-8,8),x=R(-3,3);if(l<3)return E(`Calcule f(${x}) para f(x)=${a}x²${b>=0?'+':''}${b}x${c>=0?'+':''}${c}.`,'Calcule x² primeiro.',`f(${x})=${a*x*x+b*x+c}.`);return E(`Na função f(x)=${a}x²${b>=0?'+':''}${b}x${c>=0?'+':''}${c}, a concavidade é para cima ou para baixo?`,'O sinal de a decide.',a>0?'Para cima, pois a>0.':'Para baixo, pois a<0.')},
parabola(l){let a=P([1,2,3]),h=R(-4,4),k=R(-8,8);if(l<3)return E(`Em f(x)=${a}(x−${h})²${k>=0?'+':''}${k}, qual é o vértice?`,'Compare com a(x−h)²+k.',`V=(${h},${k}).`);return E(`A parábola y=${a}(x−${h})²${k>=0?'+':''}${k} possui máximo ou mínimo? Qual valor?`,'Veja o sinal de a.',`Como a>0, há mínimo igual a ${k}, no vértice (${h},${k}).`)},
quadrado(l){let a=R(1,6),x=R(2,7);if(l<3)return E(`Se y=${a}x², calcule y para x=${x}.`,'Eleve x ao quadrado.',`y=${a}·${x*x}=${a*x*x}.`);return E(`Em y=${a}x², x dobra. Por qual fator y é multiplicado?`,'Compare (2x)² com x².','Por 4, pois (2x)²=4x².')},
transformacoes(l){let h=R(1,5),k=R(1,6);if(l<3)return E(`Comparando y=x² e y=x²+${k}, o que muda no gráfico?`,'Somar fora do quadrado altera a altura.',`A parábola sobe ${k} unidades.`);return E(`Comparando y=x² e y=(x−${h})², para onde o gráfico se desloca?`,'Observe o sinal dentro do parêntese.',`Desloca-se ${h} unidades para a direita.`)},
pa(l){let a1=R(1,12),r=R(2,10),n=R(4,12);if(l<3)return E(`Na PA ${a1}, ${a1+r}, ${a1+2*r}, ... qual é a razão e o ${n}º termo?`,'Use an=a1+(n−1)r.',`r=${r}; a${n}=${a1}+${n-1}·${r}=${a1+(n-1)*r}.`);return E(`Uma sequência tem a1=${a1} e cresce ${r} por etapa. Escreva a regra para an e relacione-a a uma função afim.`,'Use n como variável discreta.',`an=${a1}+(n−1)${r}=${r}n${a1-r>=0?'+':''}${a1-r}. É afim em domínio discreto.`)},
tangente(l){let o=R(3,15),a=R(3,15);if(l<3)return E(`Num triângulo retângulo, cateto oposto=${o} e adjacente=${a}. Calcule tan(θ).`,'tan=oposto/adjacente.',`tan(θ)=${o}/${a}≈${F(o/a)}.`);let ang=P([30,45,60]),t={30:Math.sqrt(3)/3,45:1,60:Math.sqrt(3)}[ang];return E(`Uma reta forma ${ang}° com o eixo x. Qual é seu coeficiente angular?`,'m=tan(θ).',`m=tan(${ang}°)≈${F(t)}.`)},
porcentagem(l){let p=P([5,8,10,12,15,20,25,30]),v=R(5,30)*20;if(l===1)return E(`Calcule ${p}% de ${BR(v)}.`,'Use p/100·valor.',`${p/100}·${v}=${BR(v*p/100)}.`);if(l<4)return E(`Um valor de ${BR(v)} aumenta ${p}%. Qual é o novo valor?`,'Calcule o aumento e some.',`${BR(v)}+${BR(v*p/100)}=${BR(v*(1+p/100))}.`);let i=P([1,2,3,4])/100,t=R(2,6),c=R(5,20)*100;return E(`${BR(c)} rendem ${i*100}% ao mês por ${t} meses, a juros compostos. Calcule o montante aproximado.`,'M=C(1+i)^t.',`M=${c}(1+${i})^${t}≈${BR(c*(1+i)**t)}.`)},
ladrilhamento(l){let n=P([3,4,6]),ang=(n-2)*180/n;if(l<3)return E(`Um polígono regular de ${n} lados tem ângulo interno ${F(ang)}°. Quantas peças completam 360°?`,'Divida 360 pelo ângulo.',`${360/F(ang)} peças.`);n=P([5,7,8,9,10]);ang=(n-2)*180/n;return E(`Um ${n}-gono regular, com ângulo interno ${F(ang)}°, ladrilha sozinho em torno de um vértice?`,'Veja se 360°/ângulo é inteiro.',`360/${F(ang)}≈${F(360/ang)}. Como não é inteiro, não fecha sozinho.`)},
grandezas(l){let d=R(6,30)*10,t=P([2,3,4,5]);if(l<3)return E(`Um veículo percorre ${d} km em ${t} h. Qual é a velocidade média?`,'v=d/t.',`${d}/${t}=${F(d/t)} km/h.`);if(l<5){let mb=R(4,20)*100,s=R(4,20);return E(`Um arquivo de ${mb} MB é transferido em ${s} s. Calcule a taxa média.`,'dados/tempo.',`${mb}/${s}=${F(mb/s)} MB/s.`)}let m=R(20,80)*10,v=R(2,10)*10;return E(`Uma amostra tem ${m} g e ${v} cm³. Calcule a densidade.`,'d=m/V.',`${m}/${v}=${F(m/v)} g/cm³.`)},
dados(l){if(l===1){let a=R(2,6),b=R(3,8),c=R(1,5);return E(`As frequências são A=${a}, B=${b}, C=${c}. Quantas respostas houve?`,'Some as frequências.',`${a}+${b}+${c}=${a+b+c}.`)}if(l<4){let t=P([20,25,40,50,80,100]),c=R(1,Math.floor(t/2));return E(`Em ${t} respostas, ${c} escolheram uma opção. Qual é a frequência relativa?`,'c/t·100.',`${c}/${t}·100=${F(c/t*100)}%.`)}return E('Um diagrama de dispersão mostra que, em geral, quando x aumenta, y também aumenta. Isso prova que x causa y?','Associação não é o mesmo que causalidade.','Não. O gráfico sugere associação positiva, mas não prova causa e efeito.')}
};
window.DSMathGeneratorData={names,levels,G,R,P,F,BR};
})();